// Game fixtures use town SQLite migrations; 0016+ are shared-directory migrations.
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {socialAction,socialState,messages,canVisit,visitHome,syncVisit,sharedRoom,indoorHeartbeat,leaveVisit} from '../db/social.ts';
import {interiorAction} from '../db/interiors.ts';
const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');for(const f of readdirSync(new URL('../drizzle/',import.meta.url)).filter(f=>f.endsWith('.sql')&&Number(f.slice(0,4))<=15).sort())sql.exec(readFileSync(new URL('../drizzle/'+f,import.meta.url),'utf8'));
const d={prepare(query){const stmt=sql.prepare(query);let args=[];return{bind(...a){args=a;return this},async first(){return stmt.get(...args)??null},async all(){return{results:stmt.all(...args)}},execute(){return{meta:{changes:Number(stmt.run(...args).changes)}}},async run(){return this.execute()}}},async batch(statements){sql.exec('BEGIN');try{const results=statements.map(s=>s.execute());sql.exec('COMMIT');return results}catch(e){sql.exec('ROLLBACK');throw e}}};
const now=Date.now();sql.exec("INSERT INTO towns(id,name,created) VALUES('town','Town',0),('other','Other',0)");for(const [id,home]of [['a',0],['b',1],['c',2],['d',3]])sql.prepare('INSERT INTO residents(id,token_hash,town_id,name,color,home,job,seen,created) VALUES(?,?,?,?,?,?,?,?,?)').run(id,id,'town',id,'#fff',home,'mow',now,now);
const row=id=>sql.prepare('SELECT * FROM residents WHERE id=?').get(id),act=(id,action,body={},at=now)=>socialAction(d,row(id),{action,...body},at);
assert.equal(await canVisit(d,row('b'),row('a')),false);
assert.equal((await act('a','message',{to:'b',text:'Hello',id:'aaaaaaaa-aaaaaaaa'})).status,403);
assert.equal(await act('a','request',{to:'b'}),null);assert.equal(await act('b','request',{to:'a'}),null);assert.equal(sql.prepare('SELECT COUNT(*) n FROM friendships').get().n,1);
assert.equal((await act('a','accept',{to:'b'})).status,409,'Sender cannot accept own request');assert.equal(await act('b','accept',{to:'a'}),null);
assert.equal(await act('a','access',{access:'friends'}),null);assert.equal(await canVisit(d,row('b'),row('a')),true);assert.equal(await canVisit(d,row('c'),row('a')),false);
assert.equal(await act('a','message',{to:'b',text:'Hello, neighbor!',id:'aaaaaaaa-aaaaaaaa'}),null);
assert.equal(await act('a','message',{to:'b',text:'retry',id:'aaaaaaaa-aaaaaaaa'}),null,'Idempotent retry');assert.equal((await act('a','message',{to:'b',text:'too soon',id:'bbbbbbbb-bbbbbbbb'})).status,429);
assert.equal((await messages(d,row('b'),'a')).messages.length,1);assert.equal((await messages(d,row('c'),'a')).status,403);
assert.equal((await socialState(d,row('b'),now)).unread[0].count,1);await act('b','read',{to:'a',through:now});assert.equal((await socialState(d,row('b'),now)).unread.length,0);
assert.equal(await act('a','invite',{to:'b'}),null);assert.equal((await socialState(d,row('b'),now)).invitations.length,1);assert.equal((await visitHome(d,row('c'),{host:'a'},now)).status,403);
assert.equal(await visitHome(d,row('b'),{host:'a',invitation:true},now),null);assert.equal(row('b').visit_host,'a');assert.equal(row('b').inside,1);assert.equal(row('b').shift,null);
assert.equal((await interiorAction(d,row('b'),{action:'home-place',item:'plant-fern',revision:row('b').interior_revision,x:0,z:0,rotation:0},now)).status,403,'Guests cannot spend or edit');
let room=await sharedRoom(d,row('b'),now);assert.equal(room.owner,'a');assert.equal(room.peers[0].id,'b');
await indoorHeartbeat(d,row('b'),{room:'a',roomRevision:row('b').interior_revision,indoorX:1,indoorZ:1,level:0},now+1000);assert.equal(row('b').indoor_x,1);
await indoorHeartbeat(d,row('b'),{room:'a',roomRevision:0,indoorX:2,indoorZ:2,level:0},now+2000);assert.equal(row('b').indoor_x,1,'Stale room movement ignored');
await act('a','access',{access:'nobody'});assert.equal(row('b').inside,0,'Changing access removes existing guests');assert.equal(await sharedRoom(d,row('b'),now),null);
await act('a','access',{access:'everyone'});assert.equal(await visitHome(d,row('c'),{host:'a'},now),null);assert.equal((await sharedRoom(d,row('c'),now)).owner,'a');await leaveVisit(d,row('c'));assert.equal(row('c').inside,0);
await act('a','invite',{to:'c'},now+60001);assert.equal((await visitHome(d,row('c'),{host:'a',invitation:true},now+31*60000)).status,409,'Expired invitations cannot be used');
await act('a','access',{access:'friends'});await visitHome(d,row('b'),{host:'a'},now);await act('a','remove',{to:'b'});assert.equal(row('b').inside,0,'Unfriending removes friends-only visitors');assert.equal((await messages(d,row('b'),'a')).status,403);assert.equal((await act('a','message',{to:'b',text:'No longer friends',id:'cccccccc-cccccccc'},now+5000)).status,403);
await act('a','access',{access:'everyone'});await visitHome(d,row('c'),{host:'a'},now);sql.prepare("UPDATE residents SET town_id='other' WHERE id='a'").run();await syncVisit(d,row('c'));assert.equal(row('c').inside,0,'Host moving towns removes guest');assert.equal((await visitHome(d,row('c'),{host:'a'},now)).status,403);
sql.prepare('UPDATE residents SET seen=0 WHERE id=?').run('d');assert.equal((await act('b','request',{to:'d'})).status,400,'Friend discovery only online neighbors');
console.log('PASS: mutual friends, private messages and unread state, throttling/retry, all access modes, invitations and expiry, shared room presence, stale movement, read-only visits, revocation and town moves.');
