'use client';
import {useCallback,useEffect,useState} from 'react';
import {KeyRound,LoaderCircle,Trash2} from 'lucide-react';
import {authClient,passkeyError,supportsPasskeys} from './authClient';
type SavedPasskey={id:string;name?:string|null;createdAt?:Date|string|null};
export default function PasskeySettings(){
 const [keys,setKeys]=useState<SavedPasskey[]>([]),[loading,setLoading]=useState(true),[supported,setSupported]=useState(false),[busy,setBusy]=useState(''),[name,setName]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[remove,setRemove]=useState<string|null>(null);
 const load=useCallback(async()=>{setLoading(true);try{const result=await authClient.passkey.listUserPasskeys();if(result.error)throw result.error;setKeys(result.data??[])}catch{setError('We couldn’t load your passkeys. Please try again.')}finally{setLoading(false)}},[]);
 useEffect(()=>{setSupported(supportsPasskeys());void load()},[load]);
 async function add(){if(busy)return;setBusy('add');setError('');setNotice('');try{const result=await authClient.passkey.addPasskey({name:name.trim()||undefined});if(result.error){setError(passkeyError(result.error,'add'));return}setName('');setNotice('Passkey added. Use “Log in with a passkey” next time.');await load()}catch{setError('We couldn’t add your passkey. Please try again.')}finally{setBusy('')}}
 async function deleteKey(id:string){if(busy)return;setBusy(id);setError('');setNotice('');try{const result=await authClient.passkey.deletePasskey({id});if(result.error){setError(passkeyError(result.error,'remove'));return}setRemove(null);setNotice('Passkey removed. You can still sign in with your password.');await load()}catch{setError('We couldn’t remove that passkey. Please try again.')}finally{setBusy('')}}
 return <section className="passkey-settings" aria-labelledby="passkey-heading"><h3 id="passkey-heading"><KeyRound size={19}/>Passkeys</h3><p>Sign in with Face ID, Touch ID, your device PIN, or a security key. Your password will still work.</p>
 {loading?<p role="status">Loading your passkeys…</p>:keys.length?<ul>{keys.map(key=><li key={key.id}><div><strong>{key.name||'Passkey'}</strong>{key.createdAt&&<small>Added {new Date(key.createdAt).toLocaleDateString()}</small>}</div>{remove===key.id?<div className="passkey-remove"><span>Remove this passkey?</span><button className="secondary-button" disabled={!!busy} onClick={()=>void deleteKey(key.id)}>Remove</button><button disabled={!!busy} onClick={()=>setRemove(null)}>Cancel</button></div>:<button className="icon-button" aria-label={`Remove ${key.name||'passkey'}`} disabled={!!busy} onClick={()=>setRemove(key.id)}><Trash2 size={17}/></button>}</li>)}</ul>:<p>No passkeys added yet.</p>}
 {supported?<><label htmlFor="passkey-name">Passkey name <small>(optional)</small></label><input id="passkey-name" maxLength={48} placeholder="e.g. My iPhone" value={name} disabled={!!busy} onChange={e=>setName(e.target.value)}/><button className="secondary-button full" disabled={!!busy||loading} onClick={()=>void add()}>{busy==='add'?<LoaderCircle size={17} className="animate-spin"/>:<KeyRound size={17}/>}Add a passkey</button></>:<p>Your browser doesn’t offer passkeys here. Try an up-to-date browser on a secure connection.</p>}
 {notice&&<p role="status" className="passkey-notice">{notice}</p>}{error&&<p role="alert" className="account-error">{error}<button className="passkey-reload" disabled={!!busy} onClick={()=>{setError('');void load()}}>Refresh passkeys</button></p>}</section>;
}
