import {gameIdentity} from '@/db/auth';
import {db} from '@/db/raw';
import {chatRead,mergeChatRead,type ChatRead} from '../shared/chat-read';
import {hasProfanity,CHAT_LANGUAGE_ERROR} from './profanity';
const json=(b:unknown,status=200)=>Response.json(b,{status,headers:{'Cache-Control':'no-store'}});
async function citizen(req:Request){const account=await gameIdentity(req);if(!account)return null;const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(account))),b=>b.toString(16).padStart(2,'0')).join('');return db().prepare('SELECT id,town_id,name,job,home FROM residents WHERE token_hash=?').bind(hash).first<{id:string;town_id:string;name:string;job:string|null;home:number|null}>();}
async function savedRead(town:string,resident:string,channel:string):Promise<ChatRead>{
 const row=await db().prepare('SELECT created,ids FROM chat_read_positions WHERE town_id=? AND resident_id=? AND channel=?').bind(town,resident,channel).first<{created:number;ids:string}>();
 return row?chatRead({created:row.created,ids:JSON.parse(row.ids)}):chatRead(null);
}
async function markRead(r:{id:string;town_id:string},channel:string,value:unknown){
 const cursor=chatRead(value);
 if(cursor.created>Date.now())return json({error:'Invalid read position.'},400);
 if(!cursor.created)return json({read:await savedRead(r.town_id,r.id,channel),changed:false});
 // Only acknowledge a boundary this resident could actually have loaded.
 const rows=cursor.ids.length?await db().prepare(`SELECT id FROM chat_messages WHERE town_id=? AND channel=? AND created=? AND id IN (${cursor.ids.map(()=>'?').join(',')})`).bind(r.town_id,channel,cursor.created,...cursor.ids).all<{id:string}>():{results:[]};
 if(!rows.results.length)return json({error:'Reload this conversation before marking it read.'},400);
 const ids=JSON.stringify(rows.results.map(m=>m.id).sort());
 // Merge atomically so delayed writes from another device never rewind progress.
 const changed=await db().prepare(`INSERT INTO chat_read_positions(town_id,resident_id,channel,created,ids) VALUES(?,?,?,?,?)
 ON CONFLICT(town_id,resident_id,channel) DO UPDATE SET
 created=excluded.created,
 ids=CASE WHEN excluded.created>chat_read_positions.created THEN excluded.ids ELSE
 (SELECT json_group_array(value) FROM (SELECT value FROM json_each(chat_read_positions.ids) UNION SELECT value FROM json_each(excluded.ids) ORDER BY value LIMIT 60)) END
 WHERE excluded.created>chat_read_positions.created OR (excluded.created=chat_read_positions.created AND EXISTS(SELECT value FROM json_each(excluded.ids) EXCEPT SELECT value FROM json_each(chat_read_positions.ids)))
 RETURNING resident_id`).bind(r.town_id,r.id,channel,cursor.created,ids).first();
 return json({read:await savedRead(r.town_id,r.id,channel),changed:!!changed,readerId:r.id});
}
export async function GET(req:Request){try{const r=await citizen(req);if(!r||r.home===null)return json({error:'Join a town to chat.'},401);const expectedTown=new URL(req.url).searchParams.get('town');if(expectedTown&&expectedTown!==r.town_id)return json({error:'Your resident has moved. Reopen chat in your current town.'},409);const channel=new URL(req.url).searchParams.get('channel')??'town';if(channel!=='town'&&channel!==r.job)return json({error:'This profession channel is for residents with that regular job.'},403);const params=new URL(req.url).searchParams;if(params.get('summary')==='1'){const read=await savedRead(r.town_id,r.id,channel);const cursor=mergeChatRead(read,chatRead({created:Number(params.get('after')??0),ids:(params.get('seen')??'').split(',')}));const boundary=cursor.ids.length?` AND m.id NOT IN (${cursor.ids.map(()=>'?').join(',')})`:'';const count=await db().prepare(`SELECT COUNT(*) AS unread FROM chat_messages m JOIN residents author ON author.id=m.resident_id WHERE m.town_id=? AND m.channel=? AND m.resident_id<>? AND (m.created>? OR (m.created=?${boundary}))`).bind(r.town_id,channel,r.id,cursor.created,cursor.created,...cursor.ids).first<{unread:number}>();return json({unread:count?.unread??0,read});}const rows=await db().prepare('SELECT m.id,m.resident_id AS resident,r.name,m.text,m.created FROM chat_messages m JOIN residents r ON r.id=m.resident_id WHERE m.town_id=? AND m.channel=? ORDER BY m.created DESC,m.id DESC LIMIT 60').bind(r.town_id,channel).all();return json({messages:rows.results.reverse()});}catch{return json({error:'Chat is reconnecting. Please try again.'},503);}}
export async function POST(req:Request){try{const origin=req.headers.get('origin');if(origin&&new URL(origin).host!==new URL(req.url).host)return json({error:'Use your own town page.'},403);const r=await citizen(req);if(!r||r.home===null)return json({error:'Join a town to chat.'},401);const b=await req.json() as any;if(b.townId!==undefined&&b.townId!==r.town_id)return json({error:'Your resident has moved. Reopen chat before sending.'},409);if(b.channel!=='town'&&b.channel!==r.job)return json({error:'Choose town chat or your regular profession.'},403);if(b.action==='read')return await markRead(r,b.channel,b.read);if(typeof b.text!=='string'||!b.text.trim()||b.text.trim().length>300||typeof b.id!=='string'||!/^[a-zA-Z0-9-]{16,50}$/.test(b.id))return json({error:'Write a message of 1–300 characters.'},400);if(hasProfanity(b.text))return json({error:CHAT_LANGUAGE_ERROR},400);const d=db(),existing=await d.prepare('SELECT resident_id FROM chat_messages WHERE id=?').bind(b.id).first<{resident_id:string}>();if(existing)return existing.resident_id===r.id?json({saved:true}):json({error:'Please try sending again.'},409);const now=Date.now();const saved=await d.prepare('INSERT INTO chat_messages(id,town_id,resident_id,channel,text,created) SELECT ?,?,?,?,?,? WHERE NOT EXISTS(SELECT 1 FROM chat_messages WHERE resident_id=? AND created>?) AND EXISTS(SELECT 1 FROM residents WHERE id=? AND town_id=?) RETURNING id').bind(b.id,r.town_id,r.id,b.channel,b.text.trim(),now,r.id,now-2000,r.id,r.town_id).first();if(!saved)return json({error:'Give your neighbors a moment — try again in two seconds.'},429);return json({saved:true});}catch(error){console.error('Chat write failed',error);return json({error:'Your message was not sent. Please try again.'},503);}}
