import {sql} from 'drizzle-orm';
import {sqliteTable,text,integer,real,uniqueIndex,index,primaryKey,foreignKey} from 'drizzle-orm/sqlite-core';
export const towns=sqliteTable('towns',{id:text('id').primaryKey(),name:text('name').notNull(),invite:text('invite').unique(),private:integer('private').notNull().default(0),treasury:integer('treasury').notNull().default(0),project:integer('project').notNull().default(0),tax:integer('tax').notNull().default(1),term:text('term').notNull().default(''),featured:text('featured'),created:integer('created').notNull()});
export const residents=sqliteTable('residents',{id:text('id').primaryKey(),tokenHash:text('token_hash').notNull().unique(),townId:text('town_id').notNull().references(()=>towns.id),name:text('name').notNull(),color:text('color').notNull(),home:integer('home'),job:text('job'),coins:integer('coins').notNull().default(150),xp:integer('xp').notNull().default(0),education:integer('education').notNull().default(0),lastStudy:text('last_study'),x:real('x').notNull().default(0),z:real('z').notNull().default(6),shift:text('shift'),papers:integer('papers').notNull().default(12),parcels:integer('parcels').notNull().default(6),water:integer('water').notNull().default(8),bag:integer('bag').notNull().default(0),actionTarget:text('action_target'),actionStarted:integer('action_started').notNull().default(0),mowing:integer('mowing').notNull().default(0),items:text('items').notNull().default('[]'),seen:integer('seen').notNull(),created:integer('created').notNull()},t=>[uniqueIndex('unique_town_home').on(t.townId,t.home),index('resident_town').on(t.townId)]);
export const work=sqliteTable('work',{key:text('key').primaryKey(),townId:text('town_id').notNull().references(()=>towns.id),task:text('task').notNull(),residentId:text('resident_id').notNull().references(()=>residents.id),started:integer('started').notNull(),lastStep:integer('last_step').notNull().default(0),steps:integer('steps').notNull().default(0),completed:integer('completed').notNull().default(0)},t=>[index('work_town').on(t.townId)]);
export const events=sqliteTable('events',{id:text('id').primaryKey(),townId:text('town_id').notNull().references(()=>towns.id),name:text('name').notNull(),text:text('text').notNull(),created:integer('created').notNull()},t=>[index('event_town_time').on(t.townId,t.created)]);

export const lawnCells=sqliteTable('lawn_cells',{key:text('key').primaryKey(),townId:text('town_id').notNull().references(()=>towns.id),cell:text('cell').notNull(),cutAt:integer('cut_at').notNull()},t=>[index('lawn_town').on(t.townId)]);

export const worldWork=sqliteTable('world_work',{key:text('key').primaryKey(),townId:text('town_id').notNull().references(()=>towns.id),objectId:text('object_id').notNull(),targetId:text('target_id').notNull(),completed:integer('completed').notNull()},t=>[index('world_work_town').on(t.townId)]);

export const electionCandidates=sqliteTable('election_candidates',{townId:text('town_id').notNull().references(()=>towns.id),cycle:text('cycle').notNull(),residentId:text('resident_id').notNull().references(()=>residents.id),nominatedAt:integer('nominated_at').notNull(),platform:text('platform'),tax:integer('tax').notNull().default(1)},t=>[primaryKey({columns:[t.townId,t.cycle,t.residentId]})]);
export const electionVotes=sqliteTable('election_votes',{townId:text('town_id').notNull().references(()=>towns.id),cycle:text('cycle').notNull(),voterId:text('voter_id').notNull().references(()=>residents.id),candidateId:text('candidate_id').notNull(),castAt:integer('cast_at').notNull()},t=>[primaryKey({columns:[t.townId,t.cycle,t.voterId]}),foreignKey({columns:[t.townId,t.cycle,t.candidateId],foreignColumns:[electionCandidates.townId,electionCandidates.cycle,electionCandidates.residentId]}),index('election_vote_tally').on(t.townId,t.cycle,t.candidateId)]);

// One authoritative daily summary per resident and town; retained across job changes.
export const contributions=sqliteTable('contributions',{townId:text('town_id').notNull().references(()=>towns.id),residentId:text('resident_id').notNull().references(()=>residents.id),day:text('day').notNull(),xp:integer('xp').notNull().default(0),mow:integer('mow').notNull().default(0),paper:integer('paper').notNull().default(0),clean:integer('clean').notNull().default(0),garden:integer('garden').notNull().default(0),deliver:integer('deliver').notNull().default(0),task:integer('task').notNull().default(0),tax:integer('tax').notNull().default(0),donated:integer('donated').notNull().default(0)},t=>[primaryKey({columns:[t.townId,t.residentId,t.day]})]);

export const townProjects=sqliteTable('town_projects',{townId:text('town_id').notNull().references(()=>towns.id),id:text('id').notNull(),funded:integer('funded').notNull().default(0),completed:integer('completed').notNull().default(0),mayorId:text('mayor_id').references(()=>residents.id)},t=>[primaryKey({columns:[t.townId,t.id]})]);
export const civicHistory=sqliteTable('civic_history',{id:text('id').primaryKey(),townId:text('town_id').notNull().references(()=>towns.id),name:text('name').notNull(),kind:text('kind').notNull(),project:text('project'),amount:integer('amount').notNull().default(0),created:integer('created').notNull()},t=>[index('civic_history_town_time').on(t.townId,t.created)]);

export const charterInstitutions=sqliteTable('charter_institutions',{townId:text('town_id').notNull().references(()=>towns.id),id:text('id').notNull(),node:text('node').notNull(),plot:text('plot').notNull()},t=>[primaryKey({columns:[t.townId,t.id]}),uniqueIndex('charter_institution_plot').on(t.townId,t.plot)]);
export const townTerritories=sqliteTable('town_territories',{townId:text('town_id').notNull().references(()=>towns.id),id:text('id').notNull()},t=>[primaryKey({columns:[t.townId,t.id]})]);
export const parcelBuildings=sqliteTable('parcel_buildings',{townId:text('town_id').notNull().references(()=>towns.id),plot:text('plot').notNull(),kind:text('kind').notNull()},t=>[primaryKey({columns:[t.townId,t.plot]})]);
export const townPlans=sqliteTable('town_plans',{id:text('id').primaryKey(),townId:text('town_id').notNull().references(()=>towns.id),kind:text('kind').notNull(),institution:text('institution'),option:text('option').notNull(),fromNode:text('from_node'),fromPlot:text('from_plot'),cost:integer('cost').notNull(),funded:integer('funded').notNull().default(0),status:text('status').notNull().default('voting'),created:integer('created').notNull(),closes:integer('closes').notNull(),electorate:integer('electorate').notNull(),quorum:integer('quorum').notNull(),name:text('name').notNull()},t=>[index('town_plan_history').on(t.townId,t.created),uniqueIndex('one_live_town_plan').on(t.townId).where(sql`${t.status} IN ('voting','approved')`)]);
export const planVoters=sqliteTable('plan_voters',{planId:text('plan_id').notNull().references(()=>townPlans.id),residentId:text('resident_id').notNull().references(()=>residents.id),vote:integer('vote')},t=>[primaryKey({columns:[t.planId,t.residentId]})]);
