import {hasProfanity,CHAT_LANGUAGE_ERROR} from '../server/profanity';
import {HOMES} from '../app/game/data.ts';
import {homeDoor,readInterior,roomSize,floorCount} from '../app/game/interiors.ts';
export type SocialResident={move_owner?:string;move_epoch?:number;id:string;town_id:string;home:number|null;name:string;seen:number;inside:number;visit_host:string|null;home_access:string;house:string;interior:string;interior_revision:number;indoor_x:number;indoor_z:number;indoor_level:number};
const pair=(a:string,b:string)=>[a,b].sort();
const fail=(error:string,status=400)=>({error,status});
export async function areFriends(d:D1Database,a:string,b:string){return !!await d.prepare('SELECT 1 FROM friendships WHERE a=? AND b=? AND accepted=1').bind(...pair(a,b)).first();}
export async function canVisit(d:D1Database,r:SocialResident,host:SocialResident|null){return !!host&&host.home!==null&&r.town_id===host.town_id&&(r.id===host.id||host.home_access==='everyone'||host.home_access==='friends'&&await areFriends(d,r.id,host.id));}
export async function leaveVisit(d:D1Database,r:SocialResident){const host=r.visit_host?await d.prepare('SELECT * FROM residents WHERE id=?').bind(r.visit_host).first<SocialResident>():r;const h=host?.town_id===r.town_id&&host.home!==null?host.home:r.home;const door=h!==null?homeDoor(HOMES[h]):{x:0,z:6};await d.prepare('UPDATE residents SET inside=0,visit_host=NULL,indoor_level=0,interior_revision=interior_revision+1,x=?,z=?,emote=NULL,emote_until=0 WHERE id=? AND inside=1').bind(door.x,door.z,r.id).run();}
export async function syncVisit(d:D1Database,r:SocialResident){if(!r.inside||!r.visit_host)return r;const host=await d.prepare('SELECT * FROM residents WHERE id=?').bind(r.visit_host).first<SocialResident>();if(!await canVisit(d,r,host)){await leaveVisit(d,r);return (await d.prepare('SELECT * FROM residents WHERE id=?').bind(r.id).first<SocialResident>())!;}return r;}
export async function sharedRoom(d:D1Database,r:SocialResident,now:number){if(!r.inside)return null;const host=r.visit_host?await d.prepare('SELECT * FROM residents WHERE id=?').bind(r.visit_host).first<SocialResident>():r;if(!await canVisit(d,r,host)||!host)return null;const peers=await d.prepare('SELECT id,name,color,outfit,hat,accessory,indoor_x AS x,indoor_z AS z,indoor_level AS level,emote,emote_until AS emoteUntil FROM residents WHERE town_id=? AND inside=1 AND COALESCE(visit_host,id)=? AND seen>?').bind(r.town_id,host.id,now-12000).all();return {owner:host.id,name:host.name,home:host.home,house:host.house,interior:readInterior(host.interior),revision:host.interior_revision,peers:peers.results};}
export async function indoorHeartbeat(d:D1Database,r:SocialResident,b:Record<string,any>,now:number){const host=r.visit_host?await d.prepare('SELECT * FROM residents WHERE id=?').bind(r.visit_host).first<SocialResident>():r;if(!host)return;const size=roomSize(host.house);let x=r.indoor_x,z=r.indoor_z,level=r.indoor_level;if(b.room===host.id&&b.roomRevision===r.interior_revision&&Number.isInteger(b.level)&&b.level>=0&&b.level<floorCount(host.house)&&Number.isFinite(b.indoorX)&&Number.isFinite(b.indoorZ)){x=Math.max(-size.width/2+.25,Math.min(size.width/2-.25,b.indoorX));z=Math.max(-size.depth/2+.25,Math.min(size.depth/2-.25,b.indoorZ));level=b.level;}await d.prepare('UPDATE residents SET seen=MAX(seen,?),move_updated=MAX(?,move_updated+1),indoor_x=?,indoor_z=?,indoor_level=? WHERE id=? AND inside=1 AND interior_revision=? AND move_owner=? AND move_epoch=?').bind(now,now,x,z,level,r.id,r.interior_revision,r.move_owner??'',r.move_epoch??0).run();}
export async function socialState(d:D1Database,r:SocialResident,now=Date.now()){
 const [people,links,invitations,unread]=await Promise.all([
 d.prepare('SELECT id,name,color,job,home,home_access AS access,inside,seen,town_id AS town FROM residents WHERE town_id=? AND home IS NOT NULL AND id<>? AND seen>? ORDER BY name').bind(r.town_id,r.id,now-12000).all(),
 d.prepare('SELECT f.requester,f.accepted,r.id,r.name,r.color,r.home,r.home_access AS access,r.inside,r.seen,r.town_id AS town FROM friendships f JOIN residents r ON r.id=CASE WHEN f.a=? THEN f.b ELSE f.a END WHERE f.a=? OR f.b=? ORDER BY r.name').bind(r.id,r.id,r.id).all(),
 d.prepare('SELECT i.host,i.expires,r.name FROM home_invitations i JOIN residents r ON r.id=i.host WHERE i.guest=? AND i.town_id=? AND r.town_id=i.town_id AND i.expires>?').bind(r.id,r.town_id,now).all(),
 d.prepare('SELECT sender,COUNT(*) AS count FROM direct_messages WHERE recipient=? AND read=0 AND EXISTS(SELECT 1 FROM friendships WHERE a=MIN(sender,recipient) AND b=MAX(sender,recipient) AND accepted=1) GROUP BY sender').bind(r.id).all()]);
 return {self:r.id,access:r.home_access,people:people.results,friends:links.results,invitations:invitations.results,unread:unread.results,now};
}
export async function messages(d:D1Database,r:SocialResident,to:string){if(!await areFriends(d,r.id,to))return fail('Private messages are for accepted friends.',403);const rows=await d.prepare('SELECT id,sender,text,created FROM direct_messages WHERE (sender=? AND recipient=?) OR (sender=? AND recipient=?) ORDER BY created DESC,id DESC LIMIT 60').bind(r.id,to,to,r.id).all();return {messages:rows.results.reverse()};}
export async function socialAction(d:D1Database,r:SocialResident,b:Record<string,any>,now=Date.now()){
 if(b.action==='access'){if(!['friends','everyone','nobody'].includes(b.access))return fail('Choose who may visit.');await d.prepare('UPDATE residents SET home_access=? WHERE id=?').bind(b.access,r.id).run();const guests=await d.prepare('SELECT * FROM residents WHERE visit_host=? AND inside=1').bind(r.id).all<SocialResident>();for(const guest of guests.results)await syncVisit(d,guest);return null;}
 const to=typeof b.to==='string'?b.to:'';if(!to||to===r.id)return fail('Choose another resident.');const target=await d.prepare('SELECT * FROM residents WHERE id=?').bind(to).first<SocialResident>();if(!target||target.home===null)return fail('This neighbor is unavailable.',404);const [a,c]=pair(r.id,to);
 if(b.action==='request'){if(target.town_id!==r.town_id||target.seen<now-12000)return fail('Choose a neighbor who is online in your town.');await d.prepare('INSERT OR IGNORE INTO friendships(a,b,requester,accepted,created) SELECT ?,?,?,0,? WHERE EXISTS(SELECT 1 FROM residents me JOIN residents them ON me.town_id=them.town_id WHERE me.id=? AND them.id=? AND them.seen>?)').bind(a,c,r.id,now,r.id,to,now-12000).run();return null;}
 if(b.action==='accept'){const v=await d.prepare('UPDATE friendships SET accepted=1 WHERE a=? AND b=? AND requester=? AND accepted=0').bind(a,c,to).run();return v.meta.changes?null:fail('That friend request is no longer pending.',409);}
 if(b.action==='remove'){await d.batch([d.prepare('DELETE FROM friendships WHERE a=? AND b=?').bind(a,c),d.prepare('DELETE FROM home_invitations WHERE (host=? AND guest=?) OR (host=? AND guest=?)').bind(r.id,to,to,r.id)]);await syncVisit(d,r);await syncVisit(d,target);return null;}
 if(b.action==='invite'){if(target.town_id!==r.town_id||target.seen<now-12000||!await canVisit(d,target,r))return fail('Open your home to this neighbor before inviting them.');await d.prepare('INSERT INTO home_invitations(host,guest,town_id,created,expires) VALUES(?,?,?,?,?) ON CONFLICT(host,guest) DO UPDATE SET created=excluded.created,expires=excluded.expires WHERE home_invitations.created<?').bind(r.id,to,r.town_id,now,now+30*60000,now-60000).run();return null;}
 if(b.action==='dismiss'){await d.prepare('DELETE FROM home_invitations WHERE host=? AND guest=?').bind(to,r.id).run();return null;}
 if(b.action==='read'){if(!await areFriends(d,r.id,to))return fail('This conversation is no longer available.',403);await d.prepare('UPDATE direct_messages SET read=1 WHERE sender=? AND recipient=? AND created<=?').bind(to,r.id,Number.isFinite(b.through)?Math.min(now,b.through):0).run();return null;}
 if(b.action==='message'){if(!await areFriends(d,r.id,to))return fail('Private messages are for accepted friends.',403);if(typeof b.text!=='string'||!b.text.trim()||b.text.trim().length>300||typeof b.id!=='string'||!/^[a-zA-Z0-9-]{16,50}$/.test(b.id))return fail('Write a message of 1–300 characters.');if(hasProfanity(b.text))return fail(CHAT_LANGUAGE_ERROR);const old=await d.prepare('SELECT sender,recipient FROM direct_messages WHERE id=?').bind(b.id).first<{sender:string;recipient:string}>();if(old)return old.sender===r.id&&old.recipient===to?null:fail('Try sending again.',409);const v=await d.prepare('INSERT INTO direct_messages(id,sender,recipient,text,created) SELECT ?,?,?,?,? WHERE EXISTS(SELECT 1 FROM friendships WHERE a=? AND b=? AND accepted=1) AND NOT EXISTS(SELECT 1 FROM direct_messages WHERE sender=? AND created>?)').bind(b.id,r.id,to,b.text.trim(),now,a,c,r.id,now-2000).run();return v.meta.changes?null:fail('Wait a moment before sending again.',429);}
 return fail('Choose a social action.');
}
export async function visitHome(d:D1Database,r:SocialResident,b:Record<string,any>,now:number){const host=await d.prepare('SELECT * FROM residents WHERE id=?').bind(String(b.host??'')).first<SocialResident>();if(!await canVisit(d,r,host)||!host||host.id===r.id)return fail('This home is not open to you right now.',403);if(b.invitation){const invitation=await d.prepare('SELECT 1 FROM home_invitations WHERE host=? AND guest=? AND town_id=? AND expires>?').bind(host.id,r.id,r.town_id,now).first();if(!invitation)return fail('That invitation has expired.',409);}const size=roomSize(host.house);const entered=await d.prepare("UPDATE residents SET inside=1,visit_host=?,indoor_x=0,indoor_z=?,indoor_level=0,interior_revision=interior_revision+1,mowing=0,shift=NULL,riding=0,action_target=NULL,action_started=0,emote=NULL,emote_until=0,seen=? WHERE id=? AND town_id=? AND interior_revision=? AND EXISTS(SELECT 1 FROM residents h WHERE h.id=? AND h.town_id=? AND h.home IS NOT NULL AND (h.home_access='everyone' OR h.home_access='friends' AND EXISTS(SELECT 1 FROM friendships WHERE a=? AND b=? AND accepted=1)))").bind(host.id,size.depth/2-.9,now,r.id,r.town_id,r.interior_revision,host.id,r.town_id,...pair(r.id,host.id)).run();if(!entered.meta.changes)return fail('This home or your location changed. Try visiting again.',409);await d.prepare('DELETE FROM home_invitations WHERE host=? AND guest=?').bind(host.id,r.id).run();return null;}
