export function angleDelta(from:number,to:number){return Math.atan2(Math.sin(to-from),Math.cos(to-from))}
export function installCameraGestures(canvas:HTMLElement,handlers:{mode:()=> 'pan'|'orbit';viewHeight:()=>number;pan:(x:number,y:number)=>void;orbit:(angle:number,pitch?:number)=>void;zoom:(delta:number)=>void;tap:(e:PointerEvent)=>void}){
type Pointer={x:number;y:number;startX:number;startY:number;dragged:boolean;orbit:boolean};
const pointers=new Map<number,Pointer>();let gesture:{x:number;y:number;distance:number;angle:number}|null=null;
function twoFinger(){const [a,b]=[...pointers.values()];if(!a||!b)return null;return{x:(a.x+b.x)/2,y:(a.y+b.y)/2,distance:Math.max(1,Math.hypot(b.x-a.x,b.y-a.y)),angle:Math.atan2(b.y-a.y,b.x-a.x)}}
const pointerDown=(e:PointerEvent)=>{if(e.button!==0&&e.button!==1&&e.button!==2)return;canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,dragged:e.button!==0,orbit:e.button===2||e.shiftKey||handlers.mode()==='orbit'});if(pointers.size>1){for(const p of pointers.values())p.dragged=true;gesture=twoFinger()}};
const pointerMove=(e:PointerEvent)=>{const p=pointers.get(e.pointerId);if(!p)return;const dx=e.clientX-p.x,dy=e.clientY-p.y;p.x=e.clientX;p.y=e.clientY;if(pointers.size>1){const next=twoFinger();if(next&&gesture){handlers.pan(next.x-gesture.x,next.y-gesture.y);handlers.orbit(angleDelta(gesture.angle,next.angle));handlers.zoom(handlers.viewHeight()*(gesture.distance/next.distance-1))}gesture=next;return}if(!p.dragged&&Math.hypot(p.x-p.startX,p.y-p.startY)>8){p.dragged=true;if(p.orbit)handlers.orbit(-(p.x-p.startX)*.007,(p.y-p.startY)*.005);else handlers.pan(p.x-p.startX,p.y-p.startY);return}if(p.dragged){if(p.orbit)handlers.orbit(-dx*.007,dy*.005);else handlers.pan(dx,dy)}};
const click=(e:PointerEvent)=>{const pointer=pointers.get(e.pointerId);pointers.delete(e.pointerId);gesture=null;if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);if(!pointer||pointer.dragged||e.button!==0||Math.hypot(e.clientX-pointer.startX,e.clientY-pointer.startY)>8)return;handlers.tap(e)};
const cancelPointer=(e:PointerEvent)=>{pointers.delete(e.pointerId);gesture=null;for(const p of pointers.values())p.dragged=true};const contextMenu=(e:Event)=>e.preventDefault();
canvas.addEventListener('pointerdown',pointerDown);canvas.addEventListener('pointermove',pointerMove);canvas.addEventListener('pointerup',click);canvas.addEventListener('pointercancel',cancelPointer);canvas.addEventListener('lostpointercapture',cancelPointer);canvas.addEventListener('contextmenu',contextMenu);
return()=>{canvas.removeEventListener('pointerdown',pointerDown);canvas.removeEventListener('pointermove',pointerMove);canvas.removeEventListener('pointerup',click);canvas.removeEventListener('pointercancel',cancelPointer);canvas.removeEventListener('lostpointercapture',cancelPointer);canvas.removeEventListener('contextmenu',contextMenu);pointers.clear()};
}
