'use client';
import {useEffect,useState} from 'react';
import {Coins,MapPin,Landmark,Flag,Check} from 'lucide-react';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Progress} from '@/components/ui/progress';
import {CIVIC_PROJECTS,TAX_POLICIES,projectById,townLevel,type CivicState} from './civicProjects';
import type {TownState} from './data';
export function ProjectPicker({value,onChange,civic,disabled=false}:{value:string;onChange:(id:string)=>void;civic:CivicState;disabled?:boolean}){
 return <RadioGroup className="project-picker" value={value} onValueChange={v=>onChange(String(v))} disabled={disabled} aria-label="Choose a town project">{CIVIC_PROJECTS.map(p=>{const done=civic.projects.some(s=>s.id===p.id&&s.completed);return <label className={`project-choice ${value===p.id?'is-selected':''} ${done?'is-complete':''}`} key={p.id}><div><span className="eyebrow">{p.category}</span><strong>{p.name}</strong><p>{p.description}</p><small>{done?'Completed':`${p.cost.toLocaleString()} coins · +${p.prosperity} prosperity`}</small></div>{done?<Check size={17}/>:<RadioGroupItem value={p.id}/>}</label>})}</RadioGroup>;
}
export function TaxPicker({value,onChange,disabled=false}:{value:number;onChange:(tax:number)=>void;disabled?:boolean}){
 return <RadioGroup className="tax-picker" value={String(value)} onValueChange={v=>onChange(Number(v))} disabled={disabled} aria-label="Work tax policy">{TAX_POLICIES.map(t=><label key={t.value} className={`tax-choice ${value===t.value?'is-selected':''}`}><RadioGroupItem value={String(t.value)}/><span><strong>{t.name} · {t.value} {t.value===1?'coin':'coins'}</strong><small>{t.description}</small></span></label>)}</RadioGroup>;
}
type Props={data:TownState;busy:boolean;onAction:(action:string,args:Record<string,unknown>)=>void;onLook:(x:number,z:number)=>void};
export default function CivicPanel({data,busy,onAction,onLook}:Props){
 const c=data.civic,mayor=data.election.mayor,isMayor=mayor?.id===data.resident.id,finished=c.projects.filter(p=>p.completed).length,level=townLevel(finished),featured=projectById(c.featured),progress=c.projects.find(p=>p.id===c.featured),funded=progress?.funded??0,remaining=featured?featured.cost-funded:0;
 const [tax,setTax]=useState(c.tax),[next,setNext]=useState('');useEffect(()=>setTax(c.tax),[c.tax]);
 const decide=(action:string,args:Record<string,unknown>)=>onAction(action,{term:c.term,...args});
 return <section className="civic-panel">
  <div className="town-level"><Landmark size={24}/><div><span className="eyebrow">{finished} / 12 upgrades</span><h3>{level.name}</h3><p>{level.bonus?`Every job earns ${level.bonus} extra ${level.bonus===1?'coin':'coins'} before tax. `:''}{level.next?`${level.next} more upgrades unlock +1 coin per work action for everyone.`:'All town milestones achieved.'}</p></div></div>
  <div className="featured-project"><div className="eyebrow"><Flag size={13}/> Featured town project</div>{featured?<><h3>{featured.name}</h3><p>{featured.description}</p><div className="progress-label"><span>{progress?.completed?'Open for everyone':`${funded.toLocaleString()} / ${featured.cost.toLocaleString()} coins funded`}</span><strong>{Math.round(funded/featured.cost*100)}%</strong></div><Progress className="progress" value={funded/featured.cost*100} aria-label={`${featured.name} funding`}/><p className="project-benefit">+{featured.prosperity} town prosperity · Permanent shared upgrade</p>{progress?.completed?<p className="promise-delivered"><Check size={16}/>Delivered under Mayor {progress.mayorName??mayor?.name??'your town'}</p>:isMayor?<div className="button-row"><button className="primary-button" disabled={busy||data.town.treasury<Math.min(100,remaining)} onClick={()=>decide('fund-project',{project:featured.id,funded,amount:Math.min(100,remaining)})}>Fund {Math.min(100,remaining)} coins</button><button className="secondary-button" disabled={busy||data.town.treasury<remaining} onClick={()=>decide('fund-project',{project:featured.id,funded,amount:remaining})}>Finish · {remaining.toLocaleString()} coins</button></div>:<p className="note">Mayor {mayor?.name} can use town funds to complete this project.</p>}<button className="secondary-button full" onClick={()=>onLook(featured.x,featured.z)}><MapPin size={16}/>{progress?.completed?'See the finished upgrade':'View the project site'}</button></>:<><h3>{mayor?'Choose our next chapter':'Our next chapter starts with a vote'}</h3><p>{mayor?'The mayor can choose the next featured upgrade below.':'Elect a mayor with a project you believe in. Their campaign promise will appear here.'}</p></>}</div>
  <div className="town-budget"><div><span className="eyebrow">Available town funds</span><strong><Coins size={17}/>{data.town.treasury.toLocaleString()} coins</strong></div><button className="secondary-button" disabled={busy||data.resident.coins<25} onClick={()=>onAction('support-project',{})}>Contribute 25 coins</button></div>
  <p className="note">Work taxes and voluntary donations fill this fund. Only the mayor can allocate it. Funded progress stays with the town across elections, and completed upgrades remain forever.</p>
  <details className="civic-section"><summary>Work taxes · {TAX_POLICIES[c.tax].name}</summary><p>Tax is taken from each completed work action. Workers always keep at least 1 coin. Your campaign’s tax policy takes effect when you win; later changes appear in the public history.</p><TaxPicker value={tax} onChange={setTax} disabled={!isMayor||busy}/>{isMayor&&<button className="primary-button full" disabled={busy||tax===c.tax} onClick={()=>decide('set-tax',{tax,previousTax:c.tax})}>Apply tax policy</button>}</details>
  <details className="civic-section"><summary>Town upgrade collection · {finished} / 12 complete</summary><p>{isMayor?'Deliver your featured project first, then choose another.':'Explore the permanent improvements your town can build.'}</p><ProjectPicker value={next} onChange={setNext} civic={c} disabled={!isMayor||busy||!!featured&&!progress?.completed}/>{isMayor&&<button className="primary-button full" disabled={busy||!next||!!featured&&!progress?.completed} onClick={()=>decide('feature-project',{project:next})}>Feature this project</button>}</details>
  <details className="civic-section"><summary>Public decisions &amp; spending</summary>{c.history.length?c.history.map(h=><div className="civic-record" key={h.id}><strong>{h.name}</strong><p>{h.kind==='farm-opened'?`helped complete the Town Farm fund with ${h.amount} coins. The west road is now open.`:h.kind==='farm-budget'||h.kind==='farm-donation'?`contributed ${h.amount} ${h.kind==='farm-budget'?'town':'personal'} coins to the Town Farm.`:h.kind==='planning'?`proposed ${h.project} for a resident vote.`:h.kind==='plan-funded'||h.kind==='plan-completed'?`allocated ${h.amount} coins to ${h.project}${h.kind==='plan-completed'?' and completed it':''}.`:h.kind==='elected'?`was elected, promising ${projectById(h.project)?.name??'town stewardship'} and ${TAX_POLICIES[h.amount]?.name??'Balanced'} taxes.`:h.kind==='tax'?`set work taxes to ${TAX_POLICIES[h.amount]?.name} (${h.amount} coins).`:h.kind==='donation'?`contributed ${h.amount} coins to the town fund.`:h.kind==='featured'?`featured ${projectById(h.project)?.name}.`:`allocated ${h.amount} town coins to ${projectById(h.project)?.name}${h.kind==='completed'?' and completed it':''}.`}</p><small>{new Intl.DateTimeFormat('en',{month:'short',day:'numeric',timeZone:'UTC'}).format(h.created)}</small></div>):<p>Town decisions will appear here as they happen.</p>}</details>
 </section>;
}
