export type CommunityBuilding = {
  id: string;
  name: string;
  cost: number;
  description: string;
  category: 'Food' | 'Social' | 'Creative' | 'Services' | 'Nature';
  style: string;
  color: string;
  roof: string;
  job: string;
  work: string;
  activity: string;
  outcome: string;
  future: string;
  liveService?: 'pets';
};

// Stable IDs retain buildings already purchased by existing towns.
export const COMMUNITY_BUILDINGS: CommunityBuilding[] = [
  {
    id: 'pets',
    name: 'Paws & Porches Pet Store',
    cost: 1800,
    category: 'Services',
    style: 'pets',
    color: '#ead5d8',
    roof: '#a57d97',
    description: 'A neighborhood home for animal lovers.',
    job: 'Animal care assistant',
    work: 'Refill bowls, groom coats, and prepare adoption baskets.',
    activity: 'Choose a cat or dog to join your household.',
    outcome: 'Purchased pets appear on residents’ porches and in their yards.',
    future: 'Pet daycare or an animal rescue center.',
    liveService: 'pets',
  },
  {
    id: 'garden',
    name: 'Civic garden',
    cost: 600,
    category: 'Nature',
    style: 'garden',
    color: '#b1c984',
    roof: '#719088',
    description: 'A quiet planted courtyard for the square.',
    job: 'Nursery assistant',
    work: 'Propagate seedlings, pot flowers, and tend shared planters.',
    activity: 'Host seed swaps and arrange a seasonal flower display.',
    outcome: 'A shared flower display changes with residents’ contributions.',
    future: 'Native plant nursery or a conservatory.',
  },
  {
    id: 'food',
    name: 'Neighborhood food hall',
    cost: 1200,
    category: 'Food',
    style: 'market',
    color: '#edd7ac',
    roof: '#bd8267',
    description: 'A covered meeting place for growers and cooks.',
    job: 'Market stall assistant',
    work: 'Arrange produce, fill pantry orders, and clear tables.',
    activity: 'Bring ingredients for a communal dinner.',
    outcome: 'A long table fills with dishes prepared by neighbors.',
    future: 'Farmers’ exchange or a culinary school.',
  },
  {
    id: 'craft',
    name: 'Community craft studio',
    cost: 1400,
    category: 'Creative',
    style: 'workshop',
    color: '#dac6aa',
    roof: '#719088',
    description: 'Shared workbenches and room to make something.',
    job: 'Workshop apprentice',
    work: 'Sort materials, sand furniture, and assemble repairs.',
    activity: 'Build decorations with neighbors at a shared workbench.',
    outcome: 'Finished furniture can furnish public gathering places.',
    future: 'Furniture cooperative or an inventors’ workshop.',
  },
  {
    id: 'bakery',
    name: 'Morningbell Bakery',
    cost: 1600,
    category: 'Food',
    style: 'market',
    color: '#f0d5b7',
    roof: '#bb7866',
    description: 'Warm windows and a place to meet before work.',
    job: 'Baker’s apprentice',
    work: 'Mix dough, shape loaves, and load the oven.',
    activity: 'Prepare a neighborhood breakfast together.',
    outcome: 'The serving counter fills with fresh bread for the town.',
    future: 'Neighborhood café bakery or a celebration cake shop.',
  },
  {
    id: 'music',
    name: 'Clover Music Club',
    cost: 2100,
    category: 'Social',
    style: 'theater',
    color: '#e3cfdd',
    roof: '#90739c',
    description: 'A small stage with a big welcome.',
    job: 'Stagehand',
    work: 'Arrange chairs, tune the stage, and set up lights.',
    activity: 'Rehearse and play short rhythm performances together.',
    outcome: 'Residents build toward a public concert with a decorated stage.',
    future: 'Outdoor concert pavilion or a recording studio.',
  },
  {
    id: 'recreation',
    name: 'Neighborhood Recreation Hall',
    cost: 2200,
    category: 'Social',
    style: 'festival',
    color: '#d6e0cb',
    roof: '#729d91',
    description: 'A cheerful home for friendly competition.',
    job: 'Recreation attendant',
    work: 'Set out equipment, prepare courts, and organize matches.',
    activity: 'Play short table games and take part in team challenges.',
    outcome: 'Community tournament results fill the hall’s noticeboard.',
    future: 'Sports club or an indoor games arcade.',
  },
  {
    id: 'salon',
    name: 'The Little Looking Glass',
    cost: 1700,
    category: 'Services',
    style: 'mall',
    color: '#e5c9d7',
    roof: '#997b92',
    description: 'A social corner for a fresh look.',
    job: 'Salon assistant',
    work: 'Prepare stations, wash towels, and help with styling.',
    activity: 'Style outfits and arrange neighborhood fashion shows.',
    outcome: 'Resident looks appear in a rotating town showcase.',
    future: 'Barbershop and grooming lounge or a fashion atelier.',
  },
  {
    id: 'clinic',
    name: 'Good Neighbor Clinic',
    cost: 2000,
    category: 'Services',
    style: 'campus',
    color: '#d9e4dc',
    roof: '#779ba2',
    description: 'A welcoming place to help neighbors feel cared for.',
    job: 'Clinic assistant',
    work: 'Stock supplies, prepare care packages, and tend the courtyard.',
    activity: 'Assemble welcome and wellbeing kits for neighbors.',
    outcome: 'A community care shelf fills with residents’ contributions.',
    future: 'Wellness garden or a community care center.',
  },
  {
    id: 'fire',
    name: 'Firefly Volunteer Station',
    cost: 2400,
    category: 'Services',
    style: 'workshop',
    color: '#dfbba5',
    roof: '#a65d54',
    description: 'A volunteer clubhouse with a bright red engine bay.',
    job: 'Volunteer station helper',
    work: 'Polish equipment, check supplies, and prepare training courses.',
    activity: 'Run friendly obstacle courses and cooperative rescue drills.',
    outcome: 'The town earns visible preparedness pennants through teamwork.',
    future: 'Rescue training academy or a community response center.',
  },
  {
    id: 'museum',
    name: 'Little Museum of Town Life',
    cost: 2000,
    category: 'Creative',
    style: 'museum',
    color: '#e7dbc0',
    roof: '#7b939c',
    description: 'A place to celebrate what makes this town its own.',
    job: 'Gallery assistant',
    work: 'Clean exhibits, organize donations, and arrange displays.',
    activity: 'Contribute discoveries and curate a shared exhibition.',
    outcome: 'Exhibits visibly reflect the town’s collection and history.',
    future: 'Natural history museum or an arts and heritage gallery.',
  },
  {
    id: 'exchange',
    name: 'Neighbor Exchange',
    cost: 1500,
    category: 'Nature',
    style: 'workshop',
    color: '#d2d9b8',
    roof: '#879366',
    description: 'Give useful things a second life.',
    job: 'Repair and reuse helper',
    work: 'Sort donations, repair worn items, and restock shelves.',
    activity: 'Hold swap meets and work together on repair challenges.',
    outcome: 'A reuse display shows what the town has saved and restored.',
    future: 'Recycling workshop or a community lending library.',
  },
];
export const communityBuilding = (id: string) =>
  COMMUNITY_BUILDINGS.find((b) => b.id === id);
