'use client';
import {useState} from 'react';
import {Armchair,ArrowLeft,Check,Coins,Home,Package,Paintbrush,RotateCw,X,ChevronUp,ChevronDown,ChevronLeft,ChevronRight} from 'lucide-react';
import InteriorScene from './InteriorScene';
import {FURNITURE,FINISHES,floorCount,floorName,floorFinishes,furnitureById,roomSize,starterInterior,fittedFurniture,firstFurnitureSpot,placementIssue,type PlacedFurniture} from './interiors';
import {houseById} from './lifestyle';
import {HOMES,type TownState} from './data';
type Props={data:TownState;busy:boolean;online:boolean;onAction:(action:string,body?:Record<string,unknown>,message?:string)=>Promise<any>;onRefresh:()=>void};
export default function HomeInterior({data,busy,online,onAction,onRefresh}:Props){const r=data.resident,interior=r.interior??starterInterior(),house=houseById(r.house),size=roomSize(house.id);
 const [selectedLevel,setSelectedLevel]=useState(0),level=Math.min(selectedLevel,floorCount(house.id)-1),placed=fittedFurniture(interior,house.id,level),finishes=floorFinishes(interior,level),allPlaced=Array.from({length:floorCount(house.id)},(_,i)=>fittedFurniture(interior,house.id,i)).flat();
 const [editing,setEditing]=useState(false),[tab,setTab]=useState<'furniture'|'finishes'|'stored'>('furniture'),[draft,setDraft]=useState<PlacedFurniture|null>(null),[draftRevision,setDraftRevision]=useState(0),[hint,setHint]=useState(''),[stick,setStick]=useState({x:0,z:0});
 const selected=furnitureById(draft?.id),owned=!!selected&&interior.owned.includes(selected.id),issue=draft?placementIssue(draft,placed,house.id):null,stale=!!draft&&draftRevision!==(r.interiorRevision??0),packed=interior.owned.filter(id=>!allPlaced.some(p=>p.id===id));
 function choose(id:string){const existing=placed.find(p=>p.id===id),spot=existing??firstFurnitureSpot(id,placed,house.id,level);if(!spot){setHint('There’s no room for this piece yet. Store something to make space.');return;}setDraft(spot);setDraftRevision(r.interiorRevision??0);setHint('Tap the floor to position it, or use the arrows. Rotate to find the right fit.');}
 async function save(action:string,body:Record<string,unknown>){const v=await onAction(action,{revision:r.interiorRevision,level,...body},'Your home is saved.');if(v){setDraft(null);setHint('Saved. Make yourself at home.');}else{onRefresh();setDraft(null);}}
 function changeFloor(next:number){if(busy||next<0||next>=floorCount(house.id))return;setSelectedLevel(next);setDraft(null);setStick({x:0,z:0});setHint('');}
 const nudge=(x:number,z:number)=>setDraft(p=>p?{...p,x:p.x+x,z:p.z+z}:p);
 return <main className={`home-interior ${editing?'decorating':''}`}>
 <header className="interior-header"><div><span className="eyebrow"><Home size={14}/> {HOMES[r.home!].name}</span><h1>{r.name}’s {house.name}</h1></div><div className="interior-header-actions"><span className="coin-chip"><Coins size={18}/>{r.coins.toLocaleString()}</span><button className="secondary-button" disabled={busy||!online} onClick={()=>onAction('home-exit')}><ArrowLeft size={17}/>Outside</button></div></header>
 <div className="interior-layout"><section className="interior-room"><InteriorScene level={level} onFloorChange={changeFloor} resident={r} interior={{...interior,...finishes}} placed={placed} editing={editing} draft={draft} stick={stick} onSelect={choose} onPlace={(x,z)=>setDraft(p=>p?{...p,x,z}:p)} onExit={()=>{if(!busy&&online)void onAction('home-exit')}}/>
 <div className="interior-room-caption"><span>{floorName(level)}{editing?' · Decorating':` · ${size.width} × ${size.depth}`}</span><small>{editing?'Half-step grid · green fits, red needs room':floorCount(house.id)>1?'Click the stairs to change floors · WASD to walk':'Click to walk · WASD / arrows · doorway to leave'}</small></div>
 {floorCount(house.id)>1&&<nav className="interior-floor-switch" aria-label="House floors">{Array.from({length:floorCount(house.id)},(_,i)=><button key={i} disabled={busy} aria-current={level===i?'page':undefined} onClick={()=>changeFloor(i)}>{floorName(i)}</button>)}</nav>}
 {!editing&&<div className="interior-welcome"><button className="primary-button" onClick={()=>{setEditing(true);setStick({x:0,z:0})}}><Armchair size={18}/>Make it yours</button></div>}
 {!editing&&<div className="interior-move" aria-label="Move inside your home">{([{label:'Move left',x:-1,z:0,Icon:ChevronLeft},{label:'Move forward',x:0,z:-1,Icon:ChevronUp},{label:'Move backward',x:0,z:1,Icon:ChevronDown},{label:'Move right',x:1,z:0,Icon:ChevronRight}]).map(({label,x,z,Icon})=><button key={label} aria-label={label} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);setStick({x,z})}} onPointerUp={()=>setStick({x:0,z:0})} onPointerCancel={()=>setStick({x:0,z:0})} onLostPointerCapture={()=>setStick({x:0,z:0})}><Icon size={23}/></button>)}</div>}
 </section>
 {editing&&<aside className="interior-editor" aria-label="Decorate your home"><div className="interior-editor-heading"><h2>A place for your things</h2><button className="icon-button" aria-label="Finish decorating" onClick={()=>{setEditing(false);setDraft(null)}}><X size={19}/></button></div>
 <div className="lifestyle-tabs"><button aria-pressed={tab==='furniture'} onClick={()=>setTab('furniture')}><Armchair size={16}/>Furniture</button><button aria-pressed={tab==='stored'} onClick={()=>setTab('stored')}><Package size={16}/>Stored ({packed.length})</button><button aria-pressed={tab==='finishes'} onClick={()=>setTab('finishes')}><Paintbrush size={16}/>Finishes</button></div>
 {draft&&selected?<div className="interior-placement"><strong>{selected.name}</strong><p>{stale?'Your room changed on another screen. Select this piece again.':issue??hint}</p><div className="furniture-nudge"><button aria-label="Move furniture left" onClick={()=>nudge(-.5,0)}><ChevronLeft/></button><button aria-label="Move furniture toward back wall" onClick={()=>nudge(0,-.5)}><ChevronUp/></button><button aria-label="Move furniture toward door" onClick={()=>nudge(0,.5)}><ChevronDown/></button><button aria-label="Move furniture right" onClick={()=>nudge(.5,0)}><ChevronRight/></button><button aria-label="Rotate furniture 90 degrees" onClick={()=>setDraft(p=>p?{...p,rotation:(p.rotation+90)%360}:p)}><RotateCw size={20}/></button></div>
 <button className="primary-button full" disabled={busy||!online||!!issue||stale||(!owned&&r.coins<selected.price)} onClick={()=>save('home-place',{item:draft.id,x:draft.x,z:draft.z,rotation:draft.rotation})}><Check size={17}/>{owned?'Save placement':`Buy & place · ${selected.price} coins`}</button><div className="button-row"><button className="secondary-button" onClick={()=>setDraft(null)}>Cancel</button>{owned&&placed.some(p=>p.id===draft.id)&&<button className="secondary-button" disabled={busy||!online||stale} onClick={()=>save('home-store',{item:draft.id})}><Package size={16}/>Store</button>}</div></div>:<>
 <p className="interior-editor-note">{tab==='finishes'?'A new mood, whenever you like. Wall and floor finishes are free.':tab==='stored'?'Furniture you own, ready for a new spot. Packed pieces stay yours when your house changes.':'Five starter pieces are yours. Buy new pieces with your town earnings, or tap existing furniture to rearrange it.'}</p>
 {tab==='finishes'?<div className="interior-finishes">{(['wall','floor'] as const).map(kind=><section key={kind}><h3>{kind==='wall'?'Walls':'Floors'}</h3><div>{FINISHES[kind].map(f=><button className={finishes[kind]===f.id?'selected':''} key={f.id} disabled={busy||!online} aria-pressed={finishes[kind]===f.id} onClick={()=>save('home-finish',{wall:finishes.wall,floor:finishes.floor,[kind]:f.id})}><i style={{background:f.color||house.wall}}/><span>{f.name}</span></button>)}</div></section>)}</div>:<div className="furniture-catalog">{FURNITURE.filter(f=>tab!=='stored'||packed.includes(f.id)).map(f=><button key={f.id} onClick={()=>choose(f.id)}><div className={`furniture-swatch kind-${f.kind}`} style={{'--furniture-color':f.color} as React.CSSProperties}><Armchair size={26}/><span>{f.w} × {f.d}</span></div><strong>{f.name}</strong><small>{interior.owned.includes(f.id)?allPlaced.some(p=>p.id===f.id)?`${floorName(allPlaced.find(p=>p.id===f.id)?.level??0)} · move`:'Owned · place':`${f.price} coins`}</small></button>)}{tab==='stored'&&!packed.length&&<p>Everything you own has a place in your room.</p>}</div>}
 <p className="interior-feedback" role="status">{hint}</p></>}
 </aside>}
 </div>
 </main>;
}
