'use client';
import {useEffect,useRef,useState} from 'react';
import {Armchair,ArrowLeft,Check,Coins,Home,Package,Paintbrush,RotateCw,X,ChevronUp,ChevronDown,ChevronLeft,ChevronRight} from 'lucide-react';
import InteriorScene from './InteriorScene';
import {FURNITURE,FINISHES,floorCount,floorName,floorFinishes,furnitureById,roomSize,starterInterior,fittedFurniture,firstFurnitureSpot,placementIssue,type PlacedFurniture} from './interiors';
import {houseById} from './lifestyle';
import {HOMES,type TownState} from './data';
type Props={controlling:boolean;onControl:()=>Promise<boolean>;onPosition:(p:{x:number;z:number;level:number})=>void;data:TownState;busy:boolean;online:boolean;onAction:(action:string,body?:Record<string,unknown>,message?:string)=>Promise<any>;onRefresh:()=>void};
export default function HomeInterior({data,busy,online,onAction,onRefresh,onPosition,controlling,onControl}:Props){const visitor=!!data.resident.visitHost,room=data.room,r=room?{...data.resident,house:room.house,home:room.home,interior:room.interior}:data.resident,interior=r.interior??starterInterior(),house=houseById(r.house),size=roomSize(house.id);
 const [selectedLevel,setSelectedLevel]=useState(r.indoorLevel??0),level=Math.min(selectedLevel,floorCount(house.id)-1),placed=fittedFurniture(interior,house.id,level),finishes=floorFinishes(interior,level),allPlaced=Array.from({length:floorCount(house.id)},(_,i)=>fittedFurniture(interior,house.id,i)).flat();
 const [editing,setEditing]=useState(false),[tab,setTab]=useState<'furniture'|'finishes'|'stored'>('furniture'),[draft,setDraft]=useState<PlacedFurniture|null>(null),[draftRevision,setDraftRevision]=useState(0),[hint,setHint]=useState(''),[stick,setStick]=useState({x:0,z:0});
 const saving=useRef(false),revision=useRef(0);
 useEffect(()=>{if(!controlling){setSelectedLevel(data.resident.indoorLevel??0);setStick({x:0,z:0});}},[controlling,data.resident.indoorLevel]);
 const selected=furnitureById(draft?.id),owned=!!selected&&interior.owned.includes(selected.id),issue=draft?placementIssue(draft,placed,house.id):null,stale=!!draft&&draftRevision!==(r.interiorRevision??0),packed=interior.owned.filter(id=>!allPlaced.some(p=>p.id===id));
 function choose(id:string){if(visitor||busy||!online||saving.current)return null;const existing=placed.find(p=>p.id===id),spot=existing??firstFurnitureSpot(id,placed,house.id,level)??{id,x:0,z:0,rotation:0,level};setDraft(spot);revision.current=r.interiorRevision??0;setDraftRevision(revision.current);setHint('Move to preview · click or release to place · R to rotate · Esc to cancel.');return spot;}
 async function save(action:string,body:Record<string,unknown>){if(visitor||busy||!online||saving.current)return;saving.current=true;try{const v=await onAction(action,{revision:r.interiorRevision,level,...body},'Your home is saved.');if(v){setDraft(null);setHint('Saved. Choose another piece or drag furniture to rearrange.');}else{onRefresh();setDraft(null);}}finally{saving.current=false;}}
 function commit(piece:PlacedFurniture){if(visitor||busy||!online||saving.current)return;if(revision.current!==(r.interiorRevision??0)){setHint('Your room changed on another screen. Select this piece again.');return;}const problem=placementIssue(piece,placed,house.id),f=furnitureById(piece.id);if(problem){setHint(problem);return;}if(!f)return;if(!interior.owned.includes(piece.id)&&r.coins<f.price){setHint(`You need ${f.price} coins for this piece.`);return;}void save('home-place',{item:piece.id,x:piece.x,z:piece.z,rotation:piece.rotation});}
 const rotate=()=>{if(!busy&&!saving.current)setDraft(p=>p?{...p,rotation:(p.rotation+90)%360}:p);};
 async function changeFloor(next:number){if(busy||saving.current||next<0||next>=floorCount(house.id))return;if(!await onControl())return;setSelectedLevel(next);setDraft(null);setStick({x:0,z:0});setHint('');}
 const nudge=(x:number,z:number)=>setDraft(p=>p?{...p,x:p.x+x,z:p.z+z}:p);
 return <main className={`home-interior ${editing?'decorating':''}`}>
 <header className="interior-header"><div><span className="eyebrow"><Home size={14}/> {HOMES[r.home!].name}</span><h1>{room?.name??r.name}’s {house.name}{visitor?' · Visiting':''}</h1></div><div className="interior-header-actions"><span className="coin-chip"><Coins size={18}/>{r.coins.toLocaleString()}</span><button className="secondary-button" disabled={busy||!online} onClick={()=>onAction('home-exit')}><ArrowLeft size={17}/>Outside</button></div></header>
 <div className="interior-layout"><section className="interior-room"><InteriorScene controlling={controlling} onControl={onControl} peers={room?.peers??[]} onPosition={onPosition} level={level} onFloorChange={changeFloor} resident={r} interior={{...interior,...finishes}} placed={placed} editing={editing} draft={draft} stick={stick} locked={busy||!online||stale} onSelect={choose} onPreview={piece=>setDraft(previous=>previous&&previous.id===piece.id&&previous.x===piece.x&&previous.z===piece.z&&previous.rotation===piece.rotation&&previous.level===piece.level?previous:piece)} onCommit={commit} onRotate={rotate} onCancel={()=>{if(!saving.current)setDraft(null)}} onExit={()=>{if(!busy&&online)void onAction('home-exit')}}/>
 <div className="interior-room-caption"><span>{floorName(level)}{editing?' · Decorating':` · ${size.width} × ${size.depth}`}</span><small>{editing?'Move to preview · green fits · click to place':floorCount(house.id)>1?'Click the stairs to change floors · WASD to walk':'Click to walk · WASD / arrows · doorway to leave'}</small>{(room?.peers.length??0)>1&&<small>Here: {room!.peers.filter(p=>p.id!==r.id).map(p=>`${p.name}${p.level!==level?` (${floorName(p.level)})`:""}`).join(", ")}</small>}</div>
 {floorCount(house.id)>1&&<nav className="interior-floor-switch" aria-label="House floors">{Array.from({length:floorCount(house.id)},(_,i)=><button key={i} disabled={busy} aria-current={level===i?'page':undefined} onClick={()=>changeFloor(i)}>{floorName(i)}</button>)}</nav>}
 {!editing&&!visitor&&<div className="interior-welcome"><button className="primary-button" onClick={()=>{setEditing(true);setStick({x:0,z:0})}}><Armchair size={18}/>Make it yours</button></div>}
 {!editing&&<div className="interior-move" aria-label="Move inside your home">{([{label:'Move left',x:-1,z:0,Icon:ChevronLeft},{label:'Move forward',x:0,z:-1,Icon:ChevronUp},{label:'Move backward',x:0,z:1,Icon:ChevronDown},{label:'Move right',x:1,z:0,Icon:ChevronRight}]).map(({label,x,z,Icon})=><button key={label} aria-label={label} onPointerDown={e=>{void onControl();e.currentTarget.setPointerCapture(e.pointerId);setStick({x,z})}} onPointerUp={()=>setStick({x:0,z:0})} onPointerCancel={()=>setStick({x:0,z:0})} onLostPointerCapture={()=>setStick({x:0,z:0})}><Icon size={23}/></button>)}</div>}
 </section>
 {editing&&!visitor&&<aside className="interior-editor" aria-label="Decorate your home"><div className="interior-editor-heading"><h2>A place for your things</h2><button className="icon-button" disabled={busy} aria-label="Finish decorating" onClick={()=>{setEditing(false);setDraft(null)}}><X size={19}/></button></div>
 <div className="lifestyle-tabs"><button aria-pressed={tab==='furniture'} onClick={()=>setTab('furniture')}><Armchair size={16}/>Furniture</button><button aria-pressed={tab==='stored'} onClick={()=>setTab('stored')}><Package size={16}/>Stored ({packed.length})</button><button aria-pressed={tab==='finishes'} onClick={()=>setTab('finishes')}><Paintbrush size={16}/>Finishes</button></div>
 {draft&&selected?<div className="interior-placement"><strong>{selected.name}</strong><span className="interior-placement-cost">{owned?'Owned · moving is free':`${selected.price} coins · charged when placed`}</span><p role="status">{stale?'Your room changed on another screen. Select this piece again.':issue??hint}</p><fieldset className="furniture-nudge" disabled={busy||!online||stale}><button aria-label="Move furniture left" onClick={()=>nudge(-.5,0)}><ChevronLeft/></button><button aria-label="Move furniture toward back wall" onClick={()=>nudge(0,-.5)}><ChevronUp/></button><button aria-label="Move furniture toward door" onClick={()=>nudge(0,.5)}><ChevronDown/></button><button aria-label="Move furniture right" onClick={()=>nudge(.5,0)}><ChevronRight/></button><button aria-label="Rotate furniture 90 degrees" onClick={rotate}><RotateCw size={20}/></button></fieldset>
 <button className="primary-button full" disabled={busy||!online||!!issue||stale||(!owned&&r.coins<selected.price)} onClick={()=>commit(draft)}><Check size={17}/>{owned?'Save placement':`Buy & place · ${selected.price} coins`}</button><div className="button-row"><button className="secondary-button" disabled={busy} onClick={()=>setDraft(null)}>Cancel</button>{owned&&placed.some(p=>p.id===draft.id)&&<button className="secondary-button" disabled={busy||!online||stale} onClick={()=>save('home-store',{item:draft.id})}><Package size={16}/>Store</button>}</div></div>:<>
 <p className="interior-editor-note">{tab==='finishes'?'A new mood, whenever you like. Wall and floor finishes are free.':tab==='stored'?'Furniture you own, ready for a new spot. Packed pieces stay yours when your house changes.':'Five starter pieces are yours. Buy new pieces with your town earnings, or drag existing furniture to rearrange it. On touch screens, drag to preview and release to place.'}</p>
 {tab==='finishes'?<div className="interior-finishes">{(['wall','floor'] as const).map(kind=><section key={kind}><h3>{kind==='wall'?'Walls':'Floors'}</h3><div>{FINISHES[kind].map(f=><button className={finishes[kind]===f.id?'selected':''} key={f.id} disabled={busy||!online} aria-pressed={finishes[kind]===f.id} onClick={()=>save('home-finish',{wall:finishes.wall,floor:finishes.floor,[kind]:f.id})}><i style={{background:f.color||house.wall}}/><span>{f.name}</span></button>)}</div></section>)}</div>:<div className="furniture-catalog">{FURNITURE.filter(f=>tab!=='stored'||packed.includes(f.id)).map(f=><button key={f.id} disabled={busy||!online} onClick={()=>choose(f.id)}><div className={`furniture-swatch kind-${f.kind}`} style={{'--furniture-color':f.color} as React.CSSProperties}><Armchair size={26}/><span>{f.w} × {f.d}</span></div><strong>{f.name}</strong><small>{interior.owned.includes(f.id)?allPlaced.some(p=>p.id===f.id)?`${floorName(allPlaced.find(p=>p.id===f.id)?.level??0)} · move`:'Owned · place':`${f.price} coins`}</small></button>)}{tab==='stored'&&!packed.length&&<p>Everything you own has a place in your room.</p>}</div>}
 <p className="interior-feedback" role="status">{hint}</p></>}
 </aside>}
 </div>
 </main>;
}
