'use client';
import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {houseById} from './lifestyle';
import {furnitureById,furnitureRect,roomSize,floorCount,stairwell,FINISHES,placementIssue,type Interior,type PlacedFurniture} from './interiors';
import {interiorKit,furnitureModel,staircaseModel,disposeGeometry} from './interiorModels';
import {dressAvatar} from './wardrobeScenery';
import {findPath} from './pathfinding';
import type {Resident} from './data';
type Props={level:number;onFloorChange:(level:number)=>void;resident:Resident;interior:Interior;placed:PlacedFurniture[];editing:boolean;draft:PlacedFurniture|null;stick:{x:number;z:number};onSelect:(id:string)=>void;onPlace:(x:number,z:number)=>void;onExit:()=>void};
export default function InteriorScene(props:Props){const host=useRef<HTMLDivElement>(null),live=useRef(props);live.current=props;const [error,setError]=useState('');
 useEffect(()=>{const el=host.current;if(!el)return;const p=live.current,house=houseById(p.resident.house),size=roomSize(house.id),kit=interiorKit(),{box,ball,cylinder}=kit;
 let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({antialias:true});}catch{setError('The room could not start on this device. You can still return outside.');return;}
 renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;el.appendChild(renderer.domElement);
 const scene=new THREE.Scene();scene.background=new THREE.Color('#bccbc2');scene.add(new THREE.HemisphereLight('#fff4d8','#789487',2));const sun=new THREE.DirectionalLight('#fff0d0',2.4);sun.position.set(-6,12,6);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-14;sun.shadow.camera.right=14;sun.shadow.camera.top=14;sun.shadow.camera.bottom=-14;scene.add(sun);
 const camera=new THREE.OrthographicCamera(-10,10,10,-10,.1,100);camera.position.set(11,14,17);camera.lookAt(0,0,0);
 const wall=FINISHES.wall.find(f=>f.id===p.interior.wall)?.color||house.wall,floor=FINISHES.floor.find(f=>f.id===p.interior.floor)?.color||'#be956b';
 box(size.width+.3,.3,size.depth+.3,'#795c48',0,-.18,0,scene);
 for(let x=-size.width/2+.25;x<size.width/2;x+=.5)box(.48,.07,size.depth,floor,x,.005,0,scene);
 box(size.width,.09,.14,house.trim,0,.04,size.depth/2,scene);
 // A dollhouse cutaway exposes the living space while retaining the home's exterior palette.
 box(size.width,.15,.12,house.trim,0,.11,-size.depth/2,scene);box(size.width,2.9,.18,wall,0,1.45,-size.depth/2,scene);box(.18,2.9,size.depth,wall,-size.width/2,1.45,0,scene);
 for(const y of [.15,2.86]){box(size.width,.12,.23,house.trim,0,y,-size.depth/2,scene);box(.23,.12,size.depth,house.trim,-size.width/2,y,0,scene);}
 for(const x of [-size.width*.25,size.width*.25]){box(1.6,1.35,.08,house.trim,x,1.8,-size.depth/2+.14,scene);box(1.4,1.15,.08,'#a8d3d3',x,1.8,-size.depth/2+.2,scene);box(.065,1.25,.09,house.trim,x,1.8,-size.depth/2+.26,scene);box(1.5,.06,.09,house.trim,x,1.8,-size.depth/2+.26,scene);box(1.8,.12,.38,house.trim,x,1.1,-size.depth/2+.22,scene);for(const dx of [-.87,.87])box(.25,1.55,.17,house.roof,x+dx,1.7,-size.depth/2+.2,scene);}
 const threshold=box(1.8,.08,.65,'#e8ca8d',0,.07,size.depth/2-.3,scene);threshold.userData.exit=true;threshold.visible=p.level===0;
 const stairs=floorCount(house.id)>1?staircaseModel(kit,p.level,floorCount(house.id)):null,well=stairwell(house.id);if(stairs){stairs.position.set(well.x,0,well.z);scene.add(stairs);}
 const roomRoot=new THREE.Group(),ghost=new THREE.Group();scene.add(roomRoot,ghost);const grid=new THREE.GridHelper(Math.max(size.width,size.depth),Math.max(size.width,size.depth)*2,'#597d67','#597d67');grid.position.y=.09;(grid.material as THREE.Material).transparent=true;(grid.material as THREE.Material).opacity=.17;scene.add(grid);
 const avatar=new THREE.Group();scene.add(avatar);avatar.position.set(p.level>0?well.x:0,0,p.level>0?well.z+1.6:size.depth/2-.9);const legs=[box(.18,.4,.23,'#4e5b62',-.16,.32,0,avatar),box(.18,.4,.23,'#4e5b62',.16,.32,0,avatar)];box(.23,.12,.34,'#775f47',-.16,.09,.05,avatar);box(.23,.12,.34,'#775f47',.16,.09,.05,avatar);const shirt=cylinder(.3,.48,p.resident.color,0,.77,0,avatar,.27),arms=[box(.16,.46,.2,p.resident.color,-.35,.77,0,avatar),box(.16,.46,.2,p.resident.color,.35,.77,0,avatar)];ball(.29,'#e5b994',0,1.31,0,avatar);const hair=ball(.31,'#75553c',0,1.44,-.035,avatar);hair.scale.y=.65;for(const x of [-.105,.105])box(.04,.055,.025,'#35443a',x,1.33,.27,avatar);avatar.userData={legs,arms,shirt,rider:[]};dressAvatar(avatar,p.resident,kit.mat);avatar.userData.wardrobe.position.y=-.11;
 const resize=()=>{const w=el.clientWidth,h=el.clientHeight,aspect=w/Math.max(h,1),span=Math.max(size.depth+7,(size.width+7)/aspect);camera.left=-span*aspect/2;camera.right=span*aspect/2;camera.top=span/2;camera.bottom=-span/2;camera.updateProjectionMatrix();renderer.setSize(w,h);};const observer=new ResizeObserver(resize);observer.observe(el);resize();
 const blocked=(x:number,z:number)=>{const state=live.current;if(stairs&&Math.abs(x-well.x)<.95&&Math.abs(z-well.z)<1.25)return true;if(Math.abs(x)>size.width/2-.22||Math.abs(z)>size.depth/2-.22)return true;return state.placed.some(p=>{if(furnitureById(p.id)?.kind==='rug')return false;const r=furnitureRect(p);return Math.abs(x-r.x)<r.w/2+.16&&Math.abs(z-r.z)<r.d/2+.16;});};
 const keys=new Set<string>();let path:{x:number;z:number}[]=[];const keyDown=(e:KeyboardEvent)=>{if((e.target as HTMLElement)?.closest('input,select,textarea,[role=dialog]'))return;const k=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright'].includes(k)){e.preventDefault();keys.add(k);}if(k==='e'&&!live.current.editing){if(stairs&&Math.hypot(avatar.position.x-well.x,avatar.position.z-(well.z+1.5))<1.8){const next=p.level>0&&(p.level===floorCount(house.id)-1||avatar.position.x<well.x)?p.level-1:p.level+1;live.current.onFloorChange(next);}else if(p.level===0&&avatar.position.z>size.depth/2-1.8&&Math.abs(avatar.position.x)<1.2)live.current.onExit();}};const keyUp=(e:KeyboardEvent)=>keys.delete(e.key.toLowerCase()),blur=()=>keys.clear();window.addEventListener('keydown',keyDown);window.addEventListener('keyup',keyUp);window.addEventListener('blur',blur);
 const ray=new THREE.Raycaster(),plane=new THREE.Plane(new THREE.Vector3(0,1,0),0);let down:{x:number;y:number}|null=null;
 const pointerDown=(e:PointerEvent)=>{down={x:e.clientX,y:e.clientY};};
 const pointerUp=(e:PointerEvent)=>{if(!down||Math.hypot(e.clientX-down.x,e.clientY-down.y)>8){down=null;return;}down=null;const rect=el.getBoundingClientRect();ray.setFromCamera(new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),camera);const s=live.current;
 if(s.editing&&!s.draft){const hit=ray.intersectObjects(roomRoot.children,true)[0];let o:THREE.Object3D|null=hit?.object??null;while(o&&!o.userData.furniture)o=o.parent;if(o?.userData.furniture){s.onSelect(o.userData.furniture);return;}}
 if(!s.editing&&stairs){const hit=ray.intersectObject(stairs,true)[0];let o:THREE.Object3D|null=hit?.object??null;while(o&&o.userData.floorTo===undefined)o=o.parent;if(o?.userData.floorTo!==undefined){s.onFloorChange(o.userData.floorTo);return;}}
 if(!s.editing&&p.level===0&&ray.intersectObject(threshold).length){s.onExit();return;}
 const point=new THREE.Vector3();if(!ray.ray.intersectPlane(plane,point))return;
 if(s.editing&&s.draft){s.onPlace(Math.round(point.x*2)/2,Math.round(point.z*2)/2);return;}
 if(!s.editing){path=findPath(avatar.position,{x:point.x,z:point.z},blocked);}
 };renderer.domElement.addEventListener('pointerdown',pointerDown);renderer.domElement.addEventListener('pointerup',pointerUp);
 let frame=0,last=performance.now(),furnitureKey='',draftKey='';
 const animate=(now:number)=>{frame=requestAnimationFrame(animate);const dt=Math.min((now-last)/1000,.04);last=now;const s=live.current;grid.visible=s.editing;avatar.visible=!s.editing;
 const fk=JSON.stringify(s.placed);if(fk!==furnitureKey){furnitureKey=fk;disposeGeometry(roomRoot);roomRoot.clear();for(const p of s.placed){const f=furnitureById(p.id);if(!f)continue;const model=furnitureModel(f,kit);model.position.set(p.x,0,p.z);model.rotation.y=p.rotation*Math.PI/180;roomRoot.add(model);}path=[];if(blocked(avatar.position.x,avatar.position.z))avatar.position.set(p.level>0?well.x:0,0,p.level>0?well.z+1.6:size.depth/2-.9);}
 const dk=JSON.stringify([s.draft,s.placed]);if(dk!==draftKey){draftKey=dk;disposeGeometry(ghost);ghost.traverse(o=>{if(o instanceof THREE.Mesh&&(o.material as THREE.Material).userData.preview)(o.material as THREE.Material).dispose()});ghost.clear();if(s.draft){const model=furnitureModel(furnitureById(s.draft.id)!,kit),valid=!placementIssue(s.draft,s.placed,s.resident.house);model.traverse(o=>{if(o instanceof THREE.Mesh){const m=(o.material as THREE.MeshStandardMaterial).clone();m.userData.preview=true;m.transparent=true;m.opacity=.7;m.color.lerp(new THREE.Color(valid?'#8ed29a':'#e6806f'),.35);o.material=m;}});model.position.set(s.draft.x,.03,s.draft.z);model.rotation.y=s.draft.rotation*Math.PI/180;ghost.add(model);}}
 for(const g of roomRoot.children)g.visible=g.userData.furniture!==s.draft?.id;
 if(!s.editing){let x=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0)+s.stick.x,z=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0)+s.stick.z;if(Math.hypot(x,z)>.05)path=[];else if(path.length){x=path[0].x-avatar.position.x;z=path[0].z-avatar.position.z;if(Math.hypot(x,z)<.12){path.shift();x=z=0;}}
 const len=Math.hypot(x,z);if(len>.05){const dx=x/len*dt*2.5,dz=z/len*dt*2.5;if(!blocked(avatar.position.x+dx,avatar.position.z))avatar.position.x+=dx;if(!blocked(avatar.position.x,avatar.position.z+dz))avatar.position.z+=dz;avatar.rotation.y=Math.atan2(x,z);}legs.forEach((l,i)=>l.rotation.x=len>.05?Math.sin(now*.015+i*Math.PI)*.4:0);arms.forEach((a,i)=>a.rotation.x=len>.05?Math.sin(now*.015-i*Math.PI)*.3:0);}
 renderer.render(scene,camera);};frame=requestAnimationFrame(animate);
 return()=>{cancelAnimationFrame(frame);observer.disconnect();window.removeEventListener('keydown',keyDown);window.removeEventListener('keyup',keyUp);window.removeEventListener('blur',blur);renderer.domElement.removeEventListener('pointerdown',pointerDown);renderer.domElement.removeEventListener('pointerup',pointerUp);disposeGeometry(scene);ghost.traverse(o=>{if(o instanceof THREE.Mesh)(o.material as THREE.Material).dispose()});grid.geometry.dispose();(grid.material as THREE.Material).dispose();kit.dispose();renderer.dispose();renderer.forceContextLoss();renderer.domElement.remove();};
 },[props.resident.house,props.interior.wall,props.interior.floor,props.level]);
 return <div ref={host} className="interior-canvas" aria-label={props.editing?'Place furniture on your room grid':'Your furnished home. Click the floor or use movement keys to walk.'}>{error&&<p role="alert">{error}</p>}</div>;
}
