'use client';
import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {createTownRenderer,resizeTownRenderer,releaseTownRenderer} from './townRenderer';
import {houseById} from './lifestyle';
import {furnitureById,furnitureRect,roomSize,floorCount,stairwell,FINISHES,placementIssue,type Interior,type PlacedFurniture} from './interiors';
import {interiorKit,furnitureModel,staircaseModel,disposeGeometry} from './interiorModels';
import {dressAvatar} from './wardrobeScenery';
import {findPath} from './pathfinding';
import {animateLifeGesture} from './sharedLifeScenery';
import {furniturePlacement} from './furniturePlacement';
import type {Resident,Peer} from './data';
type Props={controlling:boolean;onControl:()=>Promise<boolean>;peers:(Peer&{level:number})[];onPosition:(p:{x:number;z:number;level:number})=>void;level:number;onFloorChange:(level:number)=>void;resident:Resident;interior:Interior;placed:PlacedFurniture[];editing:boolean;draft:PlacedFurniture|null;stick:{x:number;z:number};locked:boolean;onSelect:(id:string)=>PlacedFurniture|null;onPreview:(piece:PlacedFurniture)=>void;onCommit:(piece:PlacedFurniture)=>void;onRotate:()=>void;onCancel:()=>void;onExit:()=>void};
export default function InteriorScene(props:Props){const host=useRef<HTMLDivElement>(null),live=useRef(props);live.current=props;const [error,setError]=useState('');
 useEffect(()=>{const el=host.current;if(!el)return;const p=live.current,house=houseById(p.resident.house),size=roomSize(house.id),kit=interiorKit(),{box,ball,cylinder}=kit;
 let renderer:THREE.WebGLRenderer;try{({renderer}=createTownRenderer());setError('');}catch{kit.dispose();setError('The room could not start on this device. You can still return outside.');return;}
 renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;el.appendChild(renderer.domElement);
 const scene=new THREE.Scene();scene.background=new THREE.Color('#bccbc2');scene.add(new THREE.HemisphereLight('#fff4d8','#789487',2));const sun=new THREE.DirectionalLight('#fff0d0',2.4);sun.position.set(-6,12,6);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-14;sun.shadow.camera.right=14;sun.shadow.camera.top=14;sun.shadow.camera.bottom=-14;scene.add(sun);
 const camera=new THREE.OrthographicCamera(-10,10,10,-10,.1,100);camera.position.set(11,14,17);camera.lookAt(0,0,0);
 const wall=FINISHES.wall.find(f=>f.id===p.interior.wall)?.color||house.wall,floor=FINISHES.floor.find(f=>f.id===p.interior.floor)?.color||'#be956b';
 box(size.width+.3,.3,size.depth+.3,'#795c48',0,-.18,0,scene);
 for(let x=-size.width/2+.25;x<size.width/2;x+=.5)box(.48,.07,size.depth,floor,x,.005,0,scene);
 box(size.width,.09,.14,house.trim,0,.04,size.depth/2,scene);
 // A dollhouse cutaway exposes the living space while retaining the home's exterior palette.
 box(size.width,.15,.12,house.trim,0,.11,-size.depth/2,scene);box(size.width,2.9,.18,wall,0,1.45,-size.depth/2,scene);box(.18,2.9,size.depth,wall,-size.width/2,1.45,0,scene);
 for(const y of [.15,2.86]){box(size.width,.12,.23,house.trim,0,y,-size.depth/2,scene);box(.23,.12,size.depth,house.trim,-size.width/2,y,0,scene);}
 for(const x of [-size.width*.25,size.width*.25]){box(1.6,1.35,.08,house.trim,x,1.8,-size.depth/2+.14,scene);box(1.4,1.15,.08,'#a8d3d3',x,1.8,-size.depth/2+.2,scene);box(.065,1.25,.09,house.trim,x,1.8,-size.depth/2+.26,scene);box(1.5,.06,.09,house.trim,x,1.8,-size.depth/2+.26,scene);box(1.8,.12,.38,house.trim,x,1.1,-size.depth/2+.22,scene);for(const dx of [-.87,.87])box(.25,1.55,.17,house.roof,x+dx,1.7,-size.depth/2+.2,scene);}
 const threshold=box(1.8,.08,.65,'#e8ca8d',0,.07,size.depth/2-.3,scene);threshold.userData.exit=true;threshold.visible=p.level===0;
 const stairs=floorCount(house.id)>1?staircaseModel(kit,p.level,floorCount(house.id)):null,well=stairwell(house.id);if(stairs){stairs.position.set(well.x,0,well.z);scene.add(stairs);}
 const roomRoot=new THREE.Group(),ghost=new THREE.Group();scene.add(roomRoot,ghost);const gridPoints:THREE.Vector3[]=[];for(let x=-size.width/2;x<=size.width/2;x+=.5)gridPoints.push(new THREE.Vector3(x,.09,-size.depth/2),new THREE.Vector3(x,.09,size.depth/2));for(let z=-size.depth/2;z<=size.depth/2;z+=.5)gridPoints.push(new THREE.Vector3(-size.width/2,.09,z),new THREE.Vector3(size.width/2,.09,z));const grid=new THREE.LineSegments(new THREE.BufferGeometry().setFromPoints(gridPoints),new THREE.LineBasicMaterial({color:'#416749',transparent:true,opacity:.3}));scene.add(grid);
 const footprint=new THREE.Group(),footMaterial=new THREE.MeshBasicMaterial({color:'#62bf83',transparent:true,opacity:.28,depthWrite:false}),edgeMaterial=new THREE.LineBasicMaterial({color:'#62bf83',depthTest:false});const tile=new THREE.Mesh(new THREE.PlaneGeometry(1,1),footMaterial);tile.rotation.x=-Math.PI/2;footprint.add(tile);const edge=new THREE.LineLoop(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(-.5,0,-.5),new THREE.Vector3(.5,0,-.5),new THREE.Vector3(.5,0,.5),new THREE.Vector3(-.5,0,.5)]),edgeMaterial);edge.renderOrder=3;footprint.add(edge);footprint.position.y=.105;scene.add(footprint);

 const makeAvatar=(person:Resident|Peer)=>{const avatar=new THREE.Group();const legs=[box(.18,.4,.23,'#4e5b62',-.16,.32,0,avatar),box(.18,.4,.23,'#4e5b62',.16,.32,0,avatar)];box(.23,.12,.34,'#775f47',-.16,.09,.05,avatar);box(.23,.12,.34,'#775f47',.16,.09,.05,avatar);const shirt=cylinder(.3,.48,person.color,0,.77,0,avatar,.27),arms=[box(.16,.46,.2,person.color,-.35,.77,0,avatar),box(.16,.46,.2,person.color,.35,.77,0,avatar)];ball(.29,'#e5b994',0,1.31,0,avatar);const hair=ball(.31,'#75553c',0,1.44,-.035,avatar);hair.scale.y=.65;for(const x of [-.105,.105])box(.04,.055,.025,'#35443a',x,1.33,.27,avatar);avatar.userData={legs,arms,shirt,rider:[]};dressAvatar(avatar,person,kit.mat);avatar.userData.wardrobe.position.y=-.11;return avatar;};
 const avatar=makeAvatar(p.resident);scene.add(avatar);const spawn=p.level===(p.resident.indoorLevel??0)?{x:p.resident.indoorX??0,z:p.resident.indoorZ??size.depth/2-.9}:p.level>0?{x:well.x,z:well.z+1.6}:{x:0,z:size.depth/2-.9};avatar.position.set(spawn.x,0,spawn.z);const legs=avatar.userData.legs as THREE.Mesh[],arms=avatar.userData.arms as THREE.Mesh[];
 const visitors=new Map<string,{model:THREE.Group;label:HTMLDivElement}>(),reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;

 const resize=()=>{const w=el.clientWidth,h=el.clientHeight,aspect=w/Math.max(h,1),span=Math.max(size.depth+7,(size.width+7)/aspect);camera.left=-span*aspect/2;camera.right=span*aspect/2;camera.top=span/2;camera.bottom=-span/2;camera.updateProjectionMatrix();resizeTownRenderer(renderer,w,h);};const observer=new ResizeObserver(resize);observer.observe(el);resize();
 const blocked=(x:number,z:number)=>{const state=live.current;if(stairs&&Math.abs(x-well.x)<.95&&Math.abs(z-well.z)<1.25)return true;if(Math.abs(x)>size.width/2-.22||Math.abs(z)>size.depth/2-.22)return true;return state.placed.some(p=>{if(furnitureById(p.id)?.kind==='rug')return false;const r=furnitureRect(p);return Math.abs(x-r.x)<r.w/2+.16&&Math.abs(z-r.z)<r.d/2+.16;});};
 const keys=new Set<string>(),held=new Set<string>();let wasControlling=p.controlling,disposed=false;let path:{x:number;z:number}[]=[];const keyDown=(e:KeyboardEvent)=>{if((e.target as HTMLElement)?.closest('input,select,textarea,[role=dialog]'))return;const k=e.key.toLowerCase();if(live.current.editing){if(!live.current.locked&&!e.repeat&&['r','escape'].includes(k)){e.preventDefault();if(k==='r')live.current.onRotate();else{placement.cancel();live.current.onCancel();}}return;}if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright'].includes(k)){e.preventDefault();if(!e.repeat){held.add(k);if(live.current.controlling)keys.add(k);void live.current.onControl().then(ok=>{if(ok&&!disposed&&held.has(k))keys.add(k)});}}if(k==='e'&&!live.current.editing){if(stairs&&Math.hypot(avatar.position.x-well.x,avatar.position.z-(well.z+1.5))<1.8){const next=p.level>0&&(p.level===floorCount(house.id)-1||avatar.position.x<well.x)?p.level-1:p.level+1;live.current.onFloorChange(next);}else if(p.level===0&&avatar.position.z>size.depth/2-1.8&&Math.abs(avatar.position.x)<1.2)live.current.onExit();}};const keyUp=(e:KeyboardEvent)=>{held.delete(e.key.toLowerCase());keys.delete(e.key.toLowerCase())},blur=()=>{held.clear();keys.clear();placement.cancel();};window.addEventListener('keydown',keyDown);window.addEventListener('keyup',keyUp);window.addEventListener('blur',blur);
 const ray=new THREE.Raycaster(),plane=new THREE.Plane(new THREE.Vector3(0,1,0),0);let down:{id:number;x:number;y:number}|null=null;
 const placement=furniturePlacement({state:()=>live.current,select:id=>live.current.onSelect(id),preview:piece=>live.current.onPreview(piece),commit:piece=>live.current.onCommit(piece),cancel:()=>live.current.onCancel()});
 const pointAt=(e:PointerEvent)=>{const rect=renderer.domElement.getBoundingClientRect();ray.setFromCamera(new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),camera);const point=new THREE.Vector3();return ray.ray.intersectPlane(plane,point)?{x:point.x,z:point.z}:null;};
 const pointer=(e:PointerEvent)=>({id:e.pointerId,x:e.clientX,y:e.clientY,point:pointAt(e)});
 const inside=(e:PointerEvent)=>{const r=renderer.domElement.getBoundingClientRect();return e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom;};
 const hitFurniture=()=>{const hit=ray.intersectObjects(roomRoot.children,true)[0];let o:THREE.Object3D|null=hit?.object??null;while(o&&!o.userData.furniture)o=o.parent;return (o?.userData.furniture as string)??null;};
 const pointerDown=(e:PointerEvent)=>{if(!e.isPrimary||e.button!==0||down)return;const s=live.current;if(s.locked&&s.editing)return;e.preventDefault();down={id:e.pointerId,x:e.clientX,y:e.clientY};renderer.domElement.setPointerCapture(e.pointerId);const p=pointer(e);if(s.editing)placement.down(p,hitFurniture());};
 const pointerMove=(e:PointerEvent)=>{if(!e.isPrimary)return;const p=pointer(e);placement.move({...p,point:inside(e)?p.point:null},e.pointerType==='mouse'||e.pointerType==='pen');if(live.current.editing)renderer.domElement.style.cursor=live.current.locked?'wait':placement.dragging?'grabbing':live.current.draft?'crosshair':hitFurniture()?'grab':'default';};
 const pointerUp=(e:PointerEvent)=>{if(!down||down.id!==e.pointerId)return;const start=down;down=null;const p=pointer(e),s=live.current;if(s.editing)placement.up(p,inside(e));if(renderer.domElement.hasPointerCapture(e.pointerId))renderer.domElement.releasePointerCapture(e.pointerId);if(s.editing||!inside(e)||Math.hypot(e.clientX-start.x,e.clientY-start.y)>8)return;
 if(stairs){const hit=ray.intersectObject(stairs,true)[0];let o:THREE.Object3D|null=hit?.object??null;while(o&&o.userData.floorTo===undefined)o=o.parent;if(o?.userData.floorTo!==undefined){s.onFloorChange(o.userData.floorTo);return;}}
 if(s.level===0&&ray.intersectObject(threshold).length){s.onExit();return;}
 if(p.point){const target=p.point;void s.onControl().then(ok=>{if(ok&&!disposed)path=findPath(avatar.position,target,blocked)});}
 };
 const pointerCancel=()=>{down=null;placement.cancel();};
 renderer.domElement.addEventListener('pointerdown',pointerDown);renderer.domElement.addEventListener('pointermove',pointerMove);renderer.domElement.addEventListener('pointerup',pointerUp);renderer.domElement.addEventListener('pointercancel',pointerCancel);renderer.domElement.addEventListener('lostpointercapture',pointerCancel);

 let frame=0,last=performance.now(),furnitureKey='',draftKey='';
 const animate=(now:number)=>{frame=requestAnimationFrame(animate);const dt=Math.min((now-last)/1000,.04);last=now;const s=live.current;grid.visible=s.editing;avatar.visible=!s.editing;
 const fk=JSON.stringify(s.placed);if(fk!==furnitureKey){furnitureKey=fk;disposeGeometry(roomRoot);roomRoot.clear();for(const p of s.placed){const f=furnitureById(p.id);if(!f)continue;const model=furnitureModel(f,kit);model.position.set(p.x,0,p.z);model.rotation.y=p.rotation*Math.PI/180;roomRoot.add(model);}path=[];if(blocked(avatar.position.x,avatar.position.z))avatar.position.set(p.level>0?well.x:0,0,p.level>0?well.z+1.6:size.depth/2-.9);}
 const valid=!!s.draft&&!placementIssue(s.draft,s.placed,s.resident.house),dk=JSON.stringify([s.draft?.id,valid]);if(dk!==draftKey){draftKey=dk;disposeGeometry(ghost);ghost.traverse(o=>{if(o instanceof THREE.Mesh&&(o.material as THREE.Material).userData.preview)(o.material as THREE.Material).dispose()});ghost.clear();if(s.draft){const model=furnitureModel(furnitureById(s.draft.id)!,kit);model.traverse(o=>{if(o instanceof THREE.Mesh){const m=(o.material as THREE.MeshStandardMaterial).clone();m.userData.preview=true;m.transparent=true;m.opacity=.72;m.depthWrite=false;m.color.lerp(new THREE.Color(valid?'#8ed29a':'#e6806f'),.4);o.material=m;}});ghost.add(model);}}
 ghost.visible=footprint.visible=s.editing&&!!s.draft;if(s.draft){ghost.position.set(s.draft.x,.03,s.draft.z);ghost.rotation.y=s.draft.rotation*Math.PI/180;const r=furnitureRect(s.draft);footprint.position.set(r.x,.105,r.z);footprint.scale.set(r.w,1,r.d);footMaterial.color.set(valid?'#49bc78':'#e16b59');edgeMaterial.color.copy(footMaterial.color);}

 for(const g of roomRoot.children)g.visible=g.userData.furniture!==s.draft?.id;
 if(wasControlling&&!s.controlling){keys.clear();path=[];}if(!wasControlling&&s.controlling){avatar.position.set(s.resident.indoorX??0,0,s.resident.indoorZ??2.5);}wasControlling=s.controlling;if(!s.controlling){avatar.position.x+=((s.resident.indoorX??0)-avatar.position.x)*Math.min(1,dt*10);avatar.position.z+=((s.resident.indoorZ??2.5)-avatar.position.z)*Math.min(1,dt*10);}
 if(!s.editing&&s.controlling){let x=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0)+s.stick.x,z=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0)+s.stick.z;if(Math.hypot(x,z)>.05)path=[];else if(path.length){x=path[0].x-avatar.position.x;z=path[0].z-avatar.position.z;if(Math.hypot(x,z)<.12){path.shift();x=z=0;}}
 const len=Math.hypot(x,z);if(len>.05){const dx=x/len*dt*2.5,dz=z/len*dt*2.5;if(!blocked(avatar.position.x+dx,avatar.position.z))avatar.position.x+=dx;if(!blocked(avatar.position.x,avatar.position.z+dz))avatar.position.z+=dz;avatar.rotation.y=Math.atan2(x,z);}legs.forEach((l,i)=>l.rotation.x=len>.05?Math.sin(now*.015+i*Math.PI)*.4:0);arms.forEach((a,i)=>a.rotation.x=len>.05?Math.sin(now*.015-i*Math.PI)*.3:0);}
 avatar.position.y=0;animateLifeGesture(avatar,s.resident,Date.now(),reducedMotion);s.onPosition({x:avatar.position.x,z:avatar.position.z,level:s.level});
 const others=s.peers.filter(person=>person.id!==s.resident.id&&person.level===s.level);for(const [id,entry]of visitors)if(!others.some(person=>person.id===id)){disposeGeometry(entry.model);entry.model.removeFromParent();entry.label.remove();visitors.delete(id);}
 for(const person of others){let entry=visitors.get(person.id);if(!entry){const model=makeAvatar(person),label=document.createElement('div');label.className='interior-neighbor-label';el.appendChild(label);model.position.set(person.x,0,person.z);scene.add(model);entry={model,label};visitors.set(person.id,entry);}const g=entry.model,dx=person.x-g.position.x,dz=person.z-g.position.z,moving=Math.hypot(dx,dz)>.03;g.position.x+=dx*Math.min(1,dt*9);g.position.z+=dz*Math.min(1,dt*9);g.position.y=0;if(moving)g.rotation.y=Math.atan2(dx,dz);(g.userData.legs as THREE.Mesh[]).forEach((leg,i)=>leg.rotation.x=moving?Math.sin(now*.015+i*Math.PI)*.4:0);dressAvatar(g,person,kit.mat);animateLifeGesture(g,person,Date.now(),reducedMotion);const screen=g.position.clone().add(new THREE.Vector3(0,2.3,0)).project(camera);entry.label.style.left=`${(screen.x+1)*el.clientWidth/2}px`;entry.label.style.top=`${(-screen.y+1)*el.clientHeight/2}px`;entry.label.textContent=person.name;}
 renderer.render(scene,camera);};frame=requestAnimationFrame(animate);
 return()=>{disposed=true;cancelAnimationFrame(frame);for(const entry of visitors.values())entry.label.remove();observer.disconnect();window.removeEventListener('keydown',keyDown);window.removeEventListener('keyup',keyUp);window.removeEventListener('blur',blur);renderer.domElement.removeEventListener('pointerdown',pointerDown);renderer.domElement.removeEventListener('pointerup',pointerUp);renderer.domElement.removeEventListener('pointermove',pointerMove);renderer.domElement.removeEventListener('pointercancel',pointerCancel);renderer.domElement.removeEventListener('lostpointercapture',pointerCancel);disposeGeometry(scene);ghost.traverse(o=>{if(o instanceof THREE.Mesh)(o.material as THREE.Material).dispose()});grid.geometry.dispose();(grid.material as THREE.Material).dispose();edge.geometry.dispose();footMaterial.dispose();edgeMaterial.dispose();kit.dispose();sun.shadow.dispose();releaseTownRenderer(renderer);};
 },[props.resident.house,props.interior.wall,props.interior.floor,props.level]);
 return <div className="interior-canvas" aria-label={props.editing?'Place furniture on your room grid':'Your furnished home. Click the floor or use movement keys to walk.'}><div className="town-canvas" ref={host}/>{error&&<p role="alert">{error}</p>}</div>;
}
