'use client';
import {useState} from 'react';
import {ArrowRight,Home,KeyRound,Users,Search} from 'lucide-react';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import type {TownState} from './data';
type Destination={id:string;name:string;private:number;residents:number;online:number;project:number;farm_funded:number};
type Preview={destination:Destination;homes:{id:number;name:string}[]};
export default function MoveTownPanel({data,busy,onRequest,onMove}:{data:TownState;busy:boolean;onRequest:(action:string,args:Record<string,unknown>)=>Promise<any>;onMove:(args:Record<string,unknown>)=>Promise<boolean>}){
 const [code,setCode]=useState(''),[towns,setTowns]=useState<Destination[]|null>(null),[preview,setPreview]=useState<Preview|null>(null),[home,setHome]=useState(''),[confirmed,setConfirmed]=useState(false),[accessKey,setAccessKey]=useState('');
 async function browse(){setPreview(null);setConfirmed(false);const v=await onRequest('move-options',{mode:'public'});if(v)setTowns(v.towns);}
 async function inspect(destination?:string){setPreview(null);setConfirmed(false);const key=destination?'':code.trim().toUpperCase();const v=await onRequest('move-options',{destination,key});if(v){setAccessKey(key);setPreview(v);setHome(v.homes[0]?String(v.homes[0].id):'');}}
 const choice=preview?.homes.find(h=>String(h.id)===home);
 return <div className="move-town-panel"><p>Find your people. Move from <strong>{data.town.name}</strong> to a town with an open spot, at no cost.</p>
 {!confirmed?<><form onSubmit={e=>{e.preventDefault();void inspect()}}><label className="field-label" htmlFor="move-town-code">A friend’s town code</label><div className="move-code-row"><input id="move-town-code" value={code} maxLength={32} autoCapitalize="characters" autoComplete="off" spellCheck={false} placeholder="Paste their town code" onChange={e=>setCode(e.target.value)}/><button className="secondary-button" disabled={busy||!code.trim()}><KeyRound size={17}/>Find town</button></div></form><button className="secondary-button full" disabled={busy} onClick={()=>void browse()}><Search size={17}/>Browse public towns with room</button>
 {towns!==null&&!preview&&<div className="move-town-list">{towns.length?towns.map(t=><button className="move-town-option" key={t.id} disabled={busy} onClick={()=>void inspect(t.id)}><span><strong>{t.name}</strong><small>{t.residents}/50 residents · {t.online} online now</small></span><ArrowRight size={18}/></button>):<p>No other public towns have space right now. You can still look up a friend’s town using their code.</p>}</div>}
 {preview&&<section className="move-destination"><span className="eyebrow">Your possible next chapter</span><h3>{preview.destination.name}</h3><p><Users size={16}/> {preview.destination.residents}/50 residents · {preview.destination.online} online · {50-preview.destination.residents} spots open</p><p className="note">Park {preview.destination.project}% · Town Farm {Math.floor(preview.destination.farm_funded/6000*100)}%</p><h3>Choose your new address</h3><p>Your current house design, upgrades, and belongings come with you.</p><RadioGroup className="move-addresses" value={home} onValueChange={v=>setHome(String(v))} aria-label="Vacant homes in the destination town" disabled={busy}>{preview.homes.map(h=><label className="option" key={h.id}><RadioGroupItem value={String(h.id)}/><span><Home size={16}/>{h.name}</span></label>)}</RadioGroup><p className="note">These homes are available now. Your spot is secured only when you confirm.</p><button className="primary-button full" disabled={busy||!choice} onClick={()=>setConfirmed(true)}>Review my move<ArrowRight size={17}/></button></section>}</>:preview&&<section className="move-destination"><span className="eyebrow">Ready to move?</span><h3>{choice?.name} · {preview.destination.name}</h3><div className="move-summary"><h4>Coming with you</h4><p>Your coins, job, XP, education, outfits, equipment, and house upgrades. Your next house upkeep payment stays on its current schedule.</p><h4>Staying in {data.town.name}</h4><p>Town coins, donations, projects, and your contribution history. Your old address becomes vacant. Any campaign or mayoral role ends; your current work shift stops.</p><p className="note">If voting has already opened in your new town, you can participate starting with the next election. You can move again later if there is room, but your old address is not reserved.</p></div><button className="primary-button full" disabled={busy||!choice} onClick={async()=>{const moved=await onMove({destination:preview.destination.id,key:accessKey,home:Number(home),fromTown:data.town.id,membership:data.resident.townJoinedAt??0});if(!moved){setConfirmed(false);setPreview(null);}}}>Move to {preview.destination.name} · free<ArrowRight size={17}/></button><button className="secondary-button full" disabled={busy} onClick={()=>setConfirmed(false)}>Keep looking</button></section>}
 <p className="note">Your current home stays yours until the move succeeds. A town code grants entry to that town; friends also need access to this game.</p></div>;
}
