'use client';
import {useState} from 'react';
import {Cat,Dog,PawPrint,Coins,MapPin,Check} from 'lucide-react';
import {PETS,petById} from './pets';
import {HOMES,type TownState} from './data';
export default function PetPanel({data,busy,onAction,onPlan,onLook}:{data:TownState;busy:boolean;onAction:(action:string,args:Record<string,unknown>,message?:string)=>unknown;onPlan:()=>void;onLook:(x:number,z:number)=>void}){
 const [kind,setKind]=useState<'cat'|'dog'>('cat'),built=data.planning.buildings.some(b=>b.kind==='pets'),active=kind==='cat'?data.resident.catPet:data.resident.dogPet,home=HOMES[data.resident.home??0];
 return <div className="pet-panel"><div className="pet-welcome"><PawPrint size={28}/><p>A friend to come home to. Cats settle on the porch; dogs explore the yard. Everyone in town can see them, even while you’re offline.</p></div>{!built&&<div className="pet-locked"><strong>The town hasn’t opened its Pet Store yet.</strong><p>Propose Paws &amp; Porches under Town planning → Community buildings. After the resident vote and 1,800-coin funding, the mayor places the shop and pet purchases unlock.</p><button className="secondary-button full" onClick={onPlan}>Plan the Pet Store</button><p className="note">You can still bring outside any pets you already own.</p></div>}
 <div className="lifestyle-tabs" aria-label="Pet type"><button aria-pressed={kind==='cat'} onClick={()=>setKind('cat')}><Cat size={18}/>Cats</button><button aria-pressed={kind==='dog'} onClick={()=>setKind('dog')}><Dog size={18}/>Dogs</button></div>
 <div className="pet-home-status"><strong>{active?`${petById(active)?.name} · ${kind==='cat'?'on the porch':'in the yard'}`:`No ${kind} outside right now`}</strong>{active&&<button className="secondary-button" disabled={busy} onClick={()=>onAction('pet',{pet:null,slot:kind},'Your pet is resting indoors.')}>Let rest indoors</button>}</div>
 <div className="pet-catalog">{PETS.filter(p=>p.kind===kind).map(p=>{const owned=data.resident.items.includes(p.id),selected=active===p.id,Icon=kind==='cat'?Cat:Dog;return <article className={`pet-card ${selected?'is-selected':''}`} key={p.id}><div className="pet-card-heading"><Icon size={32} style={{color:p.coat,filter:'drop-shadow(0 1px 1px #6b6655)'}}/><div><h3>{p.name}</h3><span className="pet-coat" aria-label="Coat colors"><i style={{background:p.coat}}/><i style={{background:p.accent}}/></span></div></div><p>{selected?<><Check size={15}/>At home</>:owned?'Your companion':<><Coins size={15}/>{p.price} coins</>}</p><button className={owned?'secondary-button full':'primary-button full'} disabled={busy||selected||!owned&&(!built||data.resident.coins<p.price)} onClick={()=>onAction('pet',{pet:p.id},`${p.name} is waiting at home!`)}>{selected?'Outside at home':owned?'Bring outside':`Buy ${kind} · ${p.price}`}</button></article>})}</div>
 <button className="secondary-button full" onClick={()=>onLook(home.x,home.z)}><MapPin size={17}/>Look at my pets at home</button><p className="note">One cat and one dog can be outside at a time. Switch between your owned pets for free. No pet upkeep fees; pets and their ownership come with you when you move.</p></div>;
}
