'use client';
import {ArrowDown,ArrowLeft,ArrowRight,ArrowUp,RotateCw,Plus,Minus,X,MapPin,Check} from 'lucide-react';
import {placementShape,placementError,type BuildingChoice} from './placement';
import {institutionShape,locationOf,TERRITORIES,type Placement,type PlanProposal} from './charters';
import type {TownState} from './data';
type Props={data:TownState;choice:BuildingChoice;value:Placement;plan?:PlanProposal;busy:boolean;onChange:(v:Placement)=>void;onClose:()=>void;onConfirm:()=>void;onLook:(x:number,z:number)=>void;onZoom:(n:number)=>void;onOverview:()=>void};
export default function PlacementDock({data,choice,value,plan,busy,onChange,onClose,onConfirm,onLook,onZoom,onOverview}:Props){const shape=placementShape(data.planning,choice),old=data.planning.institutions.find(i=>i.id===choice.institution),current=old?institutionShape(old):null,error=placementError(data.planning,choice,value),isMayor=data.election.mayor?.id===data.resident.id,ready=plan?.status==='ready'&&isMayor,area=Math.round(shape.width*shape.depth),oldArea=current?Math.round(current.width*current.depth):0;
 const move=(x:number,z:number)=>onChange({...value,x:value.x+x,z:value.z+z});
 return <><div className="placement-title"><div><span className="eyebrow">{ready?'Mayor’s construction view':'Town planning · size preview'}</span><h2>{shape.name}</h2><p>Tap a grid square to move the preview. Drag to pan · pinch or scroll to zoom.</p></div><button className="icon-button" onClick={onClose} aria-label="Close construction view"><X size={20}/></button></div>
 <aside className="placement-tools"><div className="placement-size"><strong>{shape.width} × {shape.depth} squares</strong><span>{area} squares of building{current?` · ${area>=oldArea?'+':''}${area-oldArea} vs current`:''}</span>{current&&<small>Current: {current.width} × {current.depth} · {current.name}</small>}</div><div className={`placement-valid ${error?'is-invalid':''}`} role="status">{error??'Clear site · front door has access'}</div><div className="placement-legend"><span>1 grid square = 1 town unit</span><span>Green: fits · Red: unavailable · Gold: front door</span></div><div className="placement-coordinate">Position {value.x}, {value.z} · Facing {['south','east','north','west'][value.rotation/90]}</div>
 <div className="placement-controls"><button className="secondary-button" aria-label="Move building west one square" onClick={()=>move(-1,0)}><ArrowLeft size={18}/></button><button className="secondary-button" aria-label="Move building north one square" onClick={()=>move(0,-1)}><ArrowUp size={18}/></button><button className="secondary-button" aria-label="Move building south one square" onClick={()=>move(0,1)}><ArrowDown size={18}/></button><button className="secondary-button" aria-label="Move building east one square" onClick={()=>move(1,0)}><ArrowRight size={18}/></button><button className="secondary-button" onClick={()=>onChange({...value,rotation:(value.rotation+90)%360})}><RotateCw size={18}/>Rotate</button></div>
 <div className="button-row"><button className="secondary-button" onClick={()=>onZoom(-8)} aria-label="Zoom in"><Plus size={18}/></button><button className="secondary-button" onClick={()=>onZoom(8)} aria-label="Zoom out"><Minus size={18}/></button><button className="secondary-button" onClick={()=>onLook(value.x,value.z)}><MapPin size={16}/>Preview</button><button className="secondary-button" onClick={onOverview}>Whole town</button></div>
 <div className="placement-jumps">{old&&<button onClick={()=>{const p=locationOf(old);onLook(p.x,p.z)}}>Current building</button>}{TERRITORIES.filter(t=>data.planning.territories.includes(t.id)).map(t=><button key={t.id} onClick={()=>onLook(t.x,t.z)}>{t.name}</button>)}</div>
 <button className="primary-button full" disabled={!ready||busy||!!error} onClick={onConfirm}><Check size={18}/>{busy?'Saving placement…':ready?'Place building here · already paid':'Preview only · vote and funding required'}</button>{!isMayor&&plan?.status==='ready'&&<p className="note">Only the elected mayor can confirm placement.</p>}<button className="secondary-button full" disabled={busy} onClick={onClose}>Back to town planning</button></aside></>;
}
