'use client';
import {useState,useRef,useEffect} from 'react';
import {MapPin,Landmark,ArrowRight,Ship} from 'lucide-react';
import {Progress} from '@/components/ui/progress';
import {CHARTER_NODES,INSTITUTIONS,TERRITORIES,PLOTS,REDEVELOPMENTS,nodeById,plotById,plotOwned,plotOccupied,fitsPlot,institutionShape,proposalTitle,proposalSite,townBuildings,type PlanningState} from './charters';
import type {TownState} from './data';
type Draft={kind:'branch'|'relocate'|'expand'|'build';institution?:string;option:string;plot?:string};
type Props={data:TownState;busy:boolean;onAction:(action:string,args:Record<string,unknown>)=>void;onLook:(x:number,z:number)=>void;onTravel:()=>void};
function PlanMap({state,site}:{state:PlanningState;site?:{x:number;z:number;width:number;depth:number}}){return <svg className="planning-map" viewBox="-66 -100 184 204" role="img" aria-label="Planning map: existing civic buildings, owned land, available expansion boundaries, and the selected site"><rect x="-66" y="-100" width="184" height="204" fill="#82b8c0"/><rect x="-60" y="-58" width="120" height="113" fill="#b7ca95"/>{TERRITORIES.map(t=><g key={t.id}><rect x={t.x-t.width/2} y={t.z-t.depth/2} width={t.width} height={t.depth} fill={state.territories.includes(t.id)?'#a8c47e':'#94b4a1'} stroke="#577a69" strokeDasharray={state.territories.includes(t.id)?undefined:'2 2'} strokeWidth=".5"/><text x={t.x} y={t.z-t.depth/2+4} fontSize="3" textAnchor="middle" fill="#345c4c">{t.name}</text></g>)}{PLOTS.filter(p=>plotOwned(p,state)).map(p=><rect key={p.id} x={p.x-p.width/2} y={p.z-p.depth/2} width={p.width} height={p.depth} fill={plotOccupied(p.id,state)?'#c8bd9e':'#dce4ad'} stroke="#7c9462" strokeWidth=".4"/>)}{townBuildings(state).map(b=><rect key={b.id} x={b.x-b.width/2} y={b.z-b.depth/2} width={b.width} height={b.depth} fill={b.roof}/>)}{site&&<rect x={site.x-site.width/2} y={site.z-site.depth/2} width={site.width} height={site.depth} fill="#e9c87155" stroke="#a66f37" strokeWidth="1.2" strokeDasharray="2 1"/>}</svg>}
export default function PlanningPanel({data,busy,onAction,onLook,onTravel}:Props){const s=data.planning,mayor=data.election.mayor,isMayor=mayor?.id===data.resident.id,active=s.proposals.find(p=>p.status==='voting'||p.status==='approved'),[draft,setDraft]=useState<Draft|null>(null),review=useRef<HTMLElement>(null);
 useEffect(()=>{if(draft)review.current?.scrollIntoView({block:'nearest',behavior:'instant'})},[draft]);
 useEffect(()=>{if(active)setDraft(null)},[active?.id]);
 const institution=draft?.institution?s.institutions.find(i=>i.id===draft.institution):undefined,fromPlot=institution?plotById(institution.plot):undefined,draftNode=draft?.kind==='branch'?nodeById(draft.option):undefined;
 const site=draft?.kind==='expand'?TERRITORIES.find(t=>t.id===draft.option):draft?.kind==='relocate'?plotById(draft.option):draft?.kind==='build'?plotById(draft.plot!):fromPlot;
 const cost=draft?.kind==='expand'?TERRITORIES.find(t=>t.id===draft.option)!.cost:draft?.kind==='branch'?draftNode!.cost:draft?.kind==='build'?REDEVELOPMENTS.find(r=>r.id===draft.option)!.cost:draft?.kind==='relocate'?800+(institution?.node==='root'?0:600):0;
 const approveDraft=()=>{if(draft)onAction('plan-propose',draft)};
 return <div className="planning-panel"><div className="planning-intro"><Landmark size={23}/><p>Build a town with its own story. Charter choices stay with an institution forever; its location can change. Private homes and belongings are outside this planning system.</p></div>
 {active&&<section className="featured-project"><span className="eyebrow">{active.status==='voting'?'Resident planning vote':'Approved town development'}</span><h3>{proposalTitle(active)}</h3><p>Proposed by {active.name} · {active.cost.toLocaleString()} town coins</p><p className="note">{active.kind==='branch'?'This charter branch is permanent. Alternative branches will close when construction completes.':active.kind==='relocate'?'The existing facility stays open until its replacement is complete. Its branch and history move with it; the former site becomes vacant.':active.kind==='expand'?'New territory and its public parcels open after the acquisition budget is fully funded.':'This vacant public parcel becomes a new community facility.'}</p>
 <PlanMap state={s} site={proposalSite(active)}/><button className="secondary-button full" onClick={()=>{const p=proposalSite(active);if(p)onLook(p.x,p.z)}}><MapPin size={16}/>View the proposed site</button>
 {active.status==='voting'?<><strong>{active.yes} support · {active.no} oppose</strong><p>Closes {new Date(active.closes).toLocaleDateString('en-US',{month:'short',day:'numeric',timeZone:'UTC'})} · {Math.max(1,Math.ceil((active.closes-Date.now())/86400000))} days left</p><p className="note">Needs 60% support among votes cast and at least {active.quorum} of {active.electorate} eligible residents voting. The roll includes settled residents active in the 14 days before this vote opened. The roll and proposal are fixed for this vote.</p>{active.eligible?<div className="button-row"><button className="primary-button" disabled={busy||active.myVote===1} onClick={()=>onAction('plan-vote',{plan:active.id,vote:true})}>{active.myVote===1?'Your vote: support':'Support this plan'}</button><button className="secondary-button" disabled={busy||active.myVote===0} onClick={()=>onAction('plan-vote',{plan:active.id,vote:false})}>{active.myVote===0?'Your vote: oppose':'Oppose this plan'}</button></div>:<p className="note">You were not in this proposal’s resident roll. You can take part in future planning votes.</p>}</>:<><div className="progress-label"><span>{active.funded.toLocaleString()} / {active.cost.toLocaleString()} funded</span><strong>{Math.floor(active.funded/active.cost*100)}%</strong></div><Progress className="progress" value={active.funded/active.cost*100} aria-label="Development funding"/>{isMayor?<div className="button-row"><button className="primary-button" disabled={busy||data.town.treasury<Math.min(100,active.cost-active.funded)} onClick={()=>onAction('plan-fund',{plan:active.id,funded:active.funded,amount:Math.min(100,active.cost-active.funded)})}>Allocate {Math.min(100,active.cost-active.funded)} coins</button><button className="secondary-button" disabled={busy||data.town.treasury<active.cost-active.funded} onClick={()=>onAction('plan-fund',{plan:active.id,funded:active.funded,amount:active.cost-active.funded})}>Complete · {(active.cost-active.funded).toLocaleString()}</button></div>:<p>Mayor {mayor?.name} can allocate the construction budget.</p>}</>}
 <button className="secondary-button full" disabled={busy||data.resident.coins<25} onClick={()=>onAction('support-project',{})}>Add 25 coins to the town fund</button></section>}
 {!isMayor&&<p className="note">Everyone can explore the plans below. The elected mayor proposes developments; residents approve them in a seven-day vote.</p>}
 {active&&<p className="note">Complete this vote and its approved development before opening another planning proposal. Progress survives a change of mayor.</p>}
 <h3>Institutions &amp; permanent branches</h3>{s.institutions.map(i=>{const current=institutionShape(i),plot=plotById(i.plot)!,vacancies=PLOTS.filter(p=>plotOwned(p,s)&&!plotOccupied(p.id,s)&&fitsPlot(current,p));return <details className="institution-card" key={i.id}><summary><span>{INSTITUTIONS.find(x=>x.id===i.id)!.name}<small>{current.name} · {plot.name}</small></span><ArrowRight size={17}/></summary><p>Your current building is {current.width} × {current.depth}. This parcel holds up to {plot.width-1} × {plot.depth-1}.</p><div className="charter-tree">{CHARTER_NODES.filter(n=>n.institution===i.id&&n.parent==='root').map(first=>{const chosen=i.node===first.id||nodeById(i.node)?.parent===first.id,locked=i.node!=='root'&&!chosen;return <div className={`charter-path ${chosen?'is-chosen':''} ${locked?'is-closed':''}`} key={first.id}><span className="eyebrow">{chosen?'Chosen path':locked?'Closed by your charter':'Permanent choice'}</span>{[first,...CHARTER_NODES.filter(n=>n.parent===first.id)].map(n=>{const possible=n.parent===i.node&&fitsPlot(n,plot),selected=n.id===i.node;return <button className={`charter-node ${draft?.option===n.id?'is-selected':''}`} key={n.id} disabled={!isMayor||!!active||busy||!possible} onClick={()=>setDraft({kind:'branch',institution:i.id,option:n.id})}><strong>{selected?'✓ ':''}{n.name}</strong><small>{n.description}</small><span>{n.cost.toLocaleString()} coins · {n.width} × {n.depth}{n.parent===i.node&&!fitsPlot(n,plot)?' · Move to a larger site first':''}</span></button>})}</div>})}</div>
 <details className="relocation-options"><summary>Relocate this institution</summary><p>Its branch stays {current.name}. The old {plot.name} site opens for redevelopment only when the new building is ready.</p>{vacancies.length?<div className="parcel-options">{vacancies.map(p=><button className={`secondary-button ${draft?.option===p.id?'is-selected':''}`} key={p.id} disabled={!isMayor||!!active||busy} onClick={()=>setDraft({kind:'relocate',institution:i.id,option:p.id})}>{p.name}<small>{p.width} × {p.depth} parcel</small></button>)}</div>:<p>No vacant parcel fits. Acquire more territory or free a suitable civic parcel first.</p>}</details><button className="secondary-button full" onClick={()=>onLook(plot.x,plot.z)}><MapPin size={16}/>Visit this building’s location</button></details>})}
 <h3>Expand our territory</h3><div className="territory-options">{TERRITORIES.map(t=><button key={t.id} className={`territory-choice ${draft?.option===t.id?'is-selected':''}`} disabled={!isMayor||!!active||busy||s.territories.includes(t.id)} onClick={()=>setDraft({kind:'expand',option:t.id})}><strong>{s.territories.includes(t.id)?'✓ ':''}{t.name}</strong><p>{t.description}</p><small>{s.territories.includes(t.id)?'Owned by your town':`${t.cost.toLocaleString()} coins · resident vote required`}</small></button>)}</div>
 {s.territories.includes('island')&&<button className="secondary-button full" onClick={onTravel}><Ship size={17}/>Walk to the ferry landing</button>}
 <details className="civic-section"><summary>Build on vacant civic land</summary><p>Vacated sites and expansion parcels can become gardens, food halls, or craft studios. These buildings do not inherit another institution’s branch.</p>{PLOTS.filter(p=>plotOwned(p,s)&&!plotOccupied(p.id,s)).map(p=><div className="vacant-site" key={p.id}><strong>{p.name}</strong><div className="button-row">{REDEVELOPMENTS.map(r=><button className="secondary-button" disabled={!isMayor||!!active||busy} key={r.id} onClick={()=>setDraft({kind:'build',option:r.id,plot:p.id})}>{r.name} · {r.cost.toLocaleString()}</button>)}</div></div>)}</details>
 {draft&&!active&&<section className="planning-review" ref={review}><span className="eyebrow">Review before opening a town vote</span><h3>{proposalTitle({...draft,institution:draft.institution??null})}</h3><p>{cost.toLocaleString()} town coins · {site?.name}</p><PlanMap state={s} site={site}/><p>{draft.kind==='branch'?`Choosing ${draftNode?.name} permanently closes the other options at this fork. The new building replaces ${institutionShape(institution!).name} at its current site.`:draft.kind==='relocate'?`Move ${institutionShape(institution!).name} from ${fromPlot?.name} to ${site?.name}. Its charter stays unchanged, and its former parcel becomes vacant.`:draft.kind==='expand'?'This acquisition adds walkable territory and new public parcels. Residents must approve it before any construction funds can be allocated.':'This creates a permanent community building on an owned, vacant parcel.'}</p><p className="note">No coins are spent when a proposal opens. The seven-day vote cannot be edited. If it passes, the mayor can fund it in installments; the existing facility remains available until completion.</p><div className="button-row"><button className="primary-button" disabled={!isMayor||busy} onClick={approveDraft}>Open resident vote</button><button className="secondary-button" onClick={()=>setDraft(null)}>Clear draft</button></div></section>}
 <details className="civic-section"><summary>Previous planning decisions</summary>{s.proposals.filter(p=>p.status==='completed'||p.status==='rejected').map(p=><div className="civic-record" key={p.id}><strong>{proposalTitle(p)}</strong><p>{p.status==='completed'?'Completed and part of your town':'Did not pass'} · {p.yes} support / {p.no} oppose</p></div>)}</details></div>;
}
