'use client';
import {sharedLifeScenery,animateLifeGesture} from './sharedLifeScenery';
import {FARM_BEDS,FARM_ORDER,PICNIC,lifeTarget,GESTURES,type SharedLifeState} from './sharedLife';
import {homeDoor} from './interiors';
import {townPets} from './petScenery';
import {farmScenery} from './farmScenery';
import {TOWN_FARM,FARM_GATE,farmIsOpen} from './townFarm';
import {GrassSync} from './grassSync';
import {houseById,grassHeight} from './lifestyle';
import {dressAvatar} from './wardrobeScenery';
import {fieldPose,FIELD_DURATION} from './fieldAnimation';
import {placementBuilding,placementError,protectedLand,type BuildingChoice} from './placement';
import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import {DEFAULT_YAW,DEFAULT_PITCH,clampPitch,screenToGround,cameraOffset} from './camera';
import {installCameraGestures} from './cameraGestures';
import {WORK_TARGETS,TARGET_BY_ID,STATIONS} from './workTargets';
import {GARDEN_AREAS,inCommunityGarden} from './gardenAreas';
import {charterScenery,buildingModel} from './charterScenery';
import {EMPTY_PLANNING,townBuildings,townLayout,marketStalls,FERRY_STOPS,proposalSite,proposalTitle,nodeById,locationOf,type PlanningState,type Placement} from './charters';
import {paperDestination,paperPose,PAPER_TIMING,type PaperThrow} from './paperDelivery';
import {civicScenery} from './civicScenery';
import {projectById,type CivicState} from './civicProjects';
import {conceptScenery} from './conceptScenery';
import {findPath} from './pathfinding';
import {entrance,BRIDGES,ROADS,COMMUNITY_PARK,isTownBlocked,groundHeight,WINDMILL} from './townLayout';
import {HOMES,TASKS,PARK,SCHOOL,LAWN_CELLS,sweptGrass,type Peer,type Resident} from './data';
export type SceneApi={settleGrass:(sequence:number,history:{cell:string;cut_at:number}[])=>void;position:(consume?:boolean)=>{x:number;z:number;path:{x:number;z:number}[];cutSequence:number};navigate:(x:number,z:number)=>void;center:()=>void;lookAt:(x:number,z:number)=>void;orbit:(yaw:number,pitch?:number)=>void;pan:(x:number,y:number)=>void;resetCamera:()=>void;overview:()=>void;stop:()=>void;zoom:(by:number)=>void;setPosition:(x:number,z:number)=>void};
type Props={controlling?:boolean;onControl?:()=>Promise<boolean>;onManualMove?:()=>void;life?:SharedLifeState;highlightHome?:number|null;parcelHomes?:number[];grassHistory?:{cell:string;cut_at:number}[];townCreated?:number;placement?:{choice:BuildingChoice;value:Placement};onPlacementChange?:(p:Placement)=>void;planning?:PlanningState;paperThrows?:PaperThrow[];onPaperLanded?:(paper:PaperThrow)=>void;onPaperSound?:(stage:'release'|'impact')=>void;mayorId?:string;civic?:CivicState;cameraMode?:'pan'|'orbit';focus?:[number,number]|null;player?:Resident;peers?:Peer[];properties?:{home:number;items:string[];name:string;house?:string;catPet?:string|null;dogPet?:string|null}[];completed?:string[];lawnCuts?:string[];worldWork?:{id:string;target:string;completed:number}[];rewardFx?:{target:string;at:number;origin?:{x:number;z:number}}|null;onSelectTask?:(id:string)=>void;project?:number;working?:boolean;enabled?:boolean;stick?:{x:number;y:number};onReady?:(api:SceneApi)=>void;onNear?:(id:string|null)=>void;onAction?:()=>void;onPaperAction?:()=>void;onSelectHome?:(id:number)=>void};
export default function TownScene(props:Props){const host=useRef<HTMLDivElement>(null);const live=useRef(props);live.current=props;const focus=useRef<[number,number]|null>(props.focus??null);focus.current=props.focus??null;const [error,setError]=useState('');
const grassState=useRef({owner:props.player?.id,tracker:new GrassSync()});if(grassState.current.owner!==props.player?.id)grassState.current={owner:props.player?.id,tracker:new GrassSync()};
const layoutKey=JSON.stringify([props.planning?.territories,props.planning?.institutions,props.planning?.buildings,farmIsOpen(props.planning??{}),props.properties?.map(p=>[p.home,p.house])]);
useEffect(()=>{if(!host.current)return;const planning=live.current.planning??EMPTY_PLANNING,buildings=townBuildings(planning),stalls=marketStalls(planning).filter(()=>planning.institutions.find(i=>i.id==='towncenter')?.node==='root'),layout=townLayout(planning);const worldBlocked=(x:number,z:number)=>isTownBlocked(x,z,layout);const el=host.current;let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});}catch{setError('This device could not start the 3D view. Try a browser with WebGL enabled.');return}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.0;el.appendChild(renderer.domElement);
const reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;const scene=new THREE.Scene();scene.background=new THREE.Color('#b8d8d0');scene.fog=new THREE.Fog('#b8d8d0',250,450);
const camera=new THREE.OrthographicCamera(-30,30,20,-20,.1,420);let viewHeight=35;const target=new THREE.Vector3(0,0,0),cameraTarget=new THREE.Vector3(0,0,5);let yaw=DEFAULT_YAW,pitch=DEFAULT_PITCH;const offset=new THREE.Vector3(24,31,37);camera.position.copy(offset);camera.lookAt(target);
scene.add(new THREE.HemisphereLight('#fff2ce','#617e50',1.6));const sun=new THREE.DirectionalLight('#fff3d1',2.3);sun.position.set(-22,45,15);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-85;sun.shadow.camera.right=85;sun.shadow.camera.top=85;sun.shadow.camera.bottom=-85;sun.shadow.camera.far=190;sun.shadow.bias=-.0003;sun.shadow.normalBias=.04;scene.add(sun);
const materials=new Map<string,THREE.MeshStandardMaterial>();const mat=(color:string)=>{if(!materials.has(color))materials.set(color,new THREE.MeshStandardMaterial({color,roughness:.92,flatShading:true}));return materials.get(color)!};
const staticRoot=new THREE.Group();scene.add(staticRoot);
function mesh(g:THREE.BufferGeometry,c:string,x:number,y:number,z:number,parent:THREE.Object3D=staticRoot){const m=new THREE.Mesh(g,mat(c));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}
function box(w:number,h:number,d:number,c:string,x:number,y:number,z:number,parent?:THREE.Object3D){return mesh(new THREE.BoxGeometry(w,h,d),c,x,y,z,parent)}
function ball(r:number,c:string,x:number,y:number,z:number,parent?:THREE.Object3D){return mesh(new THREE.IcosahedronGeometry(r,1),c,x,y,z,parent)}
function cylinder(r:number,h:number,c:string,x:number,y:number,z:number,parent?:THREE.Object3D,rt?:number){return mesh(new THREE.CylinderGeometry(rt??r,r,h,10),c,x,y,z,parent)}
function roof(w:number,d:number,h:number,c:string,x:number,y:number,z:number,parent?:THREE.Object3D){const s=new THREE.Shape();s.moveTo(-w/2,0);s.lineTo(0,h);s.lineTo(w/2,0);s.closePath();const g=new THREE.ExtrudeGeometry(s,{depth:d,bevelEnabled:false});g.translate(0,0,-d/2);return mesh(g,c,x,y,z,parent)}
let randSeed=44;function rand(){randSeed=(randSeed*1664525+1013904223)>>>0;return randSeed/4294967296}
// The terrain and every prop are real Three.js geometry, lit from one warm sun.
box(150,1.1,155,'#8cab60',0,-.62,0);box(150,.2,155,'#92b86b',0,-.02,0);
// Five bridges have bank openings, approach ramps, and the same walkable deck as navigation.
box(8,.05,145,'#64b6bd',28,.1,0);box(7,.06,145,'#79c6c9',28,.13,0);
for(const x of [23.6,32.4]){let start=-72.5;for(const end of [...BRIDGES.map(b=>b.z-3.1),55.5]){const length=end-start;if(length>0){box(.7,.6,length,'#abaf81',x,.04,start+length/2);box(.35,.15,length,'#d8d4ad',x,.38,start+length/2)}start=end+6.2}}
for(const bridge of BRIDGES){
 for(let j=0;j<16;j++)box(10,.2,.33,'#aa8051',28,.42,bridge.z-2.5+j*.34);
 for(const x of [22,34]){const ramp=box(2.06,.13,5.4,'#b18b5c',x,.27,bridge.z);ramp.rotation.z=x<28?Math.atan(.2):-Math.atan(.2)}
 for(const z of [bridge.z-2.8,bridge.z+2.8]){box(10,.13,.13,'#7e6546',28,1.15,z);for(const x of [23,26,30,33])box(.15,1,.15,'#8a6b45',x,.7,z)}
}
for(let j=0;j<65;j++)box(.35+rand()*1.6,.012,.06,'#b6e4dc',25+rand()*6,.17,-65+rand()*130);
function flower(x:number,z:number,color:string,parent:THREE.Object3D=staticRoot){cylinder(.035,.35,'#648642',x,.28,z,parent);const bloom=ball(.13,color,x,.49,z,parent);bloom.scale.y=.65;ball(.05,'#efce68',x,.55,z,parent)}
function tree(x:number,z:number,scale=1){if(inCommunityGarden(x,z,1.5)||(Math.abs(x)<60&&z>-58&&z<55&&worldBlocked(x,z))||ROADS.some(r=>Math.abs(x-r.x)<r.width/2+1.5&&Math.abs(z-r.z)<r.depth/2+1.5))return;const g=new THREE.Group();g.position.set(x,0,z);g.scale.setScalar(scale);staticRoot.add(g);cylinder(.23,2.2,'#896645',0,1.1,0,g,.15);ball(1.4,'#63884d',0,2.9,0,g);ball(1.05,'#779953',-.65,2.6,.5,g);ball(1.1,'#88a45a',.65,3.2,-.1,g);ball(.85,'#99b766',-.2,3.75,0,g);}
function fence(x:number,z:number,w:number){for(let i=0;i<=w;i+=.8){box(.13,.7,.13,'#f0e0b5',x+i,.4,z);roof(.17,.17,.12,'#f0e0b5',x+i,.75,z)}box(w,.12,.1,'#e4d2aa',x+w/2,.35,z);box(w,.12,.1,'#e4d2aa',x+w/2,.63,z)}
function bench(x:number,z:number,parent:THREE.Object3D=staticRoot){for(let i=0;i<3;i++)box(1.5,.1,.17,'#ab8051',x,.5,z+i*.19,parent);for(const a of [-.55,.55]){box(.12,.5,.48,'#535d40',x+a,.25,z+.2,parent);box(.12,1,.1,'#535d40',x+a,.5,z-.05,parent)}box(1.5,.3,.1,'#bf945c',x,.88,z-.07,parent)}
function house(h:typeof HOMES[number]){const property=live.current.properties?.find(p=>p.home===h.id),design=property?houseById(property.house):null,level=design?.level??1;if(design)h={...h,color:design.wall,roof:design.roof};const g=new THREE.Group();g.position.set(h.x,0,h.z);staticRoot.add(g);box(4.9,.25,4.2,'#b4b18c',0,.2,0,g);box(4.3,2.5,3.5,h.color,0,1.55,0,g);const attic=new THREE.Group();attic.position.y=Math.floor((level-1)/2)*1.35;g.add(attic);box(4.38,.18,3.6,'#efdab0',0,2.6,0,attic);roof(5.1,4.2,1.75,h.roof,0,2.78,0,attic);roof(4.45,3.6,1.35,'#f1dfbd',0,2.61,0,attic);roof(5.1,4.2,1.75,h.roof,0,2.81,0,attic);box(.48,1.1,.5,'#bf9875',1.2,3.9,-.65,attic);box(.64,.14,.65,'#d5b696',1.2,4.48,-.65,attic);
// Roof courses follow both gable slopes, with a centered front dormer.
for(let side of [-1,1])for(let row=1;row<7;row++){const x=side*row*.36,y=4.56-Math.abs(x)*1.75/2.55;box(.045,.035,4.22,h.id%2?'#715e59':'#825b49',x,y,0,attic)}
box(1,.9,.45,'#eedbbb',0,3.55,1.87,attic);roof(1.3,.8,.68,h.roof,0,3.99,1.9,attic);box(.4,.56,.06,'#719cad',0,3.57,2.12,attic);box(.04,.58,.07,'#f6e5c4',0,3.57,2.16,attic);
// Exposed timber framing, sash windows, flower boxes, and a small porch.
for(const x of [-2.06,2.06])box(.14,2.45,.14,'#ac865e',x,1.54,1.78,g);box(.82,1.53,.16,'#715b3d',.55,1.03,1.84,g);box(.68,1.4,.12,['#6b8b83','#ae6f56','#668198'][h.id%3],.55,1.02,1.95,g);ball(.055,'#e8bc56',.77,1.04,2.04,g);box(1.65,.16,.8,'#c7b68e',.55,.35,2.18,g);box(1.8,.13,.48,'#dbcba7',.55,.2,2.64,g);
for(const x of [-1.15,1.55]){box(.72,.85,.13,'#f4e6bf',x,1.65,1.84,g);box(.55,.64,.06,'#79b8bc',x,1.66,1.93,g);box(.055,.7,.08,'#f9efce',x,1.66,1.98,g);box(.58,.055,.08,'#f9efce',x,1.65,1.98,g);for(const a of [-.47,.47])box(.17,.8,.12,h.roof,x+a,1.65,1.84,g);box(.88,.24,.3,'#a07850',x,1.06,1.95,g);for(let k=0;k<4;k++){ball(.14,['#d984a4','#f1d872','#b695ce'][h.id%3],x-.3+k*.2,1.25,2.02,g)}}
cylinder(.38,.48,'#b67c55',-2.45,.36,1.8,g,.45);ball(.52,'#6e914b',-2.45,.9,1.8,g);box(1.1,.055,2.5,'#cfbf96',.55,.14,3.6,g);
if(level>=3){const upper=Math.floor((level-1)/2)*1.35;box(4.3,upper,3.5,h.color,0,2.7+upper/2,0,g);for(let floor=0;floor<Math.floor((level-1)/2);floor++)for(const x of [-1.4,0,1.4]){box(.7,.8,.09,design?.trim??'#f4e6bf',x,3.25+floor*1.35,1.8,g);box(.52,.61,.07,'#79b8bc',x,3.25+floor*1.35,1.86,g);}}
if(level>=2){roof(2.5,1,.55,h.roof,.55,2.1,2.15,g);for(const x of [-.65,1.75])box(.1,1.75,.1,design?.trim??'#f4e6bf',x,1.2,2.42,g);}
if(level>=4){for(const x of [-2.1,2.1])box(.24,2.5,.24,design?.trim??'#f4e6bf',x,1.53,1.8,g);for(const x of [-1.7,-1.3,-.9])box(.065,.5,.07,design?.trim??'#f4e6bf',x,.61,2.5,g);box(1,.08,.1,design?.trim??'#f4e6bf',-1.3,.88,2.5,g);}
if(design?.style==='brick')for(let y=.55;y<2.5;y+=.3)box(4.1,.025,.04,'#d8b99c',0,y,1.78,g);
if(design?.style==='cedar')for(let y=.55;y<2.5;y+=.24)box(4.1,.035,.04,'#957052',0,y,1.78,g);

box(.16,.85,.16,'#8d7750',2.65,.5,2.1,g);box(.5,.35,.45,'#638c87',2.65,1,2.1,g);roof(.52,.47,.15,'#658e89',2.65,1.18,2.1,g);
}
HOMES.forEach(house);
// Fountain forms the visual heart of the town.
cylinder(2.45,.12,'#babda1',0,.24,0);cylinder(1.72,.55,'#dcd8b7',0,.48,0);cylinder(1.43,.1,'#6fb8bc',0,.79,0);cylinder(.3,.8,'#c3c6a8',0,1.05,0);cylinder(.87,.18,'#e1ddbe',0,1.4,0);cylinder(.68,.04,'#8dd1cb',0,1.51,0);cylinder(.15,.72,'#d5d7b2',0,1.8,0);ball(.22,'#e9cf8b',0,2.24,0);
for(const [x,z] of [[-4,-4],[4,4],[-4,4],[4,-4]]){cylinder(.43,.45,'#ba9271',x,.4,z);}
// Correct planter groups are static meshes.
for(const [x,z] of [[-4,-4],[4,4],[-4,4],[4,-4]]){for(let i=0;i<5;i++)flower(x+(rand()-.5)*.5,z+(rand()-.5)*.5,i%2?'#dda0b6':'#edda82')}
bench(-4.7,-1);bench(2.9,4.5);bench(-15,3);
function lamp(x:number,z:number){cylinder(.07,2.6,'#63725b',x,1.4,z);box(.5,.62,.5,'#e7cd85',x,2.93,z);roof(.76,.76,.38,'#576b58',x,3.26,z);for(const a of [-.25,.25])for(const b of [-.25,.25])box(.045,.65,.045,'#61715b',x+a,2.94,z+b)}
for(const p of [[-6,-5],[6,5],[-6,7],[6,-7],[-18,-4],[19,4]])lamp(p[0],p[1]);
// Shops and civic buildings face onto the square, each with its own storefront.
for(const footprint of buildings){const b={...footprint,width:footprint.modelWidth??footprint.width,depth:footprint.modelDepth??footprint.depth};if(planning.institutions.some(i=>i.id===b.id&&(i.node!=='root'||i.id==='harbor'))||b.id.startsWith('site-'))continue;const g=new THREE.Group();g.position.set(b.x,0,b.z);g.rotation.y=(b.rotation??0)*Math.PI/180;staticRoot.add(g);
 box(b.width+.4,.22,b.depth+.4,'#b8b39b',0,.22,0,g);box(b.width,b.height,b.depth,b.color,0,b.height/2+.3,0,g);
 roof(b.width+.7,b.depth+.6,b.id==='townhall'?2:1.5,b.roof,0,b.height+.32,0,g);
 box(1.3,2,.16,'#57766d',0,1.25,b.depth/2+.1,g);box(1.8,.15,1.2,'#d3c4a0',0,.28,b.depth/2+.55,g);
 for(const x of [-b.width*.31,b.width*.31]){box(b.id==='townhall'?1.2:1.8,1.5,.15,'#f5e7c6',x,1.9,b.depth/2+.09,g);box(b.id==='townhall'?1:1.6,1.3,.07,'#7baeb1',x,1.9,b.depth/2+.19,g);box(.07,1.35,.09,'#f7efce',x,1.9,b.depth/2+.24,g)}
 if(b.id==='townhall'){for(const x of [-2.2,2.2])cylinder(.19,3.7,'#f2e5c2',x,2.1,b.depth/2+.4,g);roof(5.2,1.5,1.25,'#efe2bc',0,3.75,3.5,g);box(1.8,2.7,1.7,b.color,0,b.height+2.5,0,g);roof(2.3,2.1,1,b.roof,0,b.height+3.86,0,g);mesh(new THREE.CircleGeometry(.47,20),'#fff6d6',0,b.height+2.95,.87,g);box(.035,.33,.02,'#5b655b',0,b.height+3.1,.9,g);box(.27,.035,.02,'#5b655b',.12,b.height+2.95,.9,g)}
 else if(b.id!=='school'&&b.id!=='farm-barn'){for(let i=0;i<10;i++)box((b.width+.4)/10,.18,1.3,i%2?'#fff0d1':b.roof,-b.width/2+(i+.5)*(b.width+.4)/10,2.85,b.depth/2+.55,g)}
 for(const side of [-1,1])for(let row=1;row<8;row++){const x=side*row*(b.width+.7)/16,y=b.height+.34+(b.id==='townhall'?2:1.5)*(1-Math.abs(x)/((b.width+.7)/2));box(.045,.035,b.depth+.63,'#686f69',x,y,0,g)}
 if(b.id==='school'){box(1.2,1.4,1.2,'#f0ddb2',0,b.height+1.6,0,g);roof(1.7,1.7,.8,b.roof,0,b.height+2.3,0,g);cylinder(.25,.4,'#b49753',0,b.height+1.7,.6,g);roof(2.4,1.3,.9,'#f1dfb9',0,2.8,b.depth/2+.5,g)}
 if(b.id==='farm-barn'){box(3,2.5,.18,'#826048',0,1.6,b.depth/2+.2,g);for(const x of [-1.4,0,1.4])box(.12,2.5,.08,'#ecdbb2',x,1.6,b.depth/2+.32,g);for(const y of [.4,2.8])box(3,.12,.08,'#ecdbb2',0,y,b.depth/2+.32,g);for(const x of [-.7,.7]){const brace=box(.09,2.65,.09,'#ecdbb2',x,1.6,b.depth/2+.35,g);brace.rotation.z=x<0?-.52:.52;}}
 if(b.id==='general'){const tire=mesh(new THREE.TorusGeometry(.42,.065,6,16),'#465951',-2,.65,b.depth/2+.8,g);box(.6,.08,.08,'#cfad68',-2,1.25,b.depth/2+.8,g);box(.7,.7,.6,'#b49461',2,.6,b.depth/2+.8,g)}
 if(b.id==='clothing'){box(.9,1.1,.12,'#b5739a',-2,1.6,b.depth/2+.27,g);box(1.25,.27,.14,'#b5739a',-2,2,b.depth/2+.28,g)}
 if(b.id==='post'){box(.55,.9,.5,'#557e89',2,.65,b.depth/2+.9,g);box(.4,.07,.05,'#f6e6b8',2,.94,b.depth/2+1.17,g)}
 if(b.id==='cafe'){for(const x of [-2.5,2.5]){cylinder(.6,.1,'#c3a478',x,.9,b.depth/2+1.3,g);cylinder(.08,.65,'#7f7358',x,.5,b.depth/2+1.3,g)}}
}
// Market stalls and a public noticeboard form the south edge of the square.
for(let j=0;j<stalls.length;j++){const g=new THREE.Group();g.position.set(stalls[j].x,0,stalls[j].z);g.rotation.y=stalls[j].rotation*Math.PI/180;staticRoot.add(g);const x=0,z=0;box(2.3,1.05,1.3,'#b48d5a',x,.7,z,g);for(const dx of [-1.13,1.13])for(const dz of [-.63,.63])box(.1,2.5,.1,'#8e7351',x+dx,1.5,z+dz,g);for(let k=0;k<6;k++){box(.46,.12,2.15,k%2?'#fff0ce':['#c27b67','#809a69','#6792ab'][j%3],x-1.15+k*.46,2.55,z,g);box(.46,.26,.09,k%2?'#fff0ce':['#c27b67','#809a69','#6792ab'][j%3],x-1.15+k*.46,2.32,z+1.04,g)}for(let k=0;k<8;k++)ball(.15,['#dd8c5b','#d1b955','#8d9d54'][j%3],x-.85+k*.23,1.34,z,g)}
cylinder(1.5,6,'#e4d5ae',WINDMILL.x,3.1,WINDMILL.z,undefined,.95);roof(3.5,3.3,2.2,'#7b8a69',WINDMILL.x,6.1,WINDMILL.z);const windmill=new THREE.Group();windmill.position.set(WINDMILL.x,5.65,WINDMILL.z+1.7);scene.add(windmill);for(let k=0;k<4;k++){const sail=new THREE.Group();sail.rotation.z=k*Math.PI/2;windmill.add(sail);box(.13,3.3,.12,'#8f7551',0,1.7,0,sail);box(.72,2.3,.08,'#f1e3bd',.22,2.1,.02,sail)}ball(.24,'#b3a17a',WINDMILL.x,5.65,WINDMILL.z+1.88);
farmScenery({box,ball,cylinder,roof},farmIsOpen(planning));
conceptScenery({box,ball,cylinder,roof,tree,bench,flower},{north:planning.territories.includes('north'),east:planning.territories.includes('east')});staticRoot.add(charterScenery({box,ball,cylinder,roof,bench,flower},planning));
// Shared gardens have open paths, timber beds, and places for neighbors to sit.
for(const area of GARDEN_AREAS){
 box(area.width,.06,area.depth,'#84a767',area.x,.17,area.z);
 box(area.width-.4,.035,1,'#d6c49a',area.x,.22,area.z);
 box(.8,.035,area.depth-.4,'#d6c49a',area.x,.22,area.z);
 fence(area.x-area.width/2,area.z-area.depth/2,area.width);
 bench(area.x+area.width/2-1,area.z+area.depth/2-.8);
 for(const t of WORK_TARGETS.filter(t=>t.id.startsWith(`${area.id}-bed-`))){
  for(const dz of [-.5,.5])box(1.5,.22,.12,'#a98054',t.x,.24,t.z+dz);
  for(const dx of [-.72,.72])box(.12,.22,1,'#b18b5d',t.x+dx,.24,t.z);
 }
}
// Merge static props by material to keep the village comfortable on phones.
staticRoot.updateMatrixWorld(true);const batches=new Map<THREE.Material,THREE.BufferGeometry[]>();staticRoot.traverse(o=>{if(o instanceof THREE.Mesh){const g=(o.geometry.index?o.geometry.toNonIndexed():o.geometry.clone()).applyMatrix4(o.matrixWorld);const m=o.material as THREE.Material;if(!batches.has(m))batches.set(m,[]);batches.get(m)!.push(g);o.geometry.dispose()}});scene.remove(staticRoot);for(const [m,gs]of batches){const g=mergeGeometries(gs,false);if(g){const merged=new THREE.Mesh(g,m);merged.castShadow=true;merged.receiveShadow=true;scene.add(merged)}gs.forEach(g=>g.dispose())}
// Individual household deliveries, litter and thirsty beds replace abstract work sites.
const taskObjects=new Map<string,THREE.Group>();const hitMaterial=new THREE.MeshBasicMaterial({transparent:true,opacity:0,depthWrite:false,colorWrite:false});
function newspaper(parent:THREE.Object3D){const group=new THREE.Group();parent.add(group);box(.48,.09,.29,'#fff1cd',0,0,0,group);box(.46,.018,.26,'#faf6de',0,.05,0,group);box(.055,.11,.3,'#6e9780',0,0,0,group);for(let i=0;i<3;i++)box(.12,.006,.015,'#9caa92',.13,.064,-.065+i*.04,group);return group;}
for(const t of WORK_TARGETS){const g=new THREE.Group();g.position.set(t.x,0,t.z);g.userData.task=t.id;scene.add(g);taskObjects.set(t.id,g);
 const result=new THREE.Group();g.add(result);g.userData.result=result;
 if(t.job==='paper'){const paper=newspaper(result),landing=paperDestination(HOMES[t.home!]).porch;paper.position.set(landing.x-t.x,landing.y,landing.z-t.z);paper.rotation.y=.25;}
 else if(t.job==='deliver'){box(.55,.45,.48,'#c29665',.3,.655,-.5,result);box(.08,.47,.5,'#efd19c',.3,.655,-.5,result)}
 else if(t.job==='clean'){const kind=t.id.length%3;if(kind===0){const bottle=cylinder(.1,.4,'#8ab9a6',0,.31,0,result,.05);bottle.rotation.z=1.1}else if(kind===1){const paper=box(.34,.05,.24,'#f0dcae',0,.23,0,result);paper.rotation.y=1.3;ball(.08,'#ceb789',.06,.3,.02,result)}else{const can=cylinder(.12,.25,'#9bafbb',0,.29,0,result);can.rotation.z=.8;}}
 else {g.userData.soil=box(1.3,.12,.85,'#ba996d',0,.22,0,g);const foliage=new THREE.Group();g.add(foliage);g.userData.foliage=foliage;for(let j=0;j<5;j++)flower(-.48+j*.24,(j%2-.5)*.24,'#bfa879',foliage);}
 const marker=mesh(new THREE.OctahedronGeometry(.14),'#f2cf70',0,t.kind==='mailbox'?1.65:1.1,0,g);g.userData.marker=marker;
 const hit=new THREE.Mesh(new THREE.BoxGeometry(t.job==='garden'?1.3:.8,1.3,.9),hitMaterial);hit.position.y=.6;g.add(hit);
}
for(const station of STATIONS){const g=new THREE.Group();g.position.set(station.x,0,station.z);g.userData.task=station.id;scene.add(g);taskObjects.set(station.id,g);if(station.id==='supplies'){box(1.4,.7,.85,'#b18b5e',0,.55,0,g);for(let j=0;j<4;j++)box(.45,.06,.3,'#fff0ce',-.35,.94+j*.065,0,g);box(.45,.4,.45,'#bd9567',.4,1.05,0,g)}else if(station.id==='recycling'){cylinder(.28,.7,'#5d8b72',-.32,.55,0,g);cylinder(.28,.7,'#789ca6',.32,.55,0,g);box(1.4,.05,.85,'#c8b88f',0,.18,0,g)}else{cylinder(.17,.6,'#799b96',0,.5,0,g);box(.55,.1,.14,'#8fb3ac',0,.85,0,g)}g.userData.marker=mesh(new THREE.OctahedronGeometry(.16),'#f3cd6b',0,1.6,0,g);}
for(const b of buildings){const g=new THREE.Group();const door=entrance(b);g.position.set(door.x,0,door.z);g.userData.task=b.id;const hit=new THREE.Mesh(new THREE.BoxGeometry(2.5,2,1.7),hitMaterial);hit.position.y=1;g.add(hit);scene.add(g);taskObjects.set(b.id,g)}
for(const f of [...(planning.territories.includes('island')?FERRY_STOPS:[]),FARM_GATE,PICNIC,...(farmIsOpen(planning)?[FARM_ORDER,...FARM_BEDS]:[])]){const g=new THREE.Group();g.position.set(f.x,0,f.z);g.userData.task=f.id;g.add(new THREE.Mesh(new THREE.BoxGeometry(2.5,2,2),hitMaterial));scene.add(g);taskObjects.set(f.id,g);}
const houseHits:THREE.Mesh[]=[];
for(const h of HOMES){const level=houseById(live.current.properties?.find(p=>p.home===h.id)?.house).level,height=4.7+Math.floor((level-1)/2)*1.35;const hit=new THREE.Mesh(new THREE.BoxGeometry(5.7,height,4.7),hitMaterial);hit.position.set(h.x,height/2,h.z);hit.userData.home=h.id;scene.add(hit);houseHits.push(hit);
 if(true){const door=homeDoor(h),g=new THREE.Group();g.position.set(door.x,0,door.z-.7);g.userData.task=`home-door-${h.id}`;const hit=new THREE.Mesh(new THREE.BoxGeometry(1.2,1.9,.6),hitMaterial);hit.position.y=1;g.add(hit);scene.add(g);taskObjects.set(g.userData.task,g);}}
const identity=document.createElement('div');identity.className='house-identity';identity.setAttribute('role','status');const identityName=document.createElement('strong'),identityAddress=document.createElement('small');identity.appendChild(identityName);identity.appendChild(identityAddress);el.appendChild(identity);let inspectedHome:number|null=null,identityUntil=0;
const identityRing=new THREE.Mesh(new THREE.RingGeometry(3.3,3.38,4),new THREE.MeshBasicMaterial({color:'#f4d28d',transparent:true,opacity:.8,side:THREE.DoubleSide,depthWrite:false}));identityRing.rotation.set(-Math.PI/2,0,Math.PI/4);identityRing.scale.set(1.22,.99,1);identityRing.visible=false;scene.add(identityRing);
function inspectHouse(id:number|null,mobile=false){inspectedHome=id;identityUntil=mobile?Date.now()+5500:Infinity;}
const actionParticle=new THREE.Group();scene.add(actionParticle);const flyingPaper=box(.4,.08,.24,'#fff0ce',0,0,0,actionParticle),flyingParcel=box(.55,.45,.48,'#c49a66',0,0,0,actionParticle);const flyingTrash=ball(.14,'#8dafa0',0,0,0,actionParticle);box(.12,.04,.12,'#d6dbbd',0,.12,0,flyingTrash);box(.06,.47,.5,'#ecd0a0',0,0,0,flyingParcel);actionParticle.visible=false;let lastReward=0,flightStart=0,flightTarget=new THREE.Vector3(),flightOrigin=new THREE.Vector3(),flightJob='';
type PaperFlight={event:PaperThrow;home:typeof HOMES[number];group:THREE.Group;paper:THREE.Group;ring:THREE.Mesh;ringMaterial:THREE.MeshBasicMaterial;sparkles:THREE.Group;label:HTMLDivElement;origin:THREE.Vector3;released:boolean;impacted:boolean;celebratedAt:number};
const paperFlights=new Map<number,PaperFlight>();
function discardPaper(f:PaperFlight){scene.remove(f.group);f.group.traverse(o=>{if(o instanceof THREE.Mesh)o.geometry.dispose()});f.ringMaterial.dispose();f.label.remove();paperFlights.delete(f.event.id);}
function newPaperFlight(event:PaperThrow){const t=TARGET_BY_ID.get(event.target),home=t?.home===undefined?undefined:HOMES[t.home];if(!home)return;
 const group=new THREE.Group();scene.add(group);const paper=newspaper(group),ringMaterial=new THREE.MeshBasicMaterial({color:'#ffe6a1',side:THREE.DoubleSide,transparent:true,opacity:0,depthWrite:false}),ring=new THREE.Mesh(new THREE.RingGeometry(.15,.19,20),ringMaterial);group.add(ring);const door=paperDestination(home).door;ring.position.set(door.x,door.y,door.z+.06);
 const sparkles=new THREE.Group();group.add(sparkles);for(let i=0;i<7;i++)ball(.055,i%2?'#ffe3a0':'#fff5d1',0,0,0,sparkles);sparkles.visible=false;
 const label=document.createElement('div');label.className='paper-delivery-reward';label.setAttribute('aria-hidden','true');label.style.display='none';el.appendChild(label);
 const flight:PaperFlight={event,home,group,paper,ring,ringMaterial,sparkles,label,origin:new THREE.Vector3(event.origin.x,1.35,event.origin.z),released:false,impacted:false,celebratedAt:0};paperFlights.set(event.id,flight);
}
const waterDrops=new THREE.InstancedMesh(new THREE.SphereGeometry(.045,4,3),mat('#8dd4df'),16);scene.add(waterDrops);waterDrops.visible=false;const waterMatrix=new THREE.Object3D();
// Low draw-call lawn tiles and tall blades; short alternating stripes remain behind.
const lawnCells=LAWN_CELLS.filter(c=>!worldBlocked(c.x,c.z));
const grassBase=new THREE.InstancedMesh(new THREE.BoxGeometry(1,.035,1),mat('#8fba5d'),lawnCells.length);
const grassTall=new THREE.InstancedMesh(new THREE.ConeGeometry(.12,.53,3),mat('#507d36'),lawnCells.length*3);
grassBase.receiveShadow=true;grassTall.castShadow=false;grassTall.frustumCulled=false;scene.add(grassBase,grassTall);
const grassMatrix=new THREE.Object3D();const grass=grassState.current.tracker;grass.merge(live.current.grassHistory??[]);let previousCuts=grass.cuts(Date.now()),grassRevision=grass.revision,nextRegrowth=grass.nextRegrowth(Date.now());const grassIndices=new Map(lawnCells.map((c,i)=>[c.id,i]));
lawnCells.forEach((c,i)=>{grassMatrix.position.set(c.x,.215,c.z);grassMatrix.scale.set(c.size-.01,1,c.size-.01);grassMatrix.updateMatrix();grassBase.setMatrixAt(i,grassMatrix.matrix);grassBase.setColorAt(i,new THREE.Color(c.row%2?'#9cbe6a':'#85ad55'))});
let grassHistoryRef=live.current.grassHistory,grassMinute=-1;
function setGrassCut(i:number,cut:boolean){const c=lawnCells[i],height=cut?0:grassHeight(grass.cutAt(c.id),Date.now(),live.current.townCreated??Date.now());for(let j=0;j<3;j++){grassMatrix.position.set(c.x+(j-1)*.19,.215+.265*height,c.z+(j%2?-.15:.15));grassMatrix.scale.set(cut?0:1,height,cut?0:1);grassMatrix.rotation.set(0,i+j*2,0);grassMatrix.updateMatrix();grassTall.setMatrixAt(i*3+j,grassMatrix.matrix)}}
lawnCells.forEach((c,i)=>setGrassCut(i,previousCuts.has(c.id)));grassTall.instanceMatrix.needsUpdate=true;
// A small burst of clippings follows the cutting deck as it crosses new grass.
const clippings=new THREE.InstancedMesh(new THREE.BoxGeometry(.055,.06,.14),mat('#7fa84c'),18);scene.add(clippings);clippings.visible=false;let clippingUntil=0;
const parkUpgrade=new THREE.Group();parkUpgrade.position.set(COMMUNITY_PARK.x+16,0,5);scene.add(parkUpgrade);bench(-17,0,parkUpgrade);bench(-15,0,parkUpgrade);for(let i=0;i<12;i++)flower(-18+i*.35,-1.8,'#efb3bd',parkUpgrade);parkUpgrade.visible=false;
const civicArt=civicScenery({box,ball,cylinder,roof,bench,flower});
// Merge each upgrade independently so visibility changes do not rebuild the town.
for(const group of civicArt.groups.values()){
 group.updateMatrixWorld(true);const parts=new Map<THREE.Material,THREE.BufferGeometry[]>();
 group.traverse(o=>{if(o instanceof THREE.Mesh){const geometry=(o.geometry.index?o.geometry.toNonIndexed():o.geometry.clone()).applyMatrix4(o.matrixWorld);const material=o.material as THREE.Material;if(!parts.has(material))parts.set(material,[]);parts.get(material)!.push(geometry);o.geometry.dispose()}});
 group.clear();for(const [material,geometries]of parts){const geometry=mergeGeometries(geometries,false);if(geometry){const m=new THREE.Mesh(geometry,material);m.castShadow=true;m.receiveShadow=true;group.add(m)}geometries.forEach(g=>g.dispose())}scene.add(group);
}
scene.add(civicArt.construction);let civicKey='';
const editorRoot=new THREE.Group(),ghostRoot=new THREE.Group();scene.add(editorRoot,ghostRoot);editorRoot.visible=false;let ghostKey='',wasEditing=false;
const gridMaterial=new THREE.LineBasicMaterial({color:'#315c59',transparent:true,opacity:.27,depthWrite:false});const points:number[]=[];
for(const area of layout.bounds){const x0=area.x-area.width/2,x1=area.x+area.width/2,z0=area.z-area.depth/2,z1=area.z+area.depth/2;for(let x=Math.ceil(x0);x<=x1;x++)points.push(x,.31,z0,x,.31,z1);for(let z=Math.ceil(z0);z<=z1;z++)points.push(x0,.31,z,x1,.31,z);}
const gridGeometry=new THREE.BufferGeometry();gridGeometry.setAttribute('position',new THREE.Float32BufferAttribute(points,3));editorRoot.add(new THREE.LineSegments(gridGeometry,gridMaterial));
const reservedMaterial=new THREE.MeshBasicMaterial({color:'#c26f5d',transparent:true,opacity:.12,depthWrite:false});for(const r of protectedLand(planning)){const m=new THREE.Mesh(new THREE.PlaneGeometry(r.width,r.depth),reservedMaterial);m.rotation.x=-Math.PI/2;m.position.set(r.x,.32,r.z);editorRoot.add(m);}
const planOutline=new THREE.Group(),planSign=new THREE.Group();scene.add(planOutline,planSign);let planKey='';

const decorations=new THREE.Group();scene.add(decorations);let decorationKey='';
function avatar(color:string){const g=new THREE.Group();const legs=[box(.18,.4,.23,'#4e5b62',-.16,.43,0,g),box(.18,.4,.23,'#4e5b62',.16,.43,0,g)];box(.23,.12,.34,'#775f47',-.16,.18,.06,g);box(.23,.12,.34,'#775f47',.16,.18,.06,g);const shirt=cylinder(.3,.48,color,0,.88,0,g,.27);const arms=[box(.16,.46,.2,color,-.35,.88,0,g),box(.16,.46,.2,color,.35,.88,0,g)];ball(.29,'#e5b994',0,1.42,0,g);const hair=ball(.31,'#75553c',0,1.55,-.035,g);hair.scale.y=.65;for(const x of [-.105,.105])box(.04,.055,.025,'#35443a',x,1.44,.27,g);const rider=g.children.map(o=>({o,y:o.position.y,z:o.position.z}));
const mower=new THREE.Group();g.add(mower);mower.visible=false;
box(1.15,.16,1.65,'#476d40',0,.33,.1,mower);box(.9,.44,.8,'#ba5140',0,.62,.65,mower);box(.95,.1,.88,'#d76a4c',0,.87,.65,mower);box(.6,.12,.46,'#35463d',0,.85,-.3,mower);box(.6,.42,.12,'#35463d',0,1.04,-.55,mower);
box(.12,.55,.12,'#4b5c4c',0,1,.18,mower);const steering=mesh(new THREE.TorusGeometry(.23,.035,6,12),'#35443b',0,1.28,.18,mower);steering.rotation.x=Math.PI/3;
const wheels:THREE.Mesh[]=[];for(const x of [-.59,.59])for(const z of [-.5,.65]){const w=cylinder(.28,.18,'#34423a',x,.36,z,mower);w.rotation.z=Math.PI/2;wheels.push(w);}
const bike=new THREE.Group();g.add(bike);bike.visible=false;const bikeWheels:THREE.Group[]=[];
for(const z of [-.7,.7]){const wheel=new THREE.Group();wheel.position.set(0,.43,z);bike.add(wheel);bikeWheels.push(wheel);const tire=mesh(new THREE.TorusGeometry(.35,.055,6,16),'#3d4c46',0,0,0,wheel);tire.rotation.y=Math.PI/2;for(let i=0;i<4;i++){const spoke=box(.025,.66,.025,'#bfc8ad',0,0,0,wheel);spoke.rotation.x=i*Math.PI/4;}}
function frameBar(a:THREE.Vector3,b:THREE.Vector3){const bar=mesh(new THREE.CylinderGeometry(.045,.045,a.distanceTo(b),6),'#7aa5a0',0,0,0,bike);bar.position.copy(a).add(b).multiplyScalar(.5);bar.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),b.clone().sub(a).normalize())}
for(const [a,b]of [[[-.02,.43,-.7],[0,.9,-.2]],[[0,.9,-.2],[0,.43,0]],[[0,.43,0],[0,.43,-.7]],[[0,.9,-.2],[0,.95,.48]],[[0,.43,0],[0,.95,.48]],[[0,.43,.7],[0,1.17,.48]]])frameBar(new THREE.Vector3(...a),new THREE.Vector3(...b));
box(.42,.11,.3,'#756044',0,.98,-.2,bike);box(.6,.07,.07,'#65766b',0,1.18,.5,bike);box(.65,.28,.45,'#bca476',0,1.08,.85,bike);const basketPapers=box(.48,.15,.3,'#fff0d1',0,1.27,.85,bike);
const cart=new THREE.Group();g.add(cart);cart.visible=false;box(1.05,.15,1.05,'#759087',0,.46,-1.4,cart);for(const x of [-.53,.53]){const wheel=cylinder(.27,.13,'#3f4d43',x,.37,-1.4,cart);wheel.rotation.z=Math.PI/2;box(.06,.07,1.2,'#7e8a76',x, .75,-.85,cart)}const cartLoad=new THREE.Group();cart.add(cartLoad);for(let i=0;i<3;i++){box(.43,.4,.42,'#bf9466',(i%2-.5)*.48,.72+Math.floor(i/2)*.42,-1.4,cartLoad);box(.055,.42,.44,'#e8c487',(i%2-.5)*.48,.72+Math.floor(i/2)*.42,-1.4,cartLoad)}
const tool=new THREE.Group();g.add(tool);tool.visible=false;
const tools:Record<string,THREE.Group>={};for(const id of ['clean','garden','paper','deliver']){const held=new THREE.Group();tool.add(held);tools[id]=held;held.visible=false;}
box(.07,1,.07,'#b68a57',.47,.72,.35,tools.clean);box(.17,.09,.13,'#819183',.47,.28,.35,tools.clean);const rubbishBag=ball(.3,'#567064',-.45,.64,-.2,tools.clean);rubbishBag.scale.y=1.25;
cylinder(.19,.3,'#79a9b2',.47,.85,.3,tools.garden);const spout=box(.38,.08,.08,'#8cb8bd',.68,.9,.3,tools.garden);spout.rotation.z=.3;
box(.5,.09,.3,'#fff2cf',.3,.85,.43,tools.paper);box(.05,.1,.32,'#70967a',.3,.85,.43,tools.paper);
box(.5,.4,.4,'#bd925f',0,.9,.5,tools.deliver);box(.07,.42,.42,'#efcc85',0,.9,.5,tools.deliver);
g.userData={legs,arms,shirt,color,rider,mower,wheels,tool,tools,bike,bikeWheels,basketPapers,cart,cartLoad};scene.add(g);return g}
let you=avatar(live.current.player?.color??'#688aa1');you.position.set(live.current.player?.x??0,0,live.current.player?.z??5.8);const people=new Map<string,THREE.Group>();
const otherLabels=new Map<string,HTMLDivElement>();function label(id:string,text:string,g:THREE.Group){let l=otherLabels.get(id);if(!l){l=document.createElement('div');l.className='world-label';otherLabels.set(id,l);el.appendChild(l)}const v=g.position.clone().add(new THREE.Vector3(0,2.1,0)).project(camera);l.textContent=text;l.style.left=`${(v.x+1)*el.clientWidth/2}px`;l.style.top=`${(-v.y+1)*el.clientHeight/2}px`;l.style.display=viewHeight<85&&Math.abs(v.x)<1.05&&Math.abs(v.y)<1.05?'block':'none'}
// Screen-facing marker stays unmistakable at any camera angle or zoom.
const homeMarker=document.createElement('div');homeMarker.className='selected-home-marker';homeMarker.style.display='none';homeMarker.setAttribute('aria-hidden','true');
const homeMarkerName=document.createElement('span');homeMarker.appendChild(homeMarkerName);
const arrow=document.createElementNS('http://www.w3.org/2000/svg','svg');arrow.setAttribute('viewBox','0 0 48 60');arrow.setAttribute('width','48');arrow.setAttribute('height','60');
for(const [stroke,width] of [['#fffbed','9'],['#5b5634','4']]){const path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d','M15 5H33V30H43L24 53L5 30H15Z');path.setAttribute('fill','#f4cd63');path.setAttribute('stroke',stroke);path.setAttribute('stroke-width',width);path.setAttribute('stroke-linejoin','round');arrow.appendChild(path);}homeMarker.appendChild(arrow);el.appendChild(homeMarker);
const playerLabel=document.createElement('div');playerLabel.className='world-label you';el.appendChild(playerLabel);
const selection=new THREE.Mesh(new THREE.RingGeometry(2.9,3.04,64),new THREE.MeshBasicMaterial({color:'#fff2b1',side:THREE.DoubleSide,transparent:true,opacity:.85}));selection.rotation.x=-Math.PI/2;selection.position.y=.23;scene.add(selection);selection.visible=false;
const destination=new THREE.Mesh(new THREE.RingGeometry(.22,.3,32),new THREE.MeshBasicMaterial({color:'#fff4c7',side:THREE.DoubleSide}));destination.rotation.x=-Math.PI/2;destination.position.y=.24;scene.add(destination);destination.visible=false;
let navigation=0;let waypoints:{x:number;z:number}[]=[];let walkTo:THREE.Vector3|null=null;const keys=new Set<string>();let currentFocus:[number,number]|null=null;let follow=true,inspecting=false;let frame=0,last=performance.now(),lastNear='';let disposed=false;const plane=new THREE.Plane(new THREE.Vector3(0,1,0),0),raycaster=new THREE.Raycaster();
let movementTrail:{x:number;z:number}[]=[];let lastTrailPoint=you.position.clone();
const api:SceneApi={settleGrass:(sequence,history)=>grass.settle(sequence,history),position:(consume=false)=>{const path=movementTrail;if(consume){movementTrail=[];lastTrailPoint.copy(you.position)}return{x:you.position.x,z:you.position.z,path,cutSequence:grass.movementSequence}},navigate:(x,z)=>{const request=++navigation;void (async()=>{if(live.current.onControl&&!await live.current.onControl())return;if(disposed||request!==navigation)return;inspecting=false;waypoints=findPath({x:you.position.x,z:you.position.z},{x,z},blocked);const first=waypoints.shift();walkTo=first?new THREE.Vector3(first.x,0,first.z):null;follow=true;destination.position.set(x,.24,z);destination.visible=true})();},center:()=>{inspecting=false;follow=true;currentFocus=null;if(viewHeight>60){viewHeight=35;resize()}},lookAt:(x,z)=>{inspecting=true;follow=false;currentFocus=focus.current;selection.visible=false;cameraTarget.set(THREE.MathUtils.clamp(x,-120,116),0,THREE.MathUtils.clamp(z,-99,101))},orbit:(dy,dp=0)=>{yaw+=dy;pitch=clampPitch(pitch+dp)},pan:(dx,dy)=>{if(follow)cameraTarget.copy(target);follow=false;selection.visible=false;const scale=(camera.top-camera.bottom)/Math.max(1,el.clientHeight);const move=screenToGround(-dx*scale,-dy*scale/Math.sin(pitch),yaw);cameraTarget.x=THREE.MathUtils.clamp(cameraTarget.x+move.x,-120,116);cameraTarget.z=THREE.MathUtils.clamp(cameraTarget.z+move.z,-99,101)},overview:()=>{inspecting=true;follow=false;currentFocus=focus.current;selection.visible=false;yaw=DEFAULT_YAW;pitch=DEFAULT_PITCH;viewHeight=Math.max(planning.territories.length?205:118,(planning.territories.length?236:184)*el.clientHeight/el.clientWidth)/(el.clientWidth<700?.85:1);resize();cameraTarget.set(planning.territories.length?0:-28,0,1)},resetCamera:()=>{inspecting=false;yaw=DEFAULT_YAW;pitch=DEFAULT_PITCH;viewHeight=35;resize();follow=true;currentFocus=null},stop:()=>{navigation++;walkTo=null;waypoints=[];keys.clear();destination.visible=false},zoom:(by)=>{viewHeight=THREE.MathUtils.clamp(viewHeight+by,14,260);resize()},setPosition:(x,z)=>{you.position.set(x,0,z);movementTrail=[];lastTrailPoint.copy(you.position);if(!inspecting)follow=true}};live.current.onReady?.(api);
function resize(){const w=el.clientWidth,h=el.clientHeight;renderer.setSize(w,h);const v=w<700?viewHeight*.85:viewHeight;camera.left=-v*w/h/2;camera.right=v*w/h/2;camera.top=v/2;camera.bottom=-v/2;camera.far=Math.max(420,viewHeight*2+200);camera.updateProjectionMatrix()}const observer=new ResizeObserver(resize);observer.observe(el);resize();
const held=new Set<string>();const keyDown=(e:KeyboardEvent)=>{if((e.target as HTMLElement).closest('input,textarea,[contenteditable=true],[role=dialog]'))return;const k=e.key.toLowerCase();if(e.altKey&&k.startsWith('arrow')){e.preventDefault();api.pan(k==='arrowleft'?40:k==='arrowright'?-40:0,k==='arrowup'?40:k==='arrowdown'?-40:0);return}if(k==='q'||k==='r'){e.preventDefault();api.orbit(k==='q'?-.16:.16);return}if(k===' '&&live.current.enabled&&live.current.player?.shift==='paper'&&live.current.onPaperAction){e.preventDefault();if(!e.repeat&&!live.current.working)live.current.onPaperAction();return}if(k===' '&&(e.target as HTMLElement).closest('button'))return;if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright','e',' '].includes(k)){e.preventDefault();if(k==='e'||k===' '){live.current.onAction?.();return;}if(e.repeat)return;held.add(k);if(live.current.controlling!==false)keys.add(k);live.current.onManualMove?.();void (async()=>{if(live.current.onControl&&!await live.current.onControl())return;if(!disposed&&held.has(k))keys.add(k);})()}};const keyUp=(e:KeyboardEvent)=>{held.delete(e.key.toLowerCase());keys.delete(e.key.toLowerCase())};const blur=()=>{held.clear();keys.clear()};window.addEventListener('keydown',keyDown);window.addEventListener('keyup',keyUp);window.addEventListener('blur',blur);
const removeCameraGestures=installCameraGestures(renderer.domElement,{mode:()=>live.current.cameraMode??'pan',viewHeight:()=>viewHeight,pan:api.pan,orbit:api.orbit,zoom:api.zoom,tap:(e)=>{const r=el.getBoundingClientRect();raycaster.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);if(live.current.placement){const point=new THREE.Vector3();if(raycaster.ray.intersectPlane(plane,point))live.current.onPlacementChange?.({...live.current.placement.value,x:Math.round(point.x),z:Math.round(point.z)});return;}const hits=raycaster.intersectObjects([...taskObjects.entries()].filter(([id])=>{const t=TARGET_BY_ID.get(id);return t?t.job===live.current.player?.shift&&!(live.current.worldWork??[]).some(w=>w.id===t.group):(id.startsWith('home-door-')&&(live.current.properties??[]).some(p=>p.home===Number(id.slice(10)))&&!live.current.player?.shift&&!live.current.player?.mowing)||(!!lifeTarget(id)&&!live.current.player?.shift&&!live.current.player?.mowing)||buildings.some(b=>b.id===id)||id===FARM_GATE.id||FERRY_STOPS.some(f=>f.id===id)||STATIONS.some(s=>s.id===id&&s.jobs.includes(live.current.player?.shift??''))}).map(([,g])=>g),true).filter(hit=>{let o:THREE.Object3D|null=hit.object;while(o){if(!o.visible)return false;o=o.parent}return true});if(live.current.enabled&&hits.length){let o:THREE.Object3D|null=hits[0].object;while(o&&!o.userData.task)o=o.parent;if(o?.userData.task){live.current.onSelectTask?.(o.userData.task);return}}const homeHit=raycaster.intersectObjects(houseHits)[0];if(live.current.enabled&&homeHit){inspectHouse(homeHit.object.userData.home,true);return;}const p=new THREE.Vector3();if(raycaster.ray.intersectPlane(plane,p)){if(!live.current.enabled){const home=HOMES.find(h=>Math.abs(h.x-p.x)<3&&Math.abs(h.z-p.z)<3);if(home)live.current.onSelectHome?.(home.id);return}inspectHouse(null);live.current.onManualMove?.();api.navigate(THREE.MathUtils.clamp(p.x,-116,112),THREE.MathUtils.clamp(p.z,-96,98))}}});
const hoverHouse=(e:PointerEvent)=>{if(e.pointerType!=='mouse')return;if(e.buttons||!live.current.enabled||live.current.placement){inspectHouse(null);return;}const rect=el.getBoundingClientRect();raycaster.setFromCamera(new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),camera);const hit=raycaster.intersectObjects(houseHits)[0];inspectHouse(hit?hit.object.userData.home:null);};const leaveHouse=()=>inspectHouse(null);renderer.domElement.addEventListener('pointermove',hoverHouse);renderer.domElement.addEventListener('pointerleave',leaveHouse);
const wheel=(e:WheelEvent)=>{e.preventDefault();api.zoom(e.deltaY*.012)};renderer.domElement.addEventListener('wheel',wheel,{passive:false});
const blocked=worldBlocked;
function mount(g:THREE.Group,mowing:boolean,moving:boolean,now:number,person?:Props['player']|Peer){const biking=person?.shift==='paper'||!!person?.riding;g.userData.mower.visible=mowing;g.userData.bike.visible=biking;g.userData.basketPapers.visible=person?.shift==='paper'&&(person?.papers??0)>0;g.userData.cart.visible=person?.shift==='deliver';g.userData.cartLoad.visible=(person?.parcels??0)>0;for(const {o,y,z} of g.userData.rider){o.position.y=y+(mowing?.45:biking?.25:0);o.position.z=z-(mowing?.32:0)}if(mowing||biking){g.userData.legs.forEach((l:THREE.Mesh,i:number)=>l.rotation.x=biking&&moving?Math.sin(now*.014+i*Math.PI)*.7:-1);g.userData.arms.forEach((l:THREE.Mesh)=>l.rotation.x=-.7);if(biking&&moving)g.userData.bikeWheels.forEach((w:THREE.Group)=>w.rotation.x=now*.014);if(moving)g.userData.wheels.forEach((w:THREE.Mesh)=>w.rotation.x=now*.012)}g.userData.tool.visible=!!person?.shift&&!mowing;for(const [id,tool]of Object.entries(g.userData.tools) as [string,THREE.Group][])tool.visible=id===person?.shift&&id!=='paper'&&id!=='deliver';}
const pets=townPets(scene,reducedMotion);const lifeArt=sharedLifeScenery(scene,farmIsOpen(planning),reducedMotion);
function animate(now:number){if(disposed)return;frame=requestAnimationFrame(animate);const dt=Math.min((now-last)/1000,.04);last=now;const p=live.current;if(focus.current!==currentFocus&&focus.current){currentFocus=focus.current;follow=false;cameraTarget.set(currentFocus[0],0,currentFocus[1]+(el.clientWidth<700?7:0));selection.position.set(currentFocus[0],.23,currentFocus[1]);selection.visible=true;}
if(p.player&&you.userData.color!==p.player.color){you.userData.color=p.player.color;you.userData.shirt.material=mat(p.player.color);you.userData.arms.forEach((arm:THREE.Mesh)=>arm.material=mat(p.player!.color))}
if(p.player)dressAvatar(you,p.player,mat);
if(p.controlling===false&&p.player){you.position.x+=(p.player.x-you.position.x)*Math.min(1,dt*10);you.position.z+=(p.player.z-you.position.z)*Math.min(1,dt*10);movementTrail=[];lastTrailPoint.copy(you.position);}
const beforeMove=you.position.clone();let vx=0,vz=0;const sx=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0)+(p.stick?.x??0);const sy=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0)+(p.stick?.y??0);
if(p.enabled&&p.controlling!==false){if(Math.abs(sx)+Math.abs(sy)>.08){const direction=screenToGround(sx,sy,yaw);vx=direction.x;vz=direction.z;walkTo=null;waypoints=[];if(!inspecting)follow=true;selection.visible=false;}else if(walkTo){vx=walkTo.x-you.position.x;vz=walkTo.z-you.position.z;if(Math.hypot(vx,vz)<.18){const next=waypoints.shift();walkTo=next?new THREE.Vector3(next.x,0,next.z):null;destination.visible=!!next;vx=0;vz=0}}const len=Math.hypot(vx,vz);if(len>.08&&!p.working){const speed=p.player?.mowing?3.2:p.player?.shift==='paper'?5:p.player?.shift==='deliver'?3:p.player?.riding?5:3.4;const dx=vx/len*speed*dt,dz=vz/len*speed*dt;const oldx=you.position.x,oldz=you.position.z;if(!blocked(you.position.x+dx,you.position.z))you.position.x=THREE.MathUtils.clamp(you.position.x+dx,-116,112);if(!blocked(you.position.x,you.position.z+dz))you.position.z=THREE.MathUtils.clamp(you.position.z+dz,-96,98);if(walkTo&&Math.abs(oldx-you.position.x)+Math.abs(oldz-you.position.z)<.001){walkTo=null;destination.visible=false}you.rotation.y=Math.atan2(vx,vz);you.position.y=Math.sin(now*.016)*.055;}else you.position.y=0;you.userData.legs.forEach((l:THREE.Mesh,i:number)=>l.rotation.x=len>.08?Math.sin(now*.015+i*Math.PI)*.4:0);you.userData.arms.forEach((l:THREE.Mesh,i:number)=>l.rotation.x=p.working?Math.sin(now*.018+i)*.7:len>.08?Math.sin(now*.015-i*Math.PI)*.3:0)}
you.position.y=groundHeight(you.position.x,you.position.z)+(p.enabled&&Math.hypot(vx,vz)>.08&&!p.working?Math.sin(now*.016)*.055:0);
if(you.position.distanceTo(lastTrailPoint)>.22){movementTrail.push({x:you.position.x,z:you.position.z});if(movementTrail.length>32)movementTrail.shift();lastTrailPoint.copy(you.position)}
mount(you,!!p.player?.mowing,Math.hypot(vx,vz)>.08,now,p.player);you.userData.tool.rotation.x=p.working?Math.sin(now*.012)*.3:0;
const watering=TARGET_BY_ID.get(p.player?.wateringTarget??'');waterDrops.visible=!!watering;
if(watering){you.rotation.y=Math.atan2(watering.x-you.position.x,watering.z-you.position.z);you.userData.tools.garden.rotation.z=-.35;for(let i=0;i<16;i++){const phase=(now*.0012+i/16)%1;waterMatrix.position.set(THREE.MathUtils.lerp(you.position.x,watering.x,phase),THREE.MathUtils.lerp(1.05,.25,phase)+Math.sin(phase*Math.PI)*.45,THREE.MathUtils.lerp(you.position.z,watering.z,phase));waterMatrix.scale.setScalar(1);waterMatrix.updateMatrix();waterDrops.setMatrixAt(i,waterMatrix.matrix)}waterDrops.instanceMatrix.needsUpdate=true}else you.userData.tools.garden.rotation.z=0;
if(p.rewardFx&&p.rewardFx.at!==lastReward){lastReward=p.rewardFx.at;const t=TARGET_BY_ID.get(p.rewardFx.target);if(t){flightStart=now;flightJob=t.job;flightOrigin.set(you.position.x,1,you.position.z);flightTarget.set(t.x+(t.job==='deliver'?.3:0),.35,t.z-(t.job==='deliver'?.5:0));you.rotation.y=Math.atan2(t.x-you.position.x,t.z-you.position.z);}}
const animTarget=p.rewardFx?TARGET_BY_ID.get(p.rewardFx.target):null,pose=fieldPose(flightJob,now-flightStart,flightOrigin,flightTarget,reducedMotion);actionParticle.visible=!!p.rewardFx&&flightStart>0&&!pose.done&&(flightJob==='deliver'||flightJob==='clean');you.rotation.x=actionParticle.visible?pose.bend:0;
if(actionParticle.visible){actionParticle.position.set(pose.x,pose.y,pose.z);actionParticle.rotation.set(0,pose.rotation,pose.rotation*.3);actionParticle.scale.setScalar(pose.scale);flyingPaper.visible=false;flyingParcel.visible=flightJob==='deliver';flyingTrash.visible=flightJob==='clean';you.userData.arms.forEach((arm:THREE.Mesh)=>arm.rotation.x=-Math.sin(Math.min(1,(now-flightStart)/700)*Math.PI)*.85);}
// Separate flights let a rider throw to the next home while the previous paper settles.
const wallTime=Date.now(),incoming=new Map((p.paperThrows??[]).map(event=>[event.id,event]));for(const event of incoming.values()){const existing=paperFlights.get(event.id);if(existing)existing.event=event;else newPaperFlight(event);}
for(const f of [...paperFlights.values()]){
 if(!incoming.has(f.event.id)&&!f.celebratedAt){discardPaper(f);continue;}
 const elapsed=wallTime-f.event.at;
 if(!f.released){you.updateMatrixWorld(true);const hand=you.localToWorld(new THREE.Vector3(.42,1.16,.3));f.origin.copy(hand);if(elapsed>=PAPER_TIMING.release||reducedMotion){f.released=true;p.onPaperSound?.('release');}}
 const pose=paperPose(elapsed,f.origin,f.home,reducedMotion);f.paper.position.set(pose.position.x,pose.position.y,pose.position.z);f.paper.rotation.set(pose.rotation.x,pose.rotation.y,pose.rotation.z);f.paper.scale.set(pose.scale.x,pose.scale.y,pose.scale.z);
 if(elapsed<240&&!reducedMotion){const flick=Math.sin(Math.min(1,elapsed/240)*Math.PI);you.userData.arms[1].rotation.z=-flick*1.45;you.userData.arms[1].rotation.x=-flick*.55;}
 if(!reducedMotion&&elapsed>=PAPER_TIMING.impact&&!f.impacted){f.impacted=true;p.onPaperSound?.('impact');}
 const impactAge=elapsed-PAPER_TIMING.impact;f.ring.visible=!reducedMotion&&impactAge>=0&&impactAge<170;f.ring.scale.setScalar(1+Math.max(0,impactAge)/130);f.ringMaterial.opacity=Math.max(0,1-impactAge/170)*.75;
 if(pose.landed&&f.event.confirmed&&!f.celebratedAt){f.celebratedAt=wallTime;p.onPaperLanded?.(f.event);}
 if(f.celebratedAt){const age=wallTime-f.celebratedAt,progress=Math.min(1,age/700),landing=paperDestination(f.home).porch;f.paper.visible=false;f.sparkles.visible=!reducedMotion&&age<500;
  f.sparkles.children.forEach((o,i)=>{const angle=i*Math.PI*2/7;o.position.set(landing.x+Math.cos(angle)*progress*.65,landing.y+.12+Math.sin(progress*Math.PI)*.45,landing.z+Math.sin(angle)*progress*.4);o.scale.setScalar(1-progress);});
  const point=new THREE.Vector3(landing.x,landing.y+.9+(reducedMotion?0:progress*.55),landing.z).project(camera);f.label.textContent=`+${f.event.coins} · Delivered!`;f.label.style.display=Math.abs(point.x)<1&&Math.abs(point.y)<1?'block':'none';f.label.style.left=`${(point.x+1)*el.clientWidth/2}px`;f.label.style.top=`${(-point.y+1)*el.clientHeight/2}px`;f.label.style.opacity=String(1-Math.max(0,progress-.55)/.45);if(age>=700)discardPaper(f);
 }
}
const grassTime=Date.now(),minute=Math.floor(grassTime/60000);
if(grassHistoryRef!==p.grassHistory){grassHistoryRef=p.grassHistory;grass.merge(p.grassHistory??[]);}
if(p.enabled&&p.player?.mowing){for(const c of sweptGrass(beforeMove.x,beforeMove.z,you.position.x,you.position.z))if(grassIndices.has(c.id)&&grass.predict(c.id,grassTime))clippingUntil=now+250;}
if(grassRevision!==grass.revision||grassTime>=nextRegrowth||grassMinute!==minute){
 const cutSet=grass.cuts(grassTime);
 // Resolve saved and pending cuts before refreshing blade heights.
 if(grassMinute!==minute)lawnCells.forEach((c,i)=>setGrassCut(i,cutSet.has(c.id)));
 else {for(const id of previousCuts)if(!cutSet.has(id)){const i=grassIndices.get(id);if(i!==undefined)setGrassCut(i,false);}for(const id of cutSet)if(!previousCuts.has(id)){const i=grassIndices.get(id);if(i!==undefined)setGrassCut(i,true);}}
 previousCuts=cutSet;grassRevision=grass.revision;grassMinute=minute;nextRegrowth=grass.nextRegrowth(grassTime);grassTall.instanceMatrix.needsUpdate=true;
}
clippings.visible=now<clippingUntil;if(clippings.visible)for(let j=0;j<18;j++){const phase=(now*.003+j*.137)%1;grassMatrix.position.set(you.position.x+Math.sin(j*2.3)*phase*.95,.3+Math.sin(phase*Math.PI)*.7,you.position.z+Math.cos(j*2.3)*phase*.95);grassMatrix.scale.setScalar(1-phase);grassMatrix.rotation.set(j,now*.003,j);grassMatrix.updateMatrix();clippings.setMatrixAt(j,grassMatrix.matrix)}clippings.instanceMatrix.needsUpdate=true;
if(follow){cameraTarget.copy(you.position);if(el.clientWidth>700){const lead=screenToGround(3.4,2.1,yaw);cameraTarget.x+=lead.x;cameraTarget.z+=lead.z;}selection.visible=false;}target.lerp(cameraTarget,reducedMotion?1:1-Math.exp(-dt*(inspecting?9:3)));const cameraDistance=Math.max(53.91,viewHeight);(scene.fog as THREE.Fog).near=cameraDistance+150;(scene.fog as THREE.Fog).far=cameraDistance+350;const view=cameraOffset(yaw,pitch,cameraDistance);offset.set(view.x,view.y,view.z);camera.position.copy(target).add(offset);camera.lookAt(target);
const worldDone=new Map((p.worldWork??[]).map(w=>[w.id,w]));for(const t of WORK_TARGETS){const g=taskObjects.get(t.id)!,done=worldDone.get(t.group);g.visible=t.job!=='deliver'||!!p.parcelHomes?.includes(t.home!);g.userData.marker.visible=t.job===p.player?.shift&&!done;g.userData.marker.rotation.y=now*.001;g.userData.result.visible=t.job==='clean'?!done:!!done&&done.target===t.id&&!(t.job==='deliver'&&actionParticle.visible&&animTarget?.id===t.id)&&!(t.job==='paper'&&[...paperFlights.values()].some(f=>!f.celebratedAt&&f.home.id===t.home));if(t.job==='garden'){const growth=done?Math.min(1,Math.max(0,(Date.now()-done.completed)/6000)):0;g.userData.foliage.scale.y=.45+growth*.85;g.userData.foliage.rotation.z=done?0:.24;if(g.userData.doneAt!==(done?.completed??0)){g.userData.doneAt=done?.completed??0;g.userData.soil.material=mat(done?'#786044':'#ba996d');g.userData.foliage.traverse((o:THREE.Object3D)=>{if(o instanceof THREE.Mesh&&o.geometry.type==='IcosahedronGeometry'&&o.position.y<.53)o.material=mat(done?'#e4a0bc':'#bfa879')})}}}
for(const station of STATIONS){const g=taskObjects.get(station.id)!;g.userData.marker.visible=station.jobs.includes(p.player?.shift??'');if(g.userData.marker.visible)label('station-'+station.id,station.title,g);else{otherLabels.get('station-'+station.id)?.remove();otherLabels.delete('station-'+station.id)}}
for(const b of buildings)label('building-'+b.id,b.name,taskObjects.get(b.id)!);for(const f of [...(planning.territories.includes('island')?FERRY_STOPS:[]),FARM_GATE])label(f.id,f.id===FARM_GATE.id?(farmIsOpen(p.planning??{})?'Town Farm · west road open':`Town Farm · road closed · ${Math.floor((p.planning?.farmFunded??0)/TOWN_FARM.cost*100)}% funded`):f.name,taskObjects.get(f.id)!);
parkUpgrade.visible=(p.project??0)>=100;
const editing=!!p.placement;editorRoot.visible=editing;ghostRoot.visible=editing;
if(editing&&!wasEditing){follow=false;inspecting=true;viewHeight=60;resize();cameraTarget.set(p.placement!.value.x,0,p.placement!.value.z);}if(!editing&&wasEditing){ghostKey='';api.center();}wasEditing=editing;
if(p.placement){const next=JSON.stringify(p.placement);if(next!==ghostKey){ghostKey=next;ghostRoot.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();(o.material as THREE.Material).dispose()}});ghostRoot.clear();const spec=placementBuilding(planning,p.placement.choice,p.placement.value),valid=!placementError(planning,p.placement.choice,p.placement.value),style=p.placement.choice.kind==='build'?(p.placement.choice.option==='pets'?'pets':p.placement.choice.option==='garden'?'garden':p.placement.choice.option==='food'?'market':'workshop'):nodeById(p.placement.choice.kind==='branch'?p.placement.choice.option:planning.institutions.find(i=>i.id===p.placement!.choice.institution)!.node)?.style??'campus';const model=buildingModel({box,ball,cylinder,roof,bench,flower},spec,style);model.traverse(o=>{if(o instanceof THREE.Mesh){const material=(o.material as THREE.MeshStandardMaterial).clone();material.transparent=true;material.opacity=.65;material.depthWrite=false;material.color.lerp(new THREE.Color(valid?'#65c98c':'#ef6a65'),.35);o.material=material;}});ghostRoot.add(model);const rim=box(spec.width,.075,spec.depth,valid?'#65c98c':'#ef6a65',spec.x,.34,spec.z,ghostRoot);rim.material=(rim.material as THREE.MeshStandardMaterial).clone();const door=entrance(spec),marker=box(.8,.08,.8,'#f8dc86',door.x,.37,door.z,ghostRoot);marker.material=(marker.material as THREE.MeshStandardMaterial).clone();}}
const activePlan=p.planning?.proposals.find(plan=>plan.status==='voting'||plan.status==='approved'||plan.status==='ready'),nextPlanKey=JSON.stringify(activePlan&&[activePlan.id,activePlan.status,activePlan.funded]);
if(nextPlanKey!==planKey){planKey=nextPlanKey;planOutline.traverse(o=>{if(o instanceof THREE.Mesh)o.geometry.dispose()});planOutline.clear();const site=activePlan?.kind==='expand'?proposalSite(activePlan):undefined;planOutline.visible=!!site;if(site){const color=activePlan!.status==='voting'?'#e3cb86':'#d39859',w=site.width,d=site.depth;planOutline.position.set(site.x,0,site.z);for(const x of [-w/2,w/2])box(.12,.06,d,color,x,.29,0,planOutline);for(const z of [-d/2,d/2])box(w,.06,.12,color,0,.29,z,planOutline);for(const x of [-w/2,w/2])for(const z of [-d/2,d/2]){box(.16,.95,.16,'#a48155',x,.65,z,planOutline);box(.45,.2,.2,color,x,.95,z,planOutline)}planSign.position.set(site.x,.2,site.z+d/2+1);}}
if(activePlan?.kind==='expand')label('town-plan',`${activePlan.status==='voting'?'Proposed':'Building'}: ${proposalTitle(activePlan)}`,planSign);else{otherLabels.get('town-plan')?.remove();otherLabels.delete('town-plan');}
const nextCivicKey=JSON.stringify([p.civic?.featured,p.civic?.projects]);if(nextCivicKey!==civicKey){civicKey=nextCivicKey;for(const [id,g]of civicArt.groups){g.visible=!!p.civic?.projects.some(p=>p.id===id&&p.completed>0)&&!(id==='market-canopies'&&planning.institutions.find(i=>i.id==='towncenter')?.node!=='root')&&!(id==='library-court'&&nodeById(planning.institutions.find(i=>i.id==='library')!.node)?.depth===10);if(id==='library-court'){const site=locationOf(planning.institutions.find(i=>i.id==='library')!),a=site.rotation*Math.PI/180;g.rotation.y=a;g.position.set(site.x+16*Math.cos(a)-9*Math.sin(a),0,site.z-16*Math.sin(a)-9*Math.cos(a));}if(id==='market-canopies'){const site=locationOf(planning.institutions.find(i=>i.id==='towncenter')!),a=site.rotation*Math.PI/180;g.rotation.y=a;g.position.set(site.x-14*Math.sin(a),0,site.z-14*Math.cos(a));}}const featured=projectById(p.civic?.featured);civicArt.construction.visible=!!featured&&!p.civic?.projects.some(p=>p.id===featured.id&&p.completed>0);if(featured)civicArt.construction.position.set(featured.x+2.5,0,featured.z+2.5);}

pets.update(p.properties??[],Date.now());
lifeArt.update(p.life,Date.now(),[...(p.peers??[]).filter(peer=>peer.id!==p.player?.id),...(p.player?[{...p.player,x:you.position.x,z:you.position.z}]:[])]);
for(const spot of [PICNIC,...(farmIsOpen(planning)?[FARM_ORDER]:[])])label(spot.id,spot.id===PICNIC.id?`Neighborhood picnic · ${p.life?.picnicGuests.length??0} visitors today`:'Shared pantry · picnic basket',taskObjects.get(spot.id)!);

const newKey=JSON.stringify(p.properties);if(newKey!==decorationKey){decorationKey=newKey;decorations.traverse(o=>{if(o instanceof THREE.Mesh)o.geometry.dispose()});decorations.clear();for(const property of p.properties??[]){const h=HOMES[property.home];if(property.items.includes('flowers'))for(let i=0;i<8;i++)flower(h.x-1.8+i*.32,h.z+2.7,'#e1a0bf',decorations);if(property.items.includes('bench'))bench(h.x+2,h.z+3,decorations);if(property.items.includes('birdbath')){cylinder(.1,.6,'#b5bca8',h.x-2.3,.55,h.z+3,decorations);cylinder(.42,.1,'#d1d3bb',h.x-2.3,.88,h.z+3,decorations);cylinder(.34,.04,'#8dc9c8',h.x-2.3,.96,h.z+3,decorations);}if(property.items.includes('lanterns'))for(const dx of [-1.9,1.9]){box(.1,1,.1,'#6b7154',h.x+dx,.75,h.z+2.7,decorations);box(.25,.35,.25,'#edd58c',h.x+dx,1.35,h.z+2.7,decorations);}if(property.items.includes('topiary'))for(const dx of [-2.4,2.4]){cylinder(.23,.4,'#b78a65',h.x+dx,.4,h.z+2.6,decorations);for(let i=0;i<3;i++)ball(.34-i*.065,'#638b58',h.x+dx,.8+i*.3,h.z+2.6,decorations);}if(property.items.includes('roses')){for(const dx of [-2.6,-1.4])box(.1,1.8,.1,'#d5ba8d',h.x+dx,1.1,h.z+2.8,decorations);box(1.4,.13,.25,'#d5ba8d',h.x-2,1.95,h.z+2.8,decorations);for(let i=0;i<6;i++)ball(.18,'#bd7089',h.x-2.6+i*.24,2.1,h.z+2.8,decorations);}if(property.items.includes('home')){box(4.7,.2,1.8,'#b69d75',h.x,.35,h.z+2.8,decorations);for(const x of [-2,2])box(.12,2.1,.12,'#eee0b8',h.x+x,1.4,h.z+3.3,decorations)}}}
for(const peer of p.peers??[]){if(peer.id===p.player?.id)continue;let g=people.get(peer.id);if(!g){g=avatar(peer.color);g.position.set(peer.x,groundHeight(peer.x,peer.z),peer.z);people.set(peer.id,g)}if(g.userData.color!==peer.color){g.userData.color=peer.color;g.userData.shirt.material=mat(peer.color);g.userData.arms.forEach((arm:THREE.Mesh)=>arm.material=mat(peer.color))}dressAvatar(g,peer,mat);const dx=peer.x-g.position.x,dz=peer.z-g.position.z;g.position.x+=dx*Math.min(1,dt*5);g.position.z+=dz*Math.min(1,dt*5);mount(g,!!peer.mowing,Math.hypot(dx,dz)>.04,now,peer);if(Math.hypot(dx,dz)>.04){g.rotation.y=Math.atan2(dx,dz);if(!peer.mowing&&!peer.riding&&peer.shift!=='paper')g.userData.legs.forEach((l:THREE.Mesh,i:number)=>l.rotation.x=Math.sin(now*.014+i*Math.PI)*.4)}}for(const [id,g] of people){if(!(p.peers??[]).some(a=>a.id===id)){scene.remove(g);people.delete(id);otherLabels.get(id)?.remove();otherLabels.delete(id)}}for(const peer of p.peers??[]){const g=people.get(peer.id);if(g){g.position.y=groundHeight(g.position.x,g.position.z);label(peer.id,((peer.emoteUntil??0)>Date.now()?(GESTURES.find(e=>e.id===peer.emote)?.symbol??(peer.emote==='sit'?'☕':'🌱'))+' ':'')+(peer.id===p.mayorId?'Mayor ':'')+peer.name,g)}}
if(p.player)animateLifeGesture(you,Math.hypot(vx,vz)>.08&&p.player.emote==='sit'?{...p.player,emote:null}:p.player,Date.now(),reducedMotion);
for(const peer of p.peers??[]){const g=people.get(peer.id);if(g)animateLifeGesture(g,peer,Date.now(),reducedMotion);}
if(!reducedMotion)windmill.rotation.z=now*.00013;
if(p.enabled){const candidates=[...(!p.player?.shift&&!p.player?.mowing&&p.player?.home!=null?(p.properties??[]).map(h=>({id:`home-door-${h.home}`,...homeDoor(HOMES[h.home])})):[]),...WORK_TARGETS.filter(t=>t.job===p.player?.shift&&(t.job!=='deliver'||p.parcelHomes?.includes(t.home!))&&!worldDone.has(t.group)),...STATIONS.filter(s=>s.jobs.includes(p.player?.shift??'')),...(planning.territories.includes('island')?FERRY_STOPS:[]),FARM_GATE,...(!p.player?.shift&&!p.player?.mowing?[PICNIC,...(farmIsOpen(planning)?[FARM_ORDER,...FARM_BEDS]:[])]:[]),...(!p.player?.shift?[...buildings.map(b=>({id:b.id,...entrance(b)})),{id:'park',...PARK}]:[])];const nearest=candidates.sort((a,b)=>Math.hypot(a.x-you.position.x,a.z-you.position.z)-Math.hypot(b.x-you.position.x,b.z-you.position.z))[0];const id=nearest&&Math.hypot(nearest.x-you.position.x,nearest.z-you.position.z)<1.9?nearest.id:'';if(id!==lastNear){lastNear=id;p.onNear?.(id||null)}}
if(inspectedHome!==null&&Date.now()<identityUntil&&p.enabled&&!p.placement){const h=HOMES[inspectedHome],owner=p.properties?.find(v=>v.home===h.id),level=houseById(owner?.house).level,point=new THREE.Vector3(h.x,5.1+Math.floor((level-1)/2)*1.35,h.z).project(camera);const visible=Math.abs(point.x)<1&&Math.abs(point.y)<1;identity.style.display=visible?'grid':'none';identity.style.left=`${Math.max(110,Math.min(el.clientWidth-110,(point.x+1)*el.clientWidth/2))}px`;identity.style.top=`${Math.max(95,(-point.y+1)*el.clientHeight/2)}px`;const name=owner?`${owner.name}’s home`:'Available home',address=h.name+(h.id===p.player?.home?' · Your front door opens inside':'');if(identityName.textContent!==name)identityName.textContent=name;if(identityAddress.textContent!==address)identityAddress.textContent=address;identityRing.visible=visible;identityRing.position.set(h.x,.27,h.z);}else{identity.style.display='none';identityRing.visible=false;}
const selectedHouse=p.highlightHome==null?undefined:HOMES[p.highlightHome];
if(selectedHouse&&!p.placement){const property=p.properties?.find(h=>h.home===selectedHouse.id),level=property?houseById(property.house).level:1,roofHeight=4.7+Math.floor((level-1)/2)*1.35;const point=new THREE.Vector3(selectedHouse.x,roofHeight+.5,selectedHouse.z).project(camera);homeMarker.style.display=Math.abs(point.x)<1.05&&Math.abs(point.y)<1.05&&point.z>=-1&&point.z<=1?'flex':'none';homeMarker.style.left=`${(point.x+1)*el.clientWidth/2}px`;homeMarker.style.top=`${(-point.y+1)*el.clientHeight/2}px`;homeMarkerName.textContent=selectedHouse.name;}else homeMarker.style.display='none';
const labelP=you.position.clone().add(new THREE.Vector3(0,2.1,0)).project(camera);playerLabel.style.left=`${(labelP.x+1)*el.clientWidth/2}px`;playerLabel.style.top=`${(-labelP.y+1)*el.clientHeight/2}px`;playerLabel.textContent=((p.player?.emoteUntil??0)>Date.now()?(GESTURES.find(e=>e.id===p.player?.emote)?.symbol??(p.player?.emote==='sit'?'☕':'🌱'))+' ':'')+(p.player?.id===p.mayorId?'Mayor ':'')+(p.player?.name??'You');playerLabel.style.display=p.enabled&&viewHeight<85?'block':'none';renderer.render(scene,camera)}
frame=requestAnimationFrame(animate);
return()=>{disposed=true;cancelAnimationFrame(frame);pets.dispose();lifeArt.dispose();for(const f of [...paperFlights.values()])discardPaper(f);observer.disconnect();window.removeEventListener('keydown',keyDown);window.removeEventListener('keyup',keyUp);window.removeEventListener('blur',blur);removeCameraGestures();renderer.domElement.removeEventListener('wheel',wheel);renderer.domElement.removeEventListener('pointermove',hoverHouse);renderer.domElement.removeEventListener('pointerleave',leaveHouse);identity.remove();scene.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();const ms=Array.isArray(o.material)?o.material:[o.material];ms.forEach(m=>m.dispose())}});gridGeometry.dispose();gridMaterial.dispose();renderer.dispose();renderer.domElement.remove();playerLabel.remove();homeMarker.remove();otherLabels.forEach(l=>l.remove())};},[layoutKey,props.player?.id]);
return <div className="world" ref={host} aria-label="Interactive three dimensional town">{error&&<div role="alert" className="world-error">{error}</div>}</div>}
