'use client';
import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import {DEFAULT_YAW,DEFAULT_PITCH,clampPitch,screenToGround,cameraOffset} from './camera';
import {installCameraGestures} from './cameraGestures';
import {WORK_TARGETS,TARGET_BY_ID,STATIONS} from './workTargets';
import {GARDEN_AREAS,inCommunityGarden} from './gardenAreas';
import {findPath} from './pathfinding';
import {BUILDINGS,entrance,BRIDGES,ROADS,STALLS,COMMUNITY_PARK,isTownBlocked,groundHeight} from './townLayout';
import {HOMES,TASKS,PARK,SCHOOL,LAWN_CELLS,sweptGrass,type Peer,type Resident} from './data';
export type SceneApi={position:(consume?:boolean)=>{x:number;z:number;path:{x:number;z:number}[]};navigate:(x:number,z:number)=>void;center:()=>void;orbit:(yaw:number,pitch?:number)=>void;pan:(x:number,y:number)=>void;resetCamera:()=>void;stop:()=>void;zoom:(by:number)=>void;setPosition:(x:number,z:number)=>void};
type Props={cameraMode?:'pan'|'orbit';focus?:[number,number]|null;player?:Resident;peers?:Peer[];properties?:{home:number;items:string[];name:string}[];completed?:string[];lawnCuts?:string[];worldWork?:{id:string;target:string;completed:number}[];rewardFx?:{target:string;at:number;origin?:{x:number;z:number}}|null;onSelectTask?:(id:string)=>void;project?:number;working?:boolean;enabled?:boolean;stick?:{x:number;y:number};onReady?:(api:SceneApi)=>void;onNear?:(id:string|null)=>void;onAction?:()=>void;onPaperAction?:()=>void;onSelectHome?:(id:number)=>void};
export default function TownScene(props:Props){const host=useRef<HTMLDivElement>(null);const live=useRef(props);live.current=props;const focus=useRef<[number,number]|null>(props.focus??null);focus.current=props.focus??null;const [error,setError]=useState('');
useEffect(()=>{if(!host.current)return;const el=host.current;let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});}catch{setError('This device could not start the 3D view. Try a browser with WebGL enabled.');return}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.18;el.appendChild(renderer.domElement);
const reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;const scene=new THREE.Scene();scene.background=new THREE.Color('#b8d8d0');scene.fog=new THREE.Fog('#b8d8d0',80,180);
const camera=new THREE.OrthographicCamera(-30,30,20,-20,.1,220);let viewHeight=29;const target=new THREE.Vector3(0,0,0),cameraTarget=new THREE.Vector3(0,0,5);let yaw=DEFAULT_YAW,pitch=DEFAULT_PITCH;const offset=new THREE.Vector3(24,31,37);camera.position.copy(offset);camera.lookAt(target);
scene.add(new THREE.HemisphereLight('#fff2ce','#617e50',2.4));const sun=new THREE.DirectionalLight('#fff3d1',3.1);sun.position.set(-22,45,15);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-45;sun.shadow.camera.right=45;sun.shadow.camera.top=45;sun.shadow.camera.bottom=-45;sun.shadow.camera.far=110;sun.shadow.bias=-.0003;sun.shadow.normalBias=.04;scene.add(sun);
const materials=new Map<string,THREE.MeshStandardMaterial>();const mat=(color:string)=>{if(!materials.has(color))materials.set(color,new THREE.MeshStandardMaterial({color,roughness:.92,flatShading:true}));return materials.get(color)!};
const staticRoot=new THREE.Group();scene.add(staticRoot);
function mesh(g:THREE.BufferGeometry,c:string,x:number,y:number,z:number,parent:THREE.Object3D=staticRoot){const m=new THREE.Mesh(g,mat(c));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}
function box(w:number,h:number,d:number,c:string,x:number,y:number,z:number,parent?:THREE.Object3D){return mesh(new THREE.BoxGeometry(w,h,d),c,x,y,z,parent)}
function ball(r:number,c:string,x:number,y:number,z:number,parent?:THREE.Object3D){return mesh(new THREE.IcosahedronGeometry(r,1),c,x,y,z,parent)}
function cylinder(r:number,h:number,c:string,x:number,y:number,z:number,parent?:THREE.Object3D,rt?:number){return mesh(new THREE.CylinderGeometry(rt??r,r,h,10),c,x,y,z,parent)}
function roof(w:number,d:number,h:number,c:string,x:number,y:number,z:number,parent?:THREE.Object3D){const s=new THREE.Shape();s.moveTo(-w/2,0);s.lineTo(0,h);s.lineTo(w/2,0);s.closePath();const g=new THREE.ExtrudeGeometry(s,{depth:d,bevelEnabled:false});g.translate(0,0,-d/2);return mesh(g,c,x,y,z,parent)}
let randSeed=44;function rand(){randSeed=(randSeed*1664525+1013904223)>>>0;return randSeed/4294967296}
// The terrain and every prop are real Three.js geometry, lit from one warm sun.
box(150,1.1,155,'#8cab60',0,-.62,0);box(150,.2,155,'#92b86b',0,-.02,0);
for(const r of ROADS)box(r.width,.06,r.depth,'#d4c59b',r.x,.12,r.z);box(38,.08,40,'#c6c7ad',0,.13,-1);box(35,.03,37,'#dfd3b5',0,.19,-1);
// Three bridges have bank openings, approach ramps, and the same walkable deck as navigation.
box(8,.05,145,'#64b6bd',28,.1,0);box(7,.06,145,'#79c6c9',28,.13,0);
for(const x of [23.6,32.4]){let start=-72.5;for(const end of [...BRIDGES.map(b=>b.z-3.1),72.5]){const length=end-start;if(length>0){box(.7,.6,length,'#abaf81',x,.04,start+length/2);box(.35,.15,length,'#d8d4ad',x,.38,start+length/2)}start=end+6.2}}
for(const bridge of BRIDGES){
 for(let j=0;j<16;j++)box(10,.2,.33,'#aa8051',28,.42,bridge.z-2.5+j*.34);
 for(const x of [22,34]){const ramp=box(2.06,.13,5.4,'#b18b5c',x,.27,bridge.z);ramp.rotation.z=x<28?Math.atan(.2):-Math.atan(.2)}
 for(const z of [bridge.z-2.8,bridge.z+2.8]){box(10,.13,.13,'#7e6546',28,1.15,z);for(const x of [23,26,30,33])box(.15,1,.15,'#8a6b45',x,.7,z)}
}
for(let j=0;j<65;j++)box(.35+rand()*1.6,.012,.06,'#b6e4dc',25+rand()*6,.17,-65+rand()*130);
function flower(x:number,z:number,color:string,parent:THREE.Object3D=staticRoot){cylinder(.035,.35,'#648642',x,.28,z,parent);const bloom=ball(.13,color,x,.49,z,parent);bloom.scale.y=.65;ball(.05,'#efce68',x,.55,z,parent)}
function tree(x:number,z:number,scale=1){if(inCommunityGarden(x,z,1.5)||isTownBlocked(x,z)||ROADS.some(r=>Math.abs(x-r.x)<r.width/2+1.5&&Math.abs(z-r.z)<r.depth/2+1.5)||(Math.abs(x)<21&&Math.abs(z)<26))return;const g=new THREE.Group();g.position.set(x,0,z);g.scale.setScalar(scale);staticRoot.add(g);cylinder(.23,2.2,'#896645',0,1.1,0,g,.15);ball(1.4,'#63884d',0,2.9,0,g);ball(1.05,'#779953',-.65,2.6,.5,g);ball(1.1,'#88a45a',.65,3.2,-.1,g);ball(.85,'#99b766',-.2,3.75,0,g);}
function fence(x:number,z:number,w:number){for(let i=0;i<=w;i+=.8){box(.13,.7,.13,'#f0e0b5',x+i,.4,z);roof(.17,.17,.12,'#f0e0b5',x+i,.75,z)}box(w,.12,.1,'#e4d2aa',x+w/2,.35,z);box(w,.12,.1,'#e4d2aa',x+w/2,.63,z)}
function bench(x:number,z:number,parent:THREE.Object3D=staticRoot){for(let i=0;i<3;i++)box(1.5,.1,.17,'#ab8051',x,.5,z+i*.19,parent);for(const a of [-.55,.55]){box(.12,.5,.48,'#535d40',x+a,.25,z+.2,parent);box(.12,1,.1,'#535d40',x+a,.5,z-.05,parent)}box(1.5,.3,.1,'#bf945c',x,.88,z-.07,parent)}
function house(h:typeof HOMES[number]){const g=new THREE.Group();g.position.set(h.x,0,h.z);staticRoot.add(g);box(4.9,.25,4.2,'#b4b18c',0,.2,0,g);box(4.3,2.5,3.5,h.color,0,1.55,0,g);box(4.38,.18,3.6,'#efdab0',0,2.6,0,g);roof(5.1,4.2,1.75,h.roof,0,2.78,0,g);roof(4.45,3.6,1.35,'#f1dfbd',0,2.61,0,g);roof(5.1,4.2,1.75,h.roof,0,2.81,0,g);box(.48,1.1,.5,'#bf9875',1.2,3.9,-.65,g);box(.64,.14,.65,'#d5b696',1.2,4.48,-.65,g);
// Exposed timber framing, sash windows, flower boxes, and a small porch.
for(const x of [-2.06,2.06])box(.14,2.45,.14,'#ac865e',x,1.54,1.78,g);box(.82,1.53,.16,'#715b3d',.55,1.03,1.84,g);box(.68,1.4,.12,['#6b8b83','#ae6f56','#668198'][h.id%3],.55,1.02,1.95,g);ball(.055,'#e8bc56',.77,1.04,2.04,g);box(1.65,.16,.8,'#c7b68e',.55,.35,2.18,g);box(1.8,.13,.48,'#dbcba7',.55,.2,2.64,g);
for(const x of [-1.15,1.55]){box(.72,.85,.13,'#f4e6bf',x,1.65,1.84,g);box(.55,.64,.06,'#79b8bc',x,1.66,1.93,g);box(.055,.7,.08,'#f9efce',x,1.66,1.98,g);box(.58,.055,.08,'#f9efce',x,1.65,1.98,g);for(const a of [-.47,.47])box(.17,.8,.12,h.roof,x+a,1.65,1.84,g);box(.88,.24,.3,'#a07850',x,1.06,1.95,g);for(let k=0;k<4;k++){ball(.14,['#d984a4','#f1d872','#b695ce'][h.id%3],x-.3+k*.2,1.25,2.02,g)}}
cylinder(.38,.48,'#b67c55',-2.45,.36,1.8,g,.45);ball(.52,'#6e914b',-2.45,.9,1.8,g);box(1.1,.055,2.5,'#cfbf96',.55,.14,3.6,g);
box(.16,.85,.16,'#8d7750',2.65,.5,2.1,g);box(.5,.35,.45,'#638c87',2.65,1,2.1,g);roof(.52,.47,.15,'#658e89',2.65,1.18,2.1,g);
if(h.id<6){fence(h.x-3.4,h.z-2.6,6.7);for(let k=0;k<7;k++)flower(h.x-3.4+k*.34,h.z+2.7,['#fff0ad','#d890b3','#ede1dd'][h.id%3]);tree(h.x-3.8,h.z-1.6,.8)}}
HOMES.forEach(house);
// Fountain forms the visual heart of the town.
cylinder(2.45,.12,'#babda1',0,.24,0);cylinder(1.72,.55,'#dcd8b7',0,.48,0);cylinder(1.43,.1,'#6fb8bc',0,.79,0);cylinder(.3,.8,'#c3c6a8',0,1.05,0);cylinder(.87,.18,'#e1ddbe',0,1.4,0);cylinder(.68,.04,'#8dd1cb',0,1.51,0);cylinder(.15,.72,'#d5d7b2',0,1.8,0);ball(.22,'#e9cf8b',0,2.24,0);
for(const [x,z] of [[-4,-4],[4,4],[-4,4],[4,-4]]){cylinder(.43,.45,'#ba9271',x,.4,z);}
// Correct planter groups are static meshes.
for(const [x,z] of [[-4,-4],[4,4],[-4,4],[4,-4]]){for(let i=0;i<5;i++)flower(x+(rand()-.5)*.5,z+(rand()-.5)*.5,i%2?'#dda0b6':'#edda82')}
bench(-4.7,-1);bench(2.9,4.5);bench(-15,3);
function lamp(x:number,z:number){cylinder(.07,2.6,'#63725b',x,1.4,z);box(.5,.62,.5,'#e7cd85',x,2.93,z);roof(.76,.76,.38,'#576b58',x,3.26,z);for(const a of [-.25,.25])for(const b of [-.25,.25])box(.045,.65,.045,'#61715b',x+a,2.94,z+b)}
for(const p of [[-6,-5],[6,5],[-6,7],[6,-7],[-18,-4],[19,4]])lamp(p[0],p[1]);
// Shops and civic buildings face onto the square, each with its own storefront.
for(const b of BUILDINGS){const g=new THREE.Group();g.position.set(b.x,0,b.z);staticRoot.add(g);
 box(b.width+.4,.22,b.depth+.4,'#b8b39b',0,.22,0,g);box(b.width,b.height,b.depth,b.color,0,b.height/2+.3,0,g);
 roof(b.width+.7,b.depth+.6,b.id==='townhall'?2:1.5,b.roof,0,b.height+.32,0,g);
 box(1.3,2,.16,'#57766d',0,1.25,b.depth/2+.1,g);box(1.8,.15,1.2,'#d3c4a0',0,.28,b.depth/2+.55,g);
 for(const x of [-b.width*.31,b.width*.31]){box(b.id==='townhall'?1.2:1.8,1.5,.15,'#f5e7c6',x,1.9,b.depth/2+.09,g);box(b.id==='townhall'?1:1.6,1.3,.07,'#7baeb1',x,1.9,b.depth/2+.19,g);box(.07,1.35,.09,'#f7efce',x,1.9,b.depth/2+.24,g)}
 if(b.id==='townhall'){for(const x of [-2.2,2.2])cylinder(.19,3.7,'#f2e5c2',x,2.1,b.depth/2+.4,g);box(1.8,1.4,1.7,b.color,0,b.height+1.7,0,g);roof(2.3,2.1,1,b.roof,0,b.height+2.4,0,g);const clock=mesh(new THREE.CircleGeometry(.47,20),'#fff6d6',0,b.height+1.8,.87,g);box(.035,.33,.02,'#5b655b',0,b.height+1.95,.9,g);box(.27,.035,.02,'#5b655b',.12,b.height+1.8,.9,g)}
 else if(b.id!=='school'){for(let i=0;i<10;i++)box((b.width+.4)/10,.18,1.3,i%2?'#fff0d1':b.roof,-b.width/2+(i+.5)*(b.width+.4)/10,2.85,b.depth/2+.55,g)}
 if(b.id==='general'){const tire=mesh(new THREE.TorusGeometry(.42,.065,6,16),'#465951',-2,.65,b.depth/2+.8,g);box(.6,.08,.08,'#cfad68',-2,1.25,b.depth/2+.8,g);box(.7,.7,.6,'#b49461',2,.6,b.depth/2+.8,g)}
 if(b.id==='clothing'){box(.9,1.1,.12,'#b5739a',-2,1.6,b.depth/2+.27,g);box(1.25,.27,.14,'#b5739a',-2,2,b.depth/2+.28,g)}
 if(b.id==='post'){box(.55,.9,.5,'#557e89',2,.65,b.depth/2+.9,g);box(.4,.07,.05,'#f6e6b8',2,.94,b.depth/2+1.17,g)}
 if(b.id==='cafe'){for(const x of [-2.5,2.5]){cylinder(.6,.1,'#c3a478',x,.9,b.depth/2+1.3,g);cylinder(.08,.65,'#7f7358',x,.5,b.depth/2+1.3,g)}}
}
// Market stalls and a public noticeboard form the south edge of the square.
for(let j=0;j<STALLS.length;j++){const {x,z}=STALLS[j];box(2.3,1.05,1.3,'#b48d5a',x,.7,z);for(const dx of [-1.13,1.13])for(const dz of [-.63,.63])box(.1,2.5,.1,'#8e7351',x+dx,1.5,z+dz);for(let k=0;k<6;k++){box(.46,.12,2.15,k%2?'#fff0ce':['#c27b67','#809a69','#d5af56'][j],x-1.15+k*.46,2.55,z);box(.46,.26,.09,k%2?'#fff0ce':['#c27b67','#809a69','#d5af56'][j],x-1.15+k*.46,2.32,z+1.04)}for(let k=0;k<8;k++)ball(.15,['#dd8c5b','#d1b955','#8d9d54'][j],x-.85+k*.23,1.34,z)}
cylinder(1.5,6,'#e4d5ae',-27,3.1,-18,undefined,.95);roof(3.5,3.3,2.2,'#7b8a69',-27,6.1,-18);const windmill=new THREE.Group();windmill.position.set(-27,5.65,-16.3);scene.add(windmill);for(let k=0;k<4;k++){const sail=new THREE.Group();sail.rotation.z=k*Math.PI/2;windmill.add(sail);box(.13,3.3,.12,'#8f7551',0,1.7,0,sail);box(.72,2.3,.08,'#f1e3bd',.22,2.1,.02,sail)}ball(.24,'#b3a17a',-27,5.65,-16.12);
// Park, hedges, little stones, and wildflower meadows.
const park=COMMUNITY_PARK;box(park.width,.1,park.depth,'#80a25b',park.x,.15,park.z);box(park.width,.04,2,'#d4c9a2',park.x,.23,3);box(2,.04,park.depth,'#d4c9a2',park.x+6,.23,0);
for(const [dx,dz]of [[-6,6],[-6,-7],[6,7]]){bench(park.x+dx,dz);tree(park.x+dx,dz+1.7,.9)}
for(let i=0;i<20;i++)ball(.36,'#77934f',park.x-park.width/2,.4,-9+i*.95);
for(const p of [[-19,8],[-22,-7],[18,9],[19,-12],[4,-17],[-7,15],[18,17],[-18,16],[36,5],[36,-8],[21,-21],[-30,5]])tree(p[0],p[1],.9+rand()*.25);
for(let i=0;i<120;i++){const x=-70+rand()*140,z=-70+rand()*140;if((Math.abs(x)<22&&Math.abs(z)<26)||(x>23&&x<33)||HOMES.some(h=>Math.abs(x-h.x)<4&&Math.abs(z-h.z)<4))continue;tree(x,z,.65+rand()*.65)}
for(let i=0;i<340;i++){const x=-23+rand()*46,z=-19+rand()*39;if((Math.abs(x)<10.5&&Math.abs(z)<9)||HOMES.some(h=>Math.abs(x-h.x)<3.6&&Math.abs(z-h.z)<4.5))continue;rand();if(i%4===0)flower(x+.2,z,'#f3e5b7')}
for(let i=0;i<25;i++){const x=-10+rand()*20,z=-8+rand()*16;if(Math.hypot(x,z)<2.6)continue;box(.4+rand()*.4,.018,.2,'#bfb597',x,.19,z)}
// Shared gardens have open paths, timber beds, and places for neighbors to sit.
for(const area of GARDEN_AREAS){
 box(area.width,.06,area.depth,'#84a767',area.x,.17,area.z);
 box(area.width-.4,.035,1,'#d6c49a',area.x,.22,area.z);
 box(.8,.035,area.depth-.4,'#d6c49a',area.x,.22,area.z);
 fence(area.x-area.width/2,area.z-area.depth/2,area.width);
 bench(area.x+area.width/2-1,area.z+area.depth/2-.8);
 for(const t of WORK_TARGETS.filter(t=>t.id.startsWith(`${area.id}-bed-`))){
  for(const dz of [-.5,.5])box(1.5,.22,.12,'#a98054',t.x,.24,t.z+dz);
  for(const dx of [-.72,.72])box(.12,.22,1,'#b18b5d',t.x+dx,.24,t.z);
 }
}
// Merge static props by material to keep the village comfortable on phones.
staticRoot.updateMatrixWorld(true);const batches=new Map<THREE.Material,THREE.BufferGeometry[]>();staticRoot.traverse(o=>{if(o instanceof THREE.Mesh){const g=(o.geometry.index?o.geometry.toNonIndexed():o.geometry.clone()).applyMatrix4(o.matrixWorld);const m=o.material as THREE.Material;if(!batches.has(m))batches.set(m,[]);batches.get(m)!.push(g);o.geometry.dispose()}});scene.remove(staticRoot);for(const [m,gs]of batches){const g=mergeGeometries(gs,false);if(g){const merged=new THREE.Mesh(g,m);merged.castShadow=true;merged.receiveShadow=true;scene.add(merged)}gs.forEach(g=>g.dispose())}
// Individual household deliveries, litter and thirsty beds replace abstract work sites.
const taskObjects=new Map<string,THREE.Group>();const hitMaterial=new THREE.MeshBasicMaterial({transparent:true,opacity:0,depthWrite:false,colorWrite:false});
for(const t of WORK_TARGETS){const g=new THREE.Group();g.position.set(t.x,0,t.z);g.userData.task=t.id;scene.add(g);taskObjects.set(t.id,g);
 const result=new THREE.Group();g.add(result);g.userData.result=result;
 if(t.job==='paper'){const paper=box(.48,.09,.29,'#fff1cd',0,t.kind==='mailbox'?1.25:.27,.07,result);paper.rotation.y=.25;box(.055,.1,.3,'#6e9780',0,t.kind==='mailbox'?1.25:.27,.07,result)}
 else if(t.job==='deliver'){box(.55,.45,.48,'#c29665',0,.43,0,result);box(.08,.47,.5,'#efd19c',0,.43,0,result)}
 else if(t.job==='clean'){const kind=t.id.length%3;if(kind===0){const bottle=cylinder(.1,.4,'#8ab9a6',0,.31,0,result,.05);bottle.rotation.z=1.1}else if(kind===1){const paper=box(.34,.05,.24,'#f0dcae',0,.23,0,result);paper.rotation.y=1.3;ball(.08,'#ceb789',.06,.3,.02,result)}else{const can=cylinder(.12,.25,'#9bafbb',0,.29,0,result);can.rotation.z=.8;}}
 else {g.userData.soil=box(1.3,.12,.85,'#ba996d',0,.22,0,g);const foliage=new THREE.Group();g.add(foliage);g.userData.foliage=foliage;for(let j=0;j<5;j++)flower(-.48+j*.24,(j%2-.5)*.24,'#bfa879',foliage);}
 const marker=mesh(new THREE.OctahedronGeometry(.14),'#f2cf70',0,t.kind==='mailbox'?1.65:1.1,0,g);g.userData.marker=marker;
 const hit=new THREE.Mesh(new THREE.BoxGeometry(t.job==='garden'?1.3:.8,1.3,.9),hitMaterial);hit.position.y=.6;g.add(hit);
}
for(const station of STATIONS){const g=new THREE.Group();g.position.set(station.x,0,station.z);g.userData.task=station.id;scene.add(g);taskObjects.set(station.id,g);if(station.id==='supplies'){box(1.4,.7,.85,'#b18b5e',0,.55,0,g);for(let j=0;j<4;j++)box(.45,.06,.3,'#fff0ce',-.35,.94+j*.065,0,g);box(.45,.4,.45,'#bd9567',.4,1.05,0,g)}else if(station.id==='recycling'){cylinder(.28,.7,'#5d8b72',-.32,.55,0,g);cylinder(.28,.7,'#789ca6',.32,.55,0,g);box(1.4,.05,.85,'#c8b88f',0,.18,0,g)}else{cylinder(.17,.6,'#799b96',0,.5,0,g);box(.55,.1,.14,'#8fb3ac',0,.85,0,g)}g.userData.marker=mesh(new THREE.OctahedronGeometry(.16),'#f3cd6b',0,1.6,0,g);}
for(const b of BUILDINGS){const g=new THREE.Group();const door=entrance(b);g.position.set(door.x,0,door.z);g.userData.task=b.id;const hit=new THREE.Mesh(new THREE.BoxGeometry(2.5,2,1.7),hitMaterial);hit.position.y=1;g.add(hit);scene.add(g);taskObjects.set(b.id,g)}
const actionParticle=new THREE.Group();scene.add(actionParticle);const flyingPaper=box(.4,.08,.24,'#fff0ce',0,0,0,actionParticle),flyingParcel=box(.35,.3,.3,'#c49a66',0,0,0,actionParticle);actionParticle.visible=false;let lastReward=0,flightStart=0,flightTarget=new THREE.Vector3(),flightOrigin=new THREE.Vector3(),flightJob='';
const waterDrops=new THREE.InstancedMesh(new THREE.SphereGeometry(.045,4,3),mat('#8dd4df'),16);scene.add(waterDrops);waterDrops.visible=false;const waterMatrix=new THREE.Object3D();
// Low draw-call lawn tiles and tall blades; short alternating stripes remain behind.
const grassBase=new THREE.InstancedMesh(new THREE.BoxGeometry(1,.035,1),mat('#8fba5d'),LAWN_CELLS.length);
const grassTall=new THREE.InstancedMesh(new THREE.ConeGeometry(.12,.53,3),mat('#507d36'),LAWN_CELLS.length*3);
grassBase.receiveShadow=true;grassTall.castShadow=false;grassTall.frustumCulled=false;scene.add(grassBase,grassTall);
const grassMatrix=new THREE.Object3D(),optimisticCuts=new Map<string,number>();let previousCuts=new Set<string>();let serverCuts=new Set<string>();let lastServerCuts:string[]|undefined;const grassIndices=new Map(LAWN_CELLS.map((c,i)=>[c.id,i]));
LAWN_CELLS.forEach((c,i)=>{grassMatrix.position.set(c.x,.215,c.z);grassMatrix.scale.set(c.size-.01,1,c.size-.01);grassMatrix.updateMatrix();grassBase.setMatrixAt(i,grassMatrix.matrix);grassBase.setColorAt(i,new THREE.Color(c.row%2?'#9cbe6a':'#85ad55'))});
function setGrassCut(i:number,cut:boolean){const c=LAWN_CELLS[i];for(let j=0;j<3;j++){grassMatrix.position.set(c.x+(j-1)*.19,.48,c.z+(j%2?-.15:.15));grassMatrix.scale.setScalar(cut?0:1);grassMatrix.rotation.set(0,i+j*2,0);grassMatrix.updateMatrix();grassTall.setMatrixAt(i*3+j,grassMatrix.matrix)}}
LAWN_CELLS.forEach((_,i)=>setGrassCut(i,false));grassTall.instanceMatrix.needsUpdate=true;
// A small burst of clippings follows the cutting deck as it crosses new grass.
const clippings=new THREE.InstancedMesh(new THREE.BoxGeometry(.055,.06,.14),mat('#7fa84c'),18);scene.add(clippings);clippings.visible=false;let clippingUntil=0;
const parkUpgrade=new THREE.Group();parkUpgrade.position.set(COMMUNITY_PARK.x+16,0,5);scene.add(parkUpgrade);bench(-17,0,parkUpgrade);bench(-15,0,parkUpgrade);for(let i=0;i<12;i++)flower(-18+i*.35,-1.8,'#efb3bd',parkUpgrade);parkUpgrade.visible=false;
const decorations=new THREE.Group();scene.add(decorations);let decorationKey='';
function avatar(color:string){const g=new THREE.Group();const legs=[box(.18,.4,.23,'#4e5b62',-.16,.43,0,g),box(.18,.4,.23,'#4e5b62',.16,.43,0,g)];box(.23,.12,.34,'#775f47',-.16,.18,.06,g);box(.23,.12,.34,'#775f47',.16,.18,.06,g);const shirt=cylinder(.3,.48,color,0,.88,0,g,.27);const arms=[box(.16,.46,.2,color,-.35,.88,0,g),box(.16,.46,.2,color,.35,.88,0,g)];ball(.29,'#e5b994',0,1.42,0,g);const hair=ball(.31,'#75553c',0,1.55,-.035,g);hair.scale.y=.65;cylinder(.35,.12,'#e7c481',0,1.72,0,g);cylinder(.23,.21,'#f1d396',0,1.84,0,g);for(const x of [-.105,.105])box(.04,.055,.025,'#35443a',x,1.44,.27,g);const rider=g.children.map(o=>({o,y:o.position.y,z:o.position.z}));
const mower=new THREE.Group();g.add(mower);mower.visible=false;
box(1.15,.16,1.65,'#476d40',0,.33,.1,mower);box(.9,.44,.8,'#ba5140',0,.62,.65,mower);box(.95,.1,.88,'#d76a4c',0,.87,.65,mower);box(.6,.12,.46,'#35463d',0,.85,-.3,mower);box(.6,.42,.12,'#35463d',0,1.04,-.55,mower);
box(.12,.55,.12,'#4b5c4c',0,1,.18,mower);const steering=mesh(new THREE.TorusGeometry(.23,.035,6,12),'#35443b',0,1.28,.18,mower);steering.rotation.x=Math.PI/3;
const wheels:THREE.Mesh[]=[];for(const x of [-.59,.59])for(const z of [-.5,.65]){const w=cylinder(.28,.18,'#34423a',x,.36,z,mower);w.rotation.z=Math.PI/2;wheels.push(w);}
const bike=new THREE.Group();g.add(bike);bike.visible=false;const bikeWheels:THREE.Group[]=[];
for(const z of [-.7,.7]){const wheel=new THREE.Group();wheel.position.set(0,.43,z);bike.add(wheel);bikeWheels.push(wheel);const tire=mesh(new THREE.TorusGeometry(.35,.055,6,16),'#3d4c46',0,0,0,wheel);tire.rotation.y=Math.PI/2;for(let i=0;i<4;i++){const spoke=box(.025,.66,.025,'#bfc8ad',0,0,0,wheel);spoke.rotation.x=i*Math.PI/4;}}
function frameBar(a:THREE.Vector3,b:THREE.Vector3){const bar=mesh(new THREE.CylinderGeometry(.045,.045,a.distanceTo(b),6),'#7aa5a0',0,0,0,bike);bar.position.copy(a).add(b).multiplyScalar(.5);bar.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),b.clone().sub(a).normalize())}
for(const [a,b]of [[[-.02,.43,-.7],[0,.9,-.2]],[[0,.9,-.2],[0,.43,0]],[[0,.43,0],[0,.43,-.7]],[[0,.9,-.2],[0,.95,.48]],[[0,.43,0],[0,.95,.48]],[[0,.43,.7],[0,1.17,.48]]])frameBar(new THREE.Vector3(...a),new THREE.Vector3(...b));
box(.42,.11,.3,'#756044',0,.98,-.2,bike);box(.6,.07,.07,'#65766b',0,1.18,.5,bike);box(.65,.28,.45,'#bca476',0,1.08,.85,bike);const basketPapers=box(.48,.15,.3,'#fff0d1',0,1.27,.85,bike);
const cart=new THREE.Group();g.add(cart);cart.visible=false;box(1.05,.15,1.05,'#759087',0,.46,-1.4,cart);for(const x of [-.53,.53]){const wheel=cylinder(.27,.13,'#3f4d43',x,.37,-1.4,cart);wheel.rotation.z=Math.PI/2;box(.06,.07,1.2,'#7e8a76',x, .75,-.85,cart)}const cartLoad=new THREE.Group();cart.add(cartLoad);for(let i=0;i<3;i++){box(.43,.4,.42,'#bf9466',(i%2-.5)*.48,.72+Math.floor(i/2)*.42,-1.4,cartLoad);box(.055,.42,.44,'#e8c487',(i%2-.5)*.48,.72+Math.floor(i/2)*.42,-1.4,cartLoad)}
const tool=new THREE.Group();g.add(tool);tool.visible=false;
const tools:Record<string,THREE.Group>={};for(const id of ['clean','garden','paper','deliver']){const held=new THREE.Group();tool.add(held);tools[id]=held;held.visible=false;}
box(.07,1,.07,'#b68a57',.47,.72,.35,tools.clean);box(.17,.09,.13,'#819183',.47,.28,.35,tools.clean);const rubbishBag=ball(.3,'#567064',-.45,.64,-.2,tools.clean);rubbishBag.scale.y=1.25;
cylinder(.19,.3,'#79a9b2',.47,.85,.3,tools.garden);const spout=box(.38,.08,.08,'#8cb8bd',.68,.9,.3,tools.garden);spout.rotation.z=.3;
box(.5,.09,.3,'#fff2cf',.3,.85,.43,tools.paper);box(.05,.1,.32,'#70967a',.3,.85,.43,tools.paper);
box(.5,.4,.4,'#bd925f',0,.9,.5,tools.deliver);box(.07,.42,.42,'#efcc85',0,.9,.5,tools.deliver);
g.userData={legs,arms,shirt,color,rider,mower,wheels,tool,tools,bike,bikeWheels,basketPapers,cart,cartLoad};scene.add(g);return g}
let you=avatar(live.current.player?.color??'#688aa1');you.position.set(0,0,5.8);const people=new Map<string,THREE.Group>();
const npcRoutes=[{name:'Pip · shopkeeper',color:'#b68065',x:-12,z:-1},{name:'June · gardener',color:'#8d9d61',x:-31,z:2},{name:'Milo · baker',color:'#9b87a9',x:12,z:14.5}];const npcs=npcRoutes.map(n=>{const g=avatar(n.color);g.position.set(n.x,0,n.z);return g});
const otherLabels=new Map<string,HTMLDivElement>();function label(id:string,text:string,g:THREE.Group){let l=otherLabels.get(id);if(!l){l=document.createElement('div');l.className='world-label';otherLabels.set(id,l);el.appendChild(l)}const v=g.position.clone().add(new THREE.Vector3(0,2.1,0)).project(camera);l.textContent=text;l.style.left=`${(v.x+1)*el.clientWidth/2}px`;l.style.top=`${(-v.y+1)*el.clientHeight/2}px`;l.style.display=Math.abs(v.x)<1.05&&Math.abs(v.y)<1.05?'block':'none'}
const playerLabel=document.createElement('div');playerLabel.className='world-label you';el.appendChild(playerLabel);
const selection=new THREE.Mesh(new THREE.RingGeometry(2.9,3.04,64),new THREE.MeshBasicMaterial({color:'#fff2b1',side:THREE.DoubleSide,transparent:true,opacity:.85}));selection.rotation.x=-Math.PI/2;selection.position.y=.23;scene.add(selection);selection.visible=false;
const destination=new THREE.Mesh(new THREE.RingGeometry(.22,.3,32),new THREE.MeshBasicMaterial({color:'#fff4c7',side:THREE.DoubleSide}));destination.rotation.x=-Math.PI/2;destination.position.y=.24;scene.add(destination);destination.visible=false;
let waypoints:{x:number;z:number}[]=[];let walkTo:THREE.Vector3|null=null;const keys=new Set<string>();let currentFocus=focus.current;let follow=false;let frame=0,last=performance.now(),lastNear='';let disposed=false;const plane=new THREE.Plane(new THREE.Vector3(0,1,0),0),raycaster=new THREE.Raycaster();
let movementTrail:{x:number;z:number}[]=[];let lastTrailPoint=you.position.clone();
const api:SceneApi={position:(consume=false)=>{const path=movementTrail;if(consume){movementTrail=[];lastTrailPoint.copy(you.position)}return{x:you.position.x,z:you.position.z,path}},navigate:(x,z)=>{waypoints=findPath({x:you.position.x,z:you.position.z},{x,z},blocked);const first=waypoints.shift();walkTo=first?new THREE.Vector3(first.x,0,first.z):null;follow=true;destination.position.set(x,.24,z);destination.visible=true},center:()=>{follow=true;currentFocus=null},orbit:(dy,dp=0)=>{yaw+=dy;pitch=clampPitch(pitch+dp)},pan:(dx,dy)=>{if(follow)cameraTarget.copy(target);follow=false;selection.visible=false;const scale=(camera.top-camera.bottom)/Math.max(1,el.clientHeight);const move=screenToGround(-dx*scale,-dy*scale/Math.sin(pitch),yaw);cameraTarget.x=THREE.MathUtils.clamp(cameraTarget.x+move.x,-65,65);cameraTarget.z=THREE.MathUtils.clamp(cameraTarget.z+move.z,-60,60)},resetCamera:()=>{yaw=DEFAULT_YAW;pitch=DEFAULT_PITCH;viewHeight=29;resize();follow=true;currentFocus=null},stop:()=>{walkTo=null;waypoints=[];keys.clear();destination.visible=false},zoom:(by)=>{viewHeight=THREE.MathUtils.clamp(viewHeight+by,14,55);resize()},setPosition:(x,z)=>{you.position.set(x,0,z);movementTrail=[];lastTrailPoint.copy(you.position);follow=true}};live.current.onReady?.(api);
function resize(){const w=el.clientWidth,h=el.clientHeight;renderer.setSize(w,h);const v=w<700?viewHeight*.85:viewHeight;camera.left=-v*w/h/2;camera.right=v*w/h/2;camera.top=v/2;camera.bottom=-v/2;camera.updateProjectionMatrix()}const observer=new ResizeObserver(resize);observer.observe(el);resize();
const keyDown=(e:KeyboardEvent)=>{if((e.target as HTMLElement).closest('input,textarea,[contenteditable=true],[role=dialog]'))return;const k=e.key.toLowerCase();if(e.altKey&&k.startsWith('arrow')){e.preventDefault();api.pan(k==='arrowleft'?40:k==='arrowright'?-40:0,k==='arrowup'?40:k==='arrowdown'?-40:0);return}if(k==='q'||k==='r'){e.preventDefault();api.orbit(k==='q'?-.16:.16);return}if(k===' '&&live.current.enabled&&live.current.player?.shift==='paper'&&live.current.onPaperAction){e.preventDefault();if(!e.repeat&&!live.current.working)live.current.onPaperAction();return}if(k===' '&&(e.target as HTMLElement).closest('button'))return;if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright','e',' '].includes(k)){e.preventDefault();keys.add(k);if(k==='e'||k===' ')live.current.onAction?.()}};const keyUp=(e:KeyboardEvent)=>keys.delete(e.key.toLowerCase());const blur=()=>keys.clear();window.addEventListener('keydown',keyDown);window.addEventListener('keyup',keyUp);window.addEventListener('blur',blur);
const removeCameraGestures=installCameraGestures(renderer.domElement,{mode:()=>live.current.cameraMode??'pan',viewHeight:()=>viewHeight,pan:api.pan,orbit:api.orbit,zoom:api.zoom,tap:(e)=>{const r=el.getBoundingClientRect();raycaster.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const hits=raycaster.intersectObjects([...taskObjects.entries()].filter(([id])=>{const t=TARGET_BY_ID.get(id);return t?t.job===live.current.player?.shift&&!(live.current.worldWork??[]).some(w=>w.id===t.group):BUILDINGS.some(b=>b.id===id)||STATIONS.some(s=>s.id===id&&s.jobs.includes(live.current.player?.shift??''))}).map(([,g])=>g),true).filter(hit=>{let o:THREE.Object3D|null=hit.object;while(o){if(!o.visible)return false;o=o.parent}return true});if(live.current.enabled&&hits.length){let o:THREE.Object3D|null=hits[0].object;while(o&&!o.userData.task)o=o.parent;if(o?.userData.task){live.current.onSelectTask?.(o.userData.task);return}}const p=new THREE.Vector3();if(raycaster.ray.intersectPlane(plane,p)){if(!live.current.enabled){const home=HOMES.find(h=>Math.abs(h.x-p.x)<3&&Math.abs(h.z-p.z)<3);if(home)live.current.onSelectHome?.(home.id);return}api.navigate(THREE.MathUtils.clamp(p.x,-60,60),THREE.MathUtils.clamp(p.z,-58,55))}}});
const wheel=(e:WheelEvent)=>{e.preventDefault();api.zoom(e.deltaY*.012)};renderer.domElement.addEventListener('wheel',wheel,{passive:false});
const blocked=isTownBlocked;
function mount(g:THREE.Group,mowing:boolean,moving:boolean,now:number,person?:Props['player']|Peer){const biking=person?.shift==='paper';g.userData.mower.visible=mowing;g.userData.bike.visible=biking;g.userData.basketPapers.visible=(person?.papers??0)>0;g.userData.cart.visible=person?.shift==='deliver';g.userData.cartLoad.visible=(person?.parcels??0)>0;for(const {o,y,z} of g.userData.rider){o.position.y=y+(mowing?.45:biking?.25:0);o.position.z=z-(mowing?.32:0)}if(mowing||biking){g.userData.legs.forEach((l:THREE.Mesh,i:number)=>l.rotation.x=biking&&moving?Math.sin(now*.014+i*Math.PI)*.7:-1);g.userData.arms.forEach((l:THREE.Mesh)=>l.rotation.x=-.7);if(biking&&moving)g.userData.bikeWheels.forEach((w:THREE.Group)=>w.rotation.x=now*.014);if(moving)g.userData.wheels.forEach((w:THREE.Mesh)=>w.rotation.x=now*.012)}g.userData.tool.visible=!!person?.shift&&!mowing;for(const [id,tool]of Object.entries(g.userData.tools) as [string,THREE.Group][])tool.visible=id===person?.shift&&id!=='paper'&&id!=='deliver';}
function animate(now:number){if(disposed)return;frame=requestAnimationFrame(animate);const dt=Math.min((now-last)/1000,.04);last=now;const p=live.current;if(focus.current!==currentFocus&&focus.current){currentFocus=focus.current;follow=false;cameraTarget.set(currentFocus[0],0,currentFocus[1]+(el.clientWidth<700?7:0));selection.position.set(currentFocus[0],.23,currentFocus[1]);selection.visible=true;}
if(p.player&&you.userData.color!==p.player.color){you.userData.color=p.player.color;you.userData.shirt.material=mat(p.player.color);you.userData.arms.forEach((arm:THREE.Mesh)=>arm.material=mat(p.player!.color))}
const beforeMove=you.position.clone();let vx=0,vz=0;const sx=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0)+(p.stick?.x??0);const sy=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0)+(p.stick?.y??0);
if(p.enabled){if(Math.abs(sx)+Math.abs(sy)>.08){const direction=screenToGround(sx,sy,yaw);vx=direction.x;vz=direction.z;walkTo=null;waypoints=[];follow=true;selection.visible=false;}else if(walkTo){vx=walkTo.x-you.position.x;vz=walkTo.z-you.position.z;if(Math.hypot(vx,vz)<.18){const next=waypoints.shift();walkTo=next?new THREE.Vector3(next.x,0,next.z):null;destination.visible=!!next;vx=0;vz=0}}const len=Math.hypot(vx,vz);if(len>.08&&!p.working){const speed=p.player?.mowing?3.2:p.player?.shift==='paper'?5:p.player?.shift==='deliver'?3:p.player?.items.includes('bike')?5:3.4;const dx=vx/len*speed*dt,dz=vz/len*speed*dt;const oldx=you.position.x,oldz=you.position.z;if(!blocked(you.position.x+dx,you.position.z))you.position.x=THREE.MathUtils.clamp(you.position.x+dx,-60,60);if(!blocked(you.position.x,you.position.z+dz))you.position.z=THREE.MathUtils.clamp(you.position.z+dz,-58,55);if(walkTo&&Math.abs(oldx-you.position.x)+Math.abs(oldz-you.position.z)<.001){walkTo=null;destination.visible=false}you.rotation.y=Math.atan2(vx,vz);you.position.y=Math.sin(now*.016)*.055;}else you.position.y=0;you.userData.legs.forEach((l:THREE.Mesh,i:number)=>l.rotation.x=len>.08?Math.sin(now*.015+i*Math.PI)*.4:0);you.userData.arms.forEach((l:THREE.Mesh,i:number)=>l.rotation.x=p.working?Math.sin(now*.018+i)*.7:len>.08?Math.sin(now*.015-i*Math.PI)*.3:0)}
you.position.y=groundHeight(you.position.x,you.position.z)+(p.enabled&&Math.hypot(vx,vz)>.08&&!p.working?Math.sin(now*.016)*.055:0);
if(you.position.distanceTo(lastTrailPoint)>.22){movementTrail.push({x:you.position.x,z:you.position.z});if(movementTrail.length>32)movementTrail.shift();lastTrailPoint.copy(you.position)}
mount(you,!!p.player?.mowing,Math.hypot(vx,vz)>.08,now,p.player);you.userData.tool.rotation.x=p.working?Math.sin(now*.012)*.3:0;
const watering=TARGET_BY_ID.get(p.player?.wateringTarget??'');waterDrops.visible=!!watering;
if(watering){you.rotation.y=Math.atan2(watering.x-you.position.x,watering.z-you.position.z);you.userData.tools.garden.rotation.z=-.35;for(let i=0;i<16;i++){const phase=(now*.0012+i/16)%1;waterMatrix.position.set(THREE.MathUtils.lerp(you.position.x,watering.x,phase),THREE.MathUtils.lerp(1.05,.25,phase)+Math.sin(phase*Math.PI)*.45,THREE.MathUtils.lerp(you.position.z,watering.z,phase));waterMatrix.scale.setScalar(1);waterMatrix.updateMatrix();waterDrops.setMatrixAt(i,waterMatrix.matrix)}waterDrops.instanceMatrix.needsUpdate=true}else you.userData.tools.garden.rotation.z=0;
if(p.rewardFx&&p.rewardFx.at!==lastReward){lastReward=p.rewardFx.at;const t=TARGET_BY_ID.get(p.rewardFx.target);if(t){flightStart=now;flightJob=t.job;flightOrigin.set(p.rewardFx.origin?.x??you.position.x,t.job==='paper'?1.35:1,p.rewardFx.origin?.z??you.position.z);flightTarget.set(t.x,t.kind==='mailbox'?1.25:.35,t.z);if(t.job==='clean'){const old=flightOrigin.clone();flightOrigin.copy(flightTarget);flightTarget.copy(old)}}}
const flight=(now-flightStart)/550;actionParticle.visible=!!p.rewardFx&&flightStart>0&&flight<1&&flightJob!=='garden';you.userData.arms[1].rotation.z=actionParticle.visible&&flightJob==='paper'?-Math.sin(Math.min(1,flight*2)*Math.PI)*1.4:0;if(actionParticle.visible){actionParticle.position.lerpVectors(flightOrigin,flightTarget,flight);actionParticle.position.y+=Math.sin(flight*Math.PI)*(flightJob==='paper'?.95:.7);actionParticle.rotation.set(flightJob==='paper'?flight*Math.PI*2:0,flight*5,0);flyingPaper.visible=flightJob!=='deliver';flyingParcel.visible=flightJob==='deliver'}
let grassDirty=false;if(p.lawnCuts!==lastServerCuts){lastServerCuts=p.lawnCuts;serverCuts=new Set(p.lawnCuts??[]);grassDirty=true;}
if(p.enabled&&p.player?.mowing){for(const c of sweptGrass(beforeMove.x,beforeMove.z,you.position.x,you.position.z)){if(!serverCuts.has(c.id)&&!optimisticCuts.has(c.id)){optimisticCuts.set(c.id,now+2200);clippingUntil=now+250;grassDirty=true}}}
for(const [id,expiry]of optimisticCuts)if(expiry<now||serverCuts.has(id)){optimisticCuts.delete(id);grassDirty=true}
if(grassDirty){const cutSet=new Set([...serverCuts,...optimisticCuts.keys()]);for(const id of previousCuts)if(!cutSet.has(id)){const i=grassIndices.get(id);if(i!==undefined)setGrassCut(i,false)}for(const id of cutSet)if(!previousCuts.has(id)){const i=grassIndices.get(id);if(i!==undefined)setGrassCut(i,true)}previousCuts=cutSet;grassTall.instanceMatrix.needsUpdate=true;}
clippings.visible=now<clippingUntil;if(clippings.visible)for(let j=0;j<18;j++){const phase=(now*.003+j*.137)%1;grassMatrix.position.set(you.position.x+Math.sin(j*2.3)*phase*.95,.3+Math.sin(phase*Math.PI)*.7,you.position.z+Math.cos(j*2.3)*phase*.95);grassMatrix.scale.setScalar(1-phase);grassMatrix.rotation.set(j,now*.003,j);grassMatrix.updateMatrix();clippings.setMatrixAt(j,grassMatrix.matrix)}clippings.instanceMatrix.needsUpdate=true;
if(follow){cameraTarget.copy(you.position);if(el.clientWidth>700){const lead=screenToGround(3.4,2.1,yaw);cameraTarget.x+=lead.x;cameraTarget.z+=lead.z;}selection.visible=false;}target.lerp(cameraTarget,reducedMotion?1:1-Math.exp(-dt*3));const view=cameraOffset(yaw,pitch);offset.set(view.x,view.y,view.z);camera.position.copy(target).add(offset);camera.lookAt(target);
const worldDone=new Map((p.worldWork??[]).map(w=>[w.id,w]));for(const t of WORK_TARGETS){const g=taskObjects.get(t.id)!,done=worldDone.get(t.group);g.userData.marker.visible=t.job===p.player?.shift&&!done;g.userData.marker.rotation.y=now*.001;g.userData.result.visible=t.job==='clean'?!done:!!done&&done.target===t.id&&!(t.job==='paper'&&actionParticle.visible&&p.rewardFx?.target===t.id);if(t.job==='garden'){const growth=done?Math.min(1,Math.max(0,(Date.now()-done.completed)/6000)):0;g.userData.foliage.scale.y=.45+growth*.85;g.userData.foliage.rotation.z=done?0:.24;if(g.userData.doneAt!==(done?.completed??0)){g.userData.doneAt=done?.completed??0;g.userData.soil.material=mat(done?'#786044':'#ba996d');g.userData.foliage.traverse((o:THREE.Object3D)=>{if(o instanceof THREE.Mesh&&o.geometry.type==='IcosahedronGeometry'&&o.position.y<.53)o.material=mat(done?'#e4a0bc':'#bfa879')})}}}
for(const station of STATIONS){const g=taskObjects.get(station.id)!;g.userData.marker.visible=station.jobs.includes(p.player?.shift??'');if(g.userData.marker.visible)label('station-'+station.id,station.title,g);else{otherLabels.get('station-'+station.id)?.remove();otherLabels.delete('station-'+station.id)}}
for(const b of BUILDINGS)label('building-'+b.id,b.name,taskObjects.get(b.id)!);
parkUpgrade.visible=(p.project??0)>=100;
const newKey=JSON.stringify(p.properties);if(newKey!==decorationKey){decorationKey=newKey;decorations.traverse(o=>{if(o instanceof THREE.Mesh)o.geometry.dispose()});decorations.clear();for(const property of p.properties??[]){const h=HOMES[property.home];if(property.items.includes('flowers'))for(let i=0;i<8;i++)flower(h.x-1.8+i*.32,h.z+2.7,'#e1a0bf',decorations);if(property.items.includes('bench'))bench(h.x+2,h.z+3,decorations);if(property.items.includes('home')){box(4.7,.2,1.8,'#b69d75',h.x,.35,h.z+2.8,decorations);for(const x of [-2,2])box(.12,2.1,.12,'#eee0b8',h.x+x,1.4,h.z+3.3,decorations)}}}
for(const peer of p.peers??[]){if(peer.id===p.player?.id)continue;let g=people.get(peer.id);if(!g){g=avatar(peer.color);g.position.set(peer.x,groundHeight(peer.x,peer.z),peer.z);people.set(peer.id,g)}if(g.userData.color!==peer.color){g.userData.color=peer.color;g.userData.shirt.material=mat(peer.color);g.userData.arms.forEach((arm:THREE.Mesh)=>arm.material=mat(peer.color))}const dx=peer.x-g.position.x,dz=peer.z-g.position.z;g.position.x+=dx*Math.min(1,dt*5);g.position.z+=dz*Math.min(1,dt*5);mount(g,!!peer.mowing,Math.hypot(dx,dz)>.04,now,peer);if(Math.hypot(dx,dz)>.04){g.rotation.y=Math.atan2(dx,dz);if(!peer.mowing&&peer.shift!=='paper')g.userData.legs.forEach((l:THREE.Mesh,i:number)=>l.rotation.x=Math.sin(now*.014+i*Math.PI)*.4)}}for(const [id,g] of people){if(!(p.peers??[]).some(a=>a.id===id)){scene.remove(g);people.delete(id);otherLabels.get(id)?.remove();otherLabels.delete(id)}}for(const peer of p.peers??[]){const g=people.get(peer.id);if(g){g.position.y=groundHeight(g.position.x,g.position.z);label(peer.id,peer.name,g)}}
npcs.forEach((g,i)=>{const route=npcRoutes[i];const phase=now*.00015+i*2;g.position.set(route.x+Math.sin(phase)*1.3,Math.sin(now*.012+i)*.025,route.z+Math.cos(phase)*.7);g.rotation.y=Math.atan2(Math.cos(phase),-Math.sin(phase));g.userData.legs.forEach((l:THREE.Mesh,j:number)=>l.rotation.x=Math.sin(now*.009+j*Math.PI)*.17)});if(!reducedMotion)windmill.rotation.z=now*.00013; npcs.forEach((g,i)=>label('npc-'+i,npcRoutes[i].name,g));
if(p.enabled){const candidates=[...WORK_TARGETS.filter(t=>t.job===p.player?.shift&&!worldDone.has(t.group)),...STATIONS.filter(s=>s.jobs.includes(p.player?.shift??'')),...(!p.player?.shift?[...BUILDINGS.map(b=>({id:b.id,...entrance(b)})),{id:'park',...PARK}]:[])];const nearest=candidates.sort((a,b)=>Math.hypot(a.x-you.position.x,a.z-you.position.z)-Math.hypot(b.x-you.position.x,b.z-you.position.z))[0];const id=nearest&&Math.hypot(nearest.x-you.position.x,nearest.z-you.position.z)<1.9?nearest.id:'';if(id!==lastNear){lastNear=id;p.onNear?.(id||null)}}
const labelP=you.position.clone().add(new THREE.Vector3(0,2.1,0)).project(camera);playerLabel.style.left=`${(labelP.x+1)*el.clientWidth/2}px`;playerLabel.style.top=`${(-labelP.y+1)*el.clientHeight/2}px`;playerLabel.textContent=p.player?.name??'You';playerLabel.style.display=p.enabled?'block':'none';renderer.render(scene,camera)}
frame=requestAnimationFrame(animate);
return()=>{disposed=true;cancelAnimationFrame(frame);observer.disconnect();window.removeEventListener('keydown',keyDown);window.removeEventListener('keyup',keyUp);window.removeEventListener('blur',blur);removeCameraGestures();renderer.domElement.removeEventListener('wheel',wheel);scene.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();const ms=Array.isArray(o.material)?o.material:[o.material];ms.forEach(m=>m.dispose())}});renderer.dispose();renderer.domElement.remove();playerLabel.remove();otherLabels.forEach(l=>l.remove())};},[]);
return <div className="world" ref={host} aria-label="Interactive three dimensional town">{error&&<div role="alert" className="world-error">{error}</div>}</div>}
