import {db} from '@/db/raw';
import {HOMES,JOBS,TASKS,SHOP,SCHOOL,PARK,COLORS} from '@/app/game/data';
type Row={id:string;token_hash:string;town_id:string;name:string;color:string;home:number|null;job:string|null;coins:number;xp:number;education:number;last_study:string|null;x:number;z:number;items:string;seen:number;created:number};
const json=(body:unknown,status=200,cookie?:string)=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store',...(cookie?{'Set-Cookie':cookie}:{})}});
const token=()=>Array.from(crypto.getRandomValues(new Uint8Array(24)),x=>x.toString(16).padStart(2,'0')).join('');
async function hash(s:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))),x=>x.toString(16).padStart(2,'0')).join('')}
async function auth(req:Request){const id=req.headers.get('oai-authenticated-user-id');return id?await db().prepare('SELECT * FROM residents WHERE token_hash=?').bind(await hash(id)).first<Row>():null}
async function state(r:Row){const d=db();const now=Date.now();const [town,people,completed,history]=await Promise.all([d.prepare('SELECT * FROM towns WHERE id=?').bind(r.town_id).first<any>(),d.prepare('SELECT id,name,color,home,items,x,z,seen FROM residents WHERE town_id=?').bind(r.town_id).all<any>(),d.prepare('SELECT task FROM work WHERE town_id=? AND completed>?').bind(r.town_id,now-120000).all<{task:string}>(),d.prepare('SELECT name,text FROM events WHERE town_id=? ORDER BY created DESC LIMIT 6').bind(r.town_id).all()]);return {resident:{id:r.id,name:r.name,color:r.color,home:r.home,job:r.job,coins:r.coins,xp:r.xp,education:r.education,lastStudy:r.last_study,x:r.x,z:r.z,items:JSON.parse(r.items)},town:{id:town.id,name:town.name,private:!!town.private,key:town.invite??undefined,treasury:town.treasury,project:town.project,prosperity:Math.min(100,50+Math.floor(town.project/4)+completed.results.length*2),residents:people.results.length},peers:people.results.filter(p=>p.seen>now-12000).map(({seen,home,items,...p})=>p),properties:people.results.filter(p=>p.home!==null).map(p=>({home:p.home,items:JSON.parse(p.items),name:p.name})),occupied:people.results.filter(p=>p.home!==null).map(p=>p.home),completed:completed.results.map(t=>t.task),events:history.results}}
export async function GET(req:Request){try{const r=await auth(req);return json(r?await state(r):{resident:null})}catch(e){console.error('town state',e);return json({error:'The town is taking a moment to connect. Please try again.'},503)}}
export async function POST(req:Request){try{const origin=req.headers.get('origin');if(origin&&new URL(origin).host!==new URL(req.url).host)return json({error:'Please use this town’s own game page.'},403);const b=await req.json() as Record<string,any>;const d=db(),now=Date.now();let r=await auth(req);
if(b.action==='join'){const account=req.headers.get('oai-authenticated-user-id');if(!account)return json({error:'Sign in to keep your resident and town saved across devices.'},401);if(r)return json(await state(r));const name=String(b.name??'').trim().slice(0,24);if(name.length<2)return json({error:'Please enter a name with at least two letters.'},400);let townId:string;const mode=b.mode;if(mode==='private'){townId=crypto.randomUUID();const invite=token().slice(0,16).toUpperCase();await d.prepare('INSERT INTO towns(id,name,invite,private,created) VALUES(?,?,?,?,?)').bind(townId,String(b.townName||`${name}’s Hollow`).trim().slice(0,32),invite,1,now).run()}else if(mode==='key'){const town=await d.prepare('SELECT id FROM towns WHERE invite=?').bind(String(b.key??'').trim().toUpperCase()).first<{id:string}>();if(!town)return json({error:'No town has that invitation key. Check it and try again.'},404);townId=town.id}else{await d.prepare("INSERT OR IGNORE INTO towns(id,name,private,created) VALUES('willowbrook','Willowbrook',0,?)").bind(now).run();const town=await d.prepare('SELECT t.id FROM towns t LEFT JOIN residents r ON r.town_id=t.id WHERE t.private=0 GROUP BY t.id HAVING COUNT(r.id)<50 ORDER BY COUNT(r.id) DESC,t.created LIMIT 1').first<{id:string}>();if(town)townId=town.id;else{townId=crypto.randomUUID();await d.prepare('INSERT INTO towns(id,name,private,created) VALUES(?,?,0,?)').bind(townId,`Willowbrook ${now.toString().slice(-4)}`,now).run()}}
const id=crypto.randomUUID();const result=await d.prepare('INSERT INTO residents(id,token_hash,town_id,name,color,seen,created) SELECT ?,?,?,?,?,?,? WHERE (SELECT COUNT(*) FROM residents WHERE town_id=?)<50 RETURNING *').bind(id,await hash(account),townId,name,COLORS.includes(b.color)?b.color:COLORS[0],now,now,townId).first<Row>();if(!result)return json({error:'This town has reached 50 residents. Please choose another town.'},409);return json(await state(result))}
if(!r)return json({error:'Join a town or enter your resident pass first.'},401);
if(b.action==='setup'){const job=JOBS.find(j=>j.id===b.job);const h=HOMES.find(h=>h.id===b.home);if(!job||!h)return json({error:'Choose one of the available jobs and homes.'},400);if(r.home!==null)return json(await state(r));try{await d.prepare('UPDATE residents SET job=?,home=? WHERE id=? AND home IS NULL').bind(job.id,h.id,r.id).run()}catch{return json({error:'A neighbor just chose that home. Please choose another.'},409)}await d.prepare('INSERT INTO events(id,town_id,name,text,created) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),r.town_id,r.name,`moved into ${h.name}`,now).run()}
else if(b.action==='heartbeat'){const x=Number(b.x),z=Number(b.z);if(!Number.isFinite(x)||!Number.isFinite(z)||Math.abs(x)>60||z< -58||z>55)return json({error:'Stay inside the town boundary.'},400);const elapsed=Math.max(.1,Math.min((now-r.seen)/1000,3));const inBuilding=HOMES.some(h=>Math.abs(h.x-x)<2.3&&Math.abs(h.z-z)<1.95);const inRiver=x>23.2&&x<32.8&&Math.abs(z)>2.35;const allowed=Math.hypot(x-r.x,z-r.z)<=6*elapsed+1&&!inBuilding&&!inRiver;await d.prepare('UPDATE residents SET x=?,z=?,seen=? WHERE id=?').bind(allowed?x:r.x,allowed?z:r.z,now,r.id).run();r=(await d.prepare('SELECT * FROM residents WHERE id=?').bind(r.id).first<Row>())!;return json({...await state(r),corrected:!allowed})}
else if(b.action==='begin'){if(r.home===null)return json({error:'Choose a home and job first.'},400);const t=TASKS.find(t=>t.id===b.task);if(!t||Math.hypot(t.x-r.x,t.z-r.z)>2.7)return json({error:'Walk a little closer to the work site.'},400);const key=`${r.town_id}:${t.id}`;const claim=await d.prepare('INSERT INTO work(key,town_id,task,resident_id,started) VALUES(?,?,?,?,?) ON CONFLICT(key) DO UPDATE SET resident_id=excluded.resident_id,started=excluded.started,steps=0,last_step=0,completed=0 WHERE (work.completed>0 AND work.completed<?) OR (work.completed=0 AND MAX(work.started,work.last_step)<?) RETURNING *').bind(key,r.town_id,t.id,r.id,now,now-120000,now-60000).first();if(!claim){const existing=await d.prepare('SELECT * FROM work WHERE key=? AND resident_id=? AND completed=0').bind(key,r.id).first();if(!existing)return json({error:'A neighbor is taking care of this one. Try another nearby task.'},409);return json({work:existing})}return json({work:claim})}
else if(b.action==='step'){const t=TASKS.find(t=>t.id===b.task);if(!t||Math.hypot(t.x-r.x,t.z-r.z)>2.7)return json({error:'Stay near the work site to finish.'},400);const w=await d.prepare('UPDATE work SET steps=MIN(5,steps+1),last_step=? WHERE key=? AND resident_id=? AND completed=0 AND started>? AND last_step<? RETURNING *').bind(now,`${r.town_id}:${t.id}`,r.id,now-180000,now-600).first<any>();if(!w)return json({error:'Take a moment between actions, then try again.'},409);return json({work:w})}
else if(b.action==='finish'){const t=TASKS.find(t=>t.id===b.task);if(!t||Math.hypot(t.x-r.x,t.z-r.z)>2.7)return json({error:'Walk back to your task to finish.'},400);const key=`${r.town_id}:${t.id}`;const w=await d.prepare('SELECT * FROM work WHERE key=? AND resident_id=?').bind(key,r.id).first<any>();if(!w||w.steps<5||now-w.started<5000)return json({error:'Finish all five steps before collecting your pay.'},400);if(w.completed)return json({...await state(r),reward:null});const pay=r.job===t.job?29:24;await d.batch([d.prepare('UPDATE residents SET coins=coins+?,xp=xp+10 WHERE id=? AND EXISTS(SELECT 1 FROM work WHERE key=? AND resident_id=? AND completed=0)').bind(pay,r.id,key,r.id),d.prepare('UPDATE towns SET treasury=treasury+1 WHERE id=? AND EXISTS(SELECT 1 FROM work WHERE key=? AND resident_id=? AND completed=0)').bind(r.town_id,key,r.id),d.prepare('INSERT INTO events(id,town_id,name,text,created) SELECT ?,?,?,?,? WHERE EXISTS(SELECT 1 FROM work WHERE key=? AND resident_id=? AND completed=0)').bind(crypto.randomUUID(),r.town_id,r.name,`finished ${t.title.toLowerCase()}`,now,key,r.id),d.prepare('UPDATE work SET completed=? WHERE key=? AND resident_id=? AND completed=0').bind(now,key,r.id)]);r=(await d.prepare('SELECT * FROM residents WHERE id=?').bind(r.id).first<Row>())!;return json({...await state(r),reward:{coins:pay,xp:10,tax:1}})}
else if(b.action==='buy'){const item=SHOP.find(s=>s.id===b.item);if(!item)return json({error:'That item is not in the shop.'},400);const items=JSON.parse(r.items) as string[];if(items.includes(item.id))return json({error:'You already own this.'},409);const updated=await d.prepare('UPDATE residents SET coins=coins-?,items=json_insert(items,\'$[#]\',?) WHERE id=? AND coins>=? AND NOT EXISTS(SELECT 1 FROM json_each(residents.items) WHERE value=?) RETURNING *').bind(item.price,item.id,r.id,item.price,item.id).first<Row>();if(!updated)return json({error:'Save a few more coins for this one.'},409)}
else if(b.action==='donate'){if(r.coins<25)return json({error:'You need 25 coins to sponsor a garden bed.'},400);const town=await d.prepare('SELECT project FROM towns WHERE id=?').bind(r.town_id).first<{project:number}>();if(!town||town.project>=100)return json({error:'The pocket park is already open. Thank you!' },409);await d.batch([d.prepare('UPDATE residents SET coins=coins-25 WHERE id=? AND coins>=25 AND EXISTS(SELECT 1 FROM towns WHERE id=? AND project<100)').bind(r.id,r.town_id),d.prepare('UPDATE towns SET project=MIN(100,project+10) WHERE id=? AND project<100 AND changes()=1').bind(r.town_id)]);}
else if(b.action==='study'){if(Math.hypot(r.x-SCHOOL.x,r.z-SCHOOL.z)>3)return json({error:'Visit the school entrance for today’s lesson.'},400);if(b.answer!=='everyone')return json({error:'Try again: public projects belong to the whole town.'},400);const today=new Date().toISOString().slice(0,10);const updated=await d.prepare('UPDATE residents SET education=MIN(30,education+1),last_study=? WHERE id=? AND (last_study IS NULL OR last_study<>?) RETURNING *').bind(today,r.id,today).first();if(!updated)return json({error:'You have already completed today’s lesson. Come back tomorrow.'},409)}
else if(b.action==='job'){if(!JOBS.some(j=>j.id===b.job))return json({error:'Choose a job on the board.'},400);await d.prepare('UPDATE residents SET job=? WHERE id=?').bind(b.job,r.id).run()}

else return json({error:'That town action is not available.'},400);
r=(await d.prepare('SELECT * FROM residents WHERE id=?').bind(r.id).first<Row>())!;return json(await state(r));
}catch(e){console.error('town action',e);return json({error:'That action could not be saved. Please try again.'},500)}}
